/* TaskView.c generated by valac 0.54.3, the Vala compiler
 * generated from TaskView.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <gdk/gdk.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_TASK_VIEW (agenda_task_view_get_type ())
#define AGENDA_TASK_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_VIEW, AgendaTaskView))
#define AGENDA_TASK_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_VIEW, AgendaTaskViewClass))
#define AGENDA_IS_TASK_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_VIEW))
#define AGENDA_IS_TASK_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_VIEW))
#define AGENDA_TASK_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_VIEW, AgendaTaskViewClass))

typedef struct _AgendaTaskView AgendaTaskView;
typedef struct _AgendaTaskViewClass AgendaTaskViewClass;
typedef struct _AgendaTaskViewPrivate AgendaTaskViewPrivate;

#define AGENDA_TYPE_TASK_LIST (agenda_task_list_get_type ())
#define AGENDA_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskList))
#define AGENDA_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))
#define AGENDA_IS_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_LIST))
#define AGENDA_IS_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_LIST))
#define AGENDA_TASK_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))

typedef struct _AgendaTaskList AgendaTaskList;
typedef struct _AgendaTaskListClass AgendaTaskListClass;
enum  {
	AGENDA_TASK_VIEW_0_PROPERTY,
	AGENDA_TASK_VIEW_NUM_PROPERTIES
};
static GParamSpec* agenda_task_view_properties[AGENDA_TASK_VIEW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_GtkTreePath_free0(var) ((var == NULL) ? NULL : (var = (_vala_GtkTreePath_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef enum  {
	AGENDA_TASK_LIST_COLUMNS_TOGGLE,
	AGENDA_TASK_LIST_COLUMNS_TEXT,
	AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH,
	AGENDA_TASK_LIST_COLUMNS_DELETE,
	AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE,
	AGENDA_TASK_LIST_COLUMNS_ID,
	AGENDA_TASK_LIST_COLUMNS_N_COLUMNS
} AgendaTaskListColumns;

#define AGENDA_TASK_LIST_TYPE_COLUMNS (agenda_task_list_columns_get_type ())

struct _AgendaTaskView {
	GtkTreeView parent_instance;
	AgendaTaskViewPrivate * priv;
	gboolean is_editing;
};

struct _AgendaTaskViewClass {
	GtkTreeViewClass parent_class;
};

struct _AgendaTaskViewPrivate {
	AgendaTaskList* task_list;
};

static gint AgendaTaskView_private_offset;
static gpointer agenda_task_view_parent_class = NULL;

VALA_EXTERN GType agenda_task_view_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskView, g_object_unref)
VALA_EXTERN GType agenda_task_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskList, g_object_unref)
VALA_EXTERN AgendaTaskView* agenda_task_view_new_with_list (AgendaTaskList* list);
VALA_EXTERN AgendaTaskView* agenda_task_view_construct_with_list (GType object_type,
                                                      AgendaTaskList* list);
VALA_EXTERN void agenda_task_view_toggle_selected_task (AgendaTaskView* self);
VALA_EXTERN void agenda_task_list_toggle_task (AgendaTaskList* self,
                                   GtkTreePath* path);
static void _vala_GtkTreePath_free (GtkTreePath* self);
static void agenda_task_view_list_row_activated (AgendaTaskView* self,
                                          GtkTreePath* path,
                                          GtkTreeViewColumn* column);
VALA_EXTERN gboolean agenda_task_list_remove_task (AgendaTaskList* self,
                                       GtkTreePath* path);
static gboolean agenda_task_view_task_is_empty (AgendaTaskView* self,
                                         const gchar* task);
static void agenda_task_view_toggle_clicked (AgendaTaskView* self,
                                      GtkCellRendererToggle* toggle,
                                      const gchar* path);
static void agenda_task_view_text_edited (AgendaTaskView* self,
                                   const gchar* path,
                                   const gchar* edited_text);
VALA_EXTERN void agenda_task_list_set_task_text (AgendaTaskList* self,
                                     const gchar* path,
                                     const gchar* text);
VALA_EXTERN AgendaTaskView* agenda_task_view_new (void);
VALA_EXTERN AgendaTaskView* agenda_task_view_construct (GType object_type);
static GObject * agenda_task_view_constructor (GType type,
                                        guint n_construct_properties,
                                        GObjectConstructParam * construct_properties);
VALA_EXTERN GType agenda_task_list_columns_get_type (void) G_GNUC_CONST ;
static void _agenda_task_view___lambda4_ (AgendaTaskView* self,
                                   GtkCellEditable* editable,
                                   const gchar* path);
static void __agenda_task_view___lambda4__gtk_cell_renderer_editing_started (GtkCellRenderer* _sender,
                                                                      GtkCellEditable* editable,
                                                                      const gchar* path,
                                                                      gpointer self);
static void _agenda_task_view___lambda5_ (AgendaTaskView* self);
static void __agenda_task_view___lambda5__gtk_cell_renderer_editing_canceled (GtkCellRenderer* _sender,
                                                                       gpointer self);
static void _agenda_task_view_text_edited_gtk_cell_renderer_text_edited (GtkCellRendererText* _sender,
                                                                  const gchar* path,
                                                                  const gchar* new_text,
                                                                  gpointer self);
static void _agenda_task_view_toggle_clicked_gtk_cell_renderer_toggle_toggled (GtkCellRendererToggle* _sender,
                                                                        const gchar* path,
                                                                        gpointer self);
static void _agenda_task_view_list_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender,
                                                                       GtkTreePath* path,
                                                                       GtkTreeViewColumn* column,
                                                                       gpointer self);
static gboolean _agenda_task_view___lambda6_ (AgendaTaskView* self,
                                       GdkEventButton* event);
static gboolean __agenda_task_view___lambda6__gtk_widget_button_press_event (GtkWidget* _sender,
                                                                      GdkEventButton* event,
                                                                      gpointer self);
static void agenda_task_view_finalize (GObject * obj);
static GType agenda_task_view_get_type_once (void);

static inline gpointer
agenda_task_view_get_instance_private (AgendaTaskView* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaTaskView_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 30 "../src/Widgets/TaskView.vala"
	return self ? g_object_ref (self) : NULL;
#line 154 "TaskView.c"
}

AgendaTaskView*
agenda_task_view_construct_with_list (GType object_type,
                                      AgendaTaskList* list)
{
	AgendaTaskView * self = NULL;
	AgendaTaskList* _tmp0_;
	AgendaTaskList* _tmp1_;
#line 29 "../src/Widgets/TaskView.vala"
	g_return_val_if_fail (list != NULL, NULL);
#line 29 "../src/Widgets/TaskView.vala"
	self = (AgendaTaskView*) g_object_new (object_type, NULL);
#line 30 "../src/Widgets/TaskView.vala"
	_tmp0_ = _g_object_ref0 (list);
#line 30 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (self->priv->task_list);
#line 30 "../src/Widgets/TaskView.vala"
	self->priv->task_list = _tmp0_;
#line 31 "../src/Widgets/TaskView.vala"
	_tmp1_ = self->priv->task_list;
#line 31 "../src/Widgets/TaskView.vala"
	gtk_tree_view_set_model ((GtkTreeView*) self, (GtkTreeModel*) _tmp1_);
#line 29 "../src/Widgets/TaskView.vala"
	return self;
#line 180 "TaskView.c"
}

AgendaTaskView*
agenda_task_view_new_with_list (AgendaTaskList* list)
{
#line 29 "../src/Widgets/TaskView.vala"
	return agenda_task_view_construct_with_list (AGENDA_TYPE_TASK_VIEW, list);
#line 188 "TaskView.c"
}

static void
_vala_GtkTreePath_free (GtkTreePath* self)
{
#line 108 "../src/Widgets/TaskView.vala"
	g_boxed_free (gtk_tree_path_get_type (), self);
#line 196 "TaskView.c"
}

void
agenda_task_view_toggle_selected_task (AgendaTaskView* self)
{
	GtkTreeIter iter = {0};
	GtkTreeSelection* tree_selection = NULL;
	GtkTreeSelection* _tmp0_;
	GtkTreeSelection* _tmp1_;
	GtkTreeSelection* _tmp2_;
	GtkTreeIter _tmp3_ = {0};
	GtkTreePath* path = NULL;
	AgendaTaskList* _tmp4_;
	GtkTreeIter _tmp5_;
	GtkTreePath* _tmp6_;
	GtkTreePath* _tmp7_;
	GtkTreePath* _tmp10_;
#line 108 "../src/Widgets/TaskView.vala"
	g_return_if_fail (self != NULL);
#line 111 "../src/Widgets/TaskView.vala"
	_tmp0_ = gtk_tree_view_get_selection ((GtkTreeView*) self);
#line 111 "../src/Widgets/TaskView.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 111 "../src/Widgets/TaskView.vala"
	tree_selection = _tmp1_;
#line 112 "../src/Widgets/TaskView.vala"
	_tmp2_ = tree_selection;
#line 112 "../src/Widgets/TaskView.vala"
	gtk_tree_selection_get_selected (_tmp2_, NULL, &_tmp3_);
#line 112 "../src/Widgets/TaskView.vala"
	iter = _tmp3_;
#line 113 "../src/Widgets/TaskView.vala"
	_tmp4_ = self->priv->task_list;
#line 113 "../src/Widgets/TaskView.vala"
	_tmp5_ = iter;
#line 113 "../src/Widgets/TaskView.vala"
	_tmp6_ = gtk_tree_model_get_path ((GtkTreeModel*) _tmp4_, &_tmp5_);
#line 113 "../src/Widgets/TaskView.vala"
	path = _tmp6_;
#line 114 "../src/Widgets/TaskView.vala"
	_tmp7_ = path;
#line 114 "../src/Widgets/TaskView.vala"
	if (_tmp7_ != NULL) {
#line 240 "TaskView.c"
		AgendaTaskList* _tmp8_;
		GtkTreePath* _tmp9_;
#line 115 "../src/Widgets/TaskView.vala"
		_tmp8_ = self->priv->task_list;
#line 115 "../src/Widgets/TaskView.vala"
		_tmp9_ = path;
#line 115 "../src/Widgets/TaskView.vala"
		agenda_task_list_toggle_task (_tmp8_, _tmp9_);
#line 249 "TaskView.c"
	}
#line 118 "../src/Widgets/TaskView.vala"
	_tmp10_ = path;
#line 118 "../src/Widgets/TaskView.vala"
	path = NULL;
#line 118 "../src/Widgets/TaskView.vala"
	gtk_tree_path_free (_tmp10_);
#line 108 "../src/Widgets/TaskView.vala"
	__vala_GtkTreePath_free0 (path);
#line 108 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (tree_selection);
#line 261 "TaskView.c"
}

static void
agenda_task_view_list_row_activated (AgendaTaskView* self,
                                     GtkTreePath* path,
                                     GtkTreeViewColumn* column)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
#line 121 "../src/Widgets/TaskView.vala"
	g_return_if_fail (self != NULL);
#line 121 "../src/Widgets/TaskView.vala"
	g_return_if_fail (path != NULL);
#line 121 "../src/Widgets/TaskView.vala"
	g_return_if_fail (column != NULL);
#line 122 "../src/Widgets/TaskView.vala"
	_tmp0_ = gtk_tree_view_column_get_title (column);
#line 122 "../src/Widgets/TaskView.vala"
	_tmp1_ = _tmp0_;
#line 122 "../src/Widgets/TaskView.vala"
	if (g_strcmp0 (_tmp1_, "Delete") == 0) {
#line 283 "TaskView.c"
		AgendaTaskList* _tmp2_;
#line 123 "../src/Widgets/TaskView.vala"
		_tmp2_ = self->priv->task_list;
#line 123 "../src/Widgets/TaskView.vala"
		agenda_task_list_remove_task (_tmp2_, path);
#line 289 "TaskView.c"
	}
}

/**
         * Check if the task is an empty string, or only has white space.
         *
         * @return True if task is empty
         */
static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result = NULL;
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1535 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 317 "TaskView.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 321 "TaskView.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 327 "TaskView.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 331 "TaskView.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp0_) {
#line 335 "TaskView.c"
		gchar* _tmp2_;
#line 1536 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1536 "glib-2.0.vapi"
		result = _tmp2_;
#line 1536 "glib-2.0.vapi"
		return result;
#line 343 "TaskView.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1539 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1539 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1539 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1539 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1539 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1539 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1539 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1539 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 371 "TaskView.c"
				goto __catch0_g_regex_error;
			}
#line 1539 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1539 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1539 "glib-2.0.vapi"
			return NULL;
#line 380 "TaskView.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1540 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1540 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1540 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1540 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 394 "TaskView.c"
				goto __catch0_g_regex_error;
			}
#line 1540 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1540 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1540 "glib-2.0.vapi"
			return NULL;
#line 403 "TaskView.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1540 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1540 "glib-2.0.vapi"
		result = _tmp10_;
#line 1540 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
		return result;
#line 417 "TaskView.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
#line 1538 "glib-2.0.vapi"
		g_clear_error (&_inner_error0_);
#line 1542 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 426 "TaskView.c"
	}
	__finally0:
#line 1538 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1538 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1538 "glib-2.0.vapi"
	return NULL;
#line 435 "TaskView.c"
}

static gboolean
agenda_task_view_task_is_empty (AgendaTaskView* self,
                                const gchar* task)
{
	gboolean _tmp0_ = FALSE;
	gboolean result = FALSE;
#line 132 "../src/Widgets/TaskView.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 132 "../src/Widgets/TaskView.vala"
	g_return_val_if_fail (task != NULL, FALSE);
#line 133 "../src/Widgets/TaskView.vala"
	if (g_strcmp0 (task, "") == 0) {
#line 133 "../src/Widgets/TaskView.vala"
		_tmp0_ = TRUE;
#line 452 "TaskView.c"
	} else {
		gchar* _tmp1_;
		gchar* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
#line 133 "../src/Widgets/TaskView.vala"
		_tmp1_ = string_replace (task, " ", "");
#line 133 "../src/Widgets/TaskView.vala"
		_tmp2_ = _tmp1_;
#line 133 "../src/Widgets/TaskView.vala"
		_tmp3_ = strlen (_tmp2_);
#line 133 "../src/Widgets/TaskView.vala"
		_tmp4_ = _tmp3_;
#line 133 "../src/Widgets/TaskView.vala"
		_tmp0_ = _tmp4_ == 0;
#line 133 "../src/Widgets/TaskView.vala"
		_g_free0 (_tmp2_);
#line 470 "TaskView.c"
	}
#line 133 "../src/Widgets/TaskView.vala"
	if (_tmp0_) {
#line 134 "../src/Widgets/TaskView.vala"
		result = TRUE;
#line 134 "../src/Widgets/TaskView.vala"
		return result;
#line 478 "TaskView.c"
	} else {
#line 136 "../src/Widgets/TaskView.vala"
		result = FALSE;
#line 136 "../src/Widgets/TaskView.vala"
		return result;
#line 484 "TaskView.c"
	}
}

static void
agenda_task_view_toggle_clicked (AgendaTaskView* self,
                                 GtkCellRendererToggle* toggle,
                                 const gchar* path)
{
	GtkTreePath* tree_path = NULL;
	GtkTreePath* _tmp0_;
	AgendaTaskList* _tmp1_;
#line 140 "../src/Widgets/TaskView.vala"
	g_return_if_fail (self != NULL);
#line 140 "../src/Widgets/TaskView.vala"
	g_return_if_fail (toggle != NULL);
#line 140 "../src/Widgets/TaskView.vala"
	g_return_if_fail (path != NULL);
#line 141 "../src/Widgets/TaskView.vala"
	_tmp0_ = gtk_tree_path_new_from_string (path);
#line 141 "../src/Widgets/TaskView.vala"
	tree_path = _tmp0_;
#line 142 "../src/Widgets/TaskView.vala"
	_tmp1_ = self->priv->task_list;
#line 142 "../src/Widgets/TaskView.vala"
	agenda_task_list_toggle_task (_tmp1_, tree_path);
#line 140 "../src/Widgets/TaskView.vala"
	__vala_GtkTreePath_free0 (tree_path);
#line 512 "TaskView.c"
}

static void
agenda_task_view_text_edited (AgendaTaskView* self,
                              const gchar* path,
                              const gchar* edited_text)
{
	AgendaTaskList* _tmp0_;
#line 145 "../src/Widgets/TaskView.vala"
	g_return_if_fail (self != NULL);
#line 145 "../src/Widgets/TaskView.vala"
	g_return_if_fail (path != NULL);
#line 145 "../src/Widgets/TaskView.vala"
	g_return_if_fail (edited_text != NULL);
#line 147 "../src/Widgets/TaskView.vala"
	if (agenda_task_view_task_is_empty (self, edited_text)) {
#line 148 "../src/Widgets/TaskView.vala"
		return;
#line 531 "TaskView.c"
	}
#line 150 "../src/Widgets/TaskView.vala"
	_tmp0_ = self->priv->task_list;
#line 150 "../src/Widgets/TaskView.vala"
	agenda_task_list_set_task_text (_tmp0_, path, edited_text);
#line 151 "../src/Widgets/TaskView.vala"
	self->is_editing = FALSE;
#line 539 "TaskView.c"
}

AgendaTaskView*
agenda_task_view_construct (GType object_type)
{
	AgendaTaskView * self = NULL;
#line 24 "../src/Widgets/TaskView.vala"
	self = (AgendaTaskView*) g_object_new (object_type, NULL);
#line 24 "../src/Widgets/TaskView.vala"
	return self;
#line 550 "TaskView.c"
}

AgendaTaskView*
agenda_task_view_new (void)
{
#line 24 "../src/Widgets/TaskView.vala"
	return agenda_task_view_construct (AGENDA_TYPE_TASK_VIEW);
#line 558 "TaskView.c"
}

static void
_agenda_task_view___lambda4_ (AgendaTaskView* self,
                              GtkCellEditable* editable,
                              const gchar* path)
{
#line 84 "../src/Widgets/TaskView.vala"
	g_return_if_fail (editable != NULL);
#line 84 "../src/Widgets/TaskView.vala"
	g_return_if_fail (path != NULL);
#line 85 "../src/Widgets/TaskView.vala"
	self->is_editing = TRUE;
#line 572 "TaskView.c"
}

static void
__agenda_task_view___lambda4__gtk_cell_renderer_editing_started (GtkCellRenderer* _sender,
                                                                 GtkCellEditable* editable,
                                                                 const gchar* path,
                                                                 gpointer self)
{
#line 84 "../src/Widgets/TaskView.vala"
	_agenda_task_view___lambda4_ ((AgendaTaskView*) self, editable, path);
#line 583 "TaskView.c"
}

static void
_agenda_task_view___lambda5_ (AgendaTaskView* self)
{
#line 89 "../src/Widgets/TaskView.vala"
	self->is_editing = FALSE;
#line 591 "TaskView.c"
}

static void
__agenda_task_view___lambda5__gtk_cell_renderer_editing_canceled (GtkCellRenderer* _sender,
                                                                  gpointer self)
{
#line 88 "../src/Widgets/TaskView.vala"
	_agenda_task_view___lambda5_ ((AgendaTaskView*) self);
#line 600 "TaskView.c"
}

static void
_agenda_task_view_text_edited_gtk_cell_renderer_text_edited (GtkCellRendererText* _sender,
                                                             const gchar* path,
                                                             const gchar* new_text,
                                                             gpointer self)
{
#line 92 "../src/Widgets/TaskView.vala"
	agenda_task_view_text_edited ((AgendaTaskView*) self, path, new_text);
#line 611 "TaskView.c"
}

static void
_agenda_task_view_toggle_clicked_gtk_cell_renderer_toggle_toggled (GtkCellRendererToggle* _sender,
                                                                   const gchar* path,
                                                                   gpointer self)
{
#line 93 "../src/Widgets/TaskView.vala"
	agenda_task_view_toggle_clicked ((AgendaTaskView*) self, _sender, path);
#line 621 "TaskView.c"
}

static void
_agenda_task_view_list_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender,
                                                                  GtkTreePath* path,
                                                                  GtkTreeViewColumn* column,
                                                                  gpointer self)
{
#line 94 "../src/Widgets/TaskView.vala"
	agenda_task_view_list_row_activated ((AgendaTaskView*) self, path, column);
#line 632 "TaskView.c"
}

static gboolean
_agenda_task_view___lambda6_ (AgendaTaskView* self,
                              GdkEventButton* event)
{
	GtkTreePath* p = NULL;
	GtkTreePath* _tmp0_;
	GtkTreePath* _tmp1_ = NULL;
	GtkTreePath* _tmp2_;
	GtkTreePath* _tmp5_;
	gboolean result = FALSE;
#line 95 "../src/Widgets/TaskView.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 96 "../src/Widgets/TaskView.vala"
	_tmp0_ = gtk_tree_path_new ();
#line 96 "../src/Widgets/TaskView.vala"
	p = _tmp0_;
#line 97 "../src/Widgets/TaskView.vala"
	gtk_tree_view_get_path_at_pos ((GtkTreeView*) self, (gint) event->x, (gint) event->y, &_tmp1_, NULL, NULL, NULL);
#line 97 "../src/Widgets/TaskView.vala"
	__vala_GtkTreePath_free0 (p);
#line 97 "../src/Widgets/TaskView.vala"
	p = _tmp1_;
#line 98 "../src/Widgets/TaskView.vala"
	_tmp2_ = p;
#line 98 "../src/Widgets/TaskView.vala"
	if (_tmp2_ == NULL) {
#line 661 "TaskView.c"
		GtkTreeSelection* _tmp3_;
		GtkTreePath* _tmp4_;
#line 99 "../src/Widgets/TaskView.vala"
		_tmp3_ = gtk_tree_view_get_selection ((GtkTreeView*) self);
#line 99 "../src/Widgets/TaskView.vala"
		gtk_tree_selection_unselect_all (_tmp3_);
#line 100 "../src/Widgets/TaskView.vala"
		_tmp4_ = p;
#line 100 "../src/Widgets/TaskView.vala"
		p = NULL;
#line 100 "../src/Widgets/TaskView.vala"
		gtk_tree_path_free (_tmp4_);
#line 101 "../src/Widgets/TaskView.vala"
		result = TRUE;
#line 101 "../src/Widgets/TaskView.vala"
		__vala_GtkTreePath_free0 (p);
#line 101 "../src/Widgets/TaskView.vala"
		return result;
#line 680 "TaskView.c"
	}
#line 103 "../src/Widgets/TaskView.vala"
	_tmp5_ = p;
#line 103 "../src/Widgets/TaskView.vala"
	p = NULL;
#line 103 "../src/Widgets/TaskView.vala"
	gtk_tree_path_free (_tmp5_);
#line 104 "../src/Widgets/TaskView.vala"
	result = FALSE;
#line 104 "../src/Widgets/TaskView.vala"
	__vala_GtkTreePath_free0 (p);
#line 104 "../src/Widgets/TaskView.vala"
	return result;
#line 694 "TaskView.c"
}

static gboolean
__agenda_task_view___lambda6__gtk_widget_button_press_event (GtkWidget* _sender,
                                                             GdkEventButton* event,
                                                             gpointer self)
{
	gboolean result;
	result = _agenda_task_view___lambda6_ ((AgendaTaskView*) self, event);
#line 95 "../src/Widgets/TaskView.vala"
	return result;
#line 706 "TaskView.c"
}

static GObject *
agenda_task_view_constructor (GType type,
                              guint n_construct_properties,
                              GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	AgendaTaskView * self;
	GtkTreeViewColumn* column = NULL;
	GtkTreeViewColumn* _tmp0_;
	GtkCellRendererText* text = NULL;
	GtkCellRendererText* _tmp1_;
	GtkCellRendererToggle* toggle = NULL;
	GtkCellRendererToggle* _tmp2_;
	GtkCellRendererPixbuf* delete_button = NULL;
	GtkCellRendererPixbuf* _tmp3_;
	GtkCellRendererPixbuf* draghandle = NULL;
	GtkCellRendererPixbuf* _tmp4_;
	GtkCellRendererToggle* _tmp5_;
	GtkCellRendererToggle* _tmp6_;
	GtkTreeViewColumn* _tmp7_;
	GtkTreeViewColumn* _tmp8_;
	GtkCellRendererText* _tmp9_;
	GtkCellRendererText* _tmp10_;
	GtkCellRendererText* _tmp11_;
	GtkCellRendererText* _tmp12_;
	GtkCellRendererText* _tmp13_;
	GtkCellRendererText* _tmp14_;
	GtkTreeViewColumn* _tmp15_;
	GtkTreeViewColumn* _tmp16_;
	GtkTreeViewColumn* _tmp17_;
	GtkCellRendererPixbuf* _tmp18_;
	GtkCellRendererPixbuf* _tmp19_;
	GtkTreeViewColumn* _tmp20_;
	GtkTreeViewColumn* _tmp21_;
	GtkCellRendererPixbuf* _tmp22_;
	GtkCellRendererPixbuf* _tmp23_;
	GtkTreeViewColumn* _tmp24_;
	GtkTreeViewColumn* _tmp25_;
	GtkCellRendererText* _tmp26_;
	GtkCellRendererText* _tmp27_;
	GtkCellRendererText* _tmp28_;
	GtkCellRendererToggle* _tmp29_;
#line 34 "../src/Widgets/TaskView.vala"
	parent_class = G_OBJECT_CLASS (agenda_task_view_parent_class);
#line 34 "../src/Widgets/TaskView.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 34 "../src/Widgets/TaskView.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK_VIEW, AgendaTaskView);
#line 35 "../src/Widgets/TaskView.vala"
	gtk_widget_set_name ((GtkWidget*) self, "TaskView");
#line 36 "../src/Widgets/TaskView.vala"
	gtk_tree_view_set_activate_on_single_click ((GtkTreeView*) self, TRUE);
#line 37 "../src/Widgets/TaskView.vala"
	gtk_tree_view_set_headers_visible ((GtkTreeView*) self, FALSE);
#line 38 "../src/Widgets/TaskView.vala"
	gtk_tree_view_set_enable_search ((GtkTreeView*) self, FALSE);
#line 39 "../src/Widgets/TaskView.vala"
	gtk_widget_set_hexpand ((GtkWidget*) self, TRUE);
#line 40 "../src/Widgets/TaskView.vala"
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_FILL);
#line 41 "../src/Widgets/TaskView.vala"
	gtk_tree_view_set_reorderable ((GtkTreeView*) self, TRUE);
#line 43 "../src/Widgets/TaskView.vala"
	_tmp0_ = gtk_tree_view_column_new ();
#line 43 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp0_);
#line 43 "../src/Widgets/TaskView.vala"
	column = _tmp0_;
#line 44 "../src/Widgets/TaskView.vala"
	_tmp1_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 44 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp1_);
#line 44 "../src/Widgets/TaskView.vala"
	text = _tmp1_;
#line 45 "../src/Widgets/TaskView.vala"
	_tmp2_ = (GtkCellRendererToggle*) gtk_cell_renderer_toggle_new ();
#line 45 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp2_);
#line 45 "../src/Widgets/TaskView.vala"
	toggle = _tmp2_;
#line 46 "../src/Widgets/TaskView.vala"
	_tmp3_ = (GtkCellRendererPixbuf*) gtk_cell_renderer_pixbuf_new ();
#line 46 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp3_);
#line 46 "../src/Widgets/TaskView.vala"
	delete_button = _tmp3_;
#line 47 "../src/Widgets/TaskView.vala"
	_tmp4_ = (GtkCellRendererPixbuf*) gtk_cell_renderer_pixbuf_new ();
#line 47 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp4_);
#line 47 "../src/Widgets/TaskView.vala"
	draghandle = _tmp4_;
#line 50 "../src/Widgets/TaskView.vala"
	_tmp5_ = toggle;
#line 50 "../src/Widgets/TaskView.vala"
	g_object_set ((GtkCellRenderer*) _tmp5_, "xpad", (guint) 6, NULL);
#line 51 "../src/Widgets/TaskView.vala"
	_tmp6_ = toggle;
#line 51 "../src/Widgets/TaskView.vala"
	_tmp7_ = gtk_tree_view_column_new_with_attributes ("Toggle", (GtkCellRenderer*) _tmp6_, "active", AGENDA_TASK_LIST_COLUMNS_TOGGLE, NULL);
#line 51 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp7_);
#line 51 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (column);
#line 51 "../src/Widgets/TaskView.vala"
	column = _tmp7_;
#line 55 "../src/Widgets/TaskView.vala"
	_tmp8_ = column;
#line 55 "../src/Widgets/TaskView.vala"
	gtk_tree_view_append_column ((GtkTreeView*) self, _tmp8_);
#line 58 "../src/Widgets/TaskView.vala"
	_tmp9_ = text;
#line 58 "../src/Widgets/TaskView.vala"
	g_object_set ((GtkCellRenderer*) _tmp9_, "ypad", (guint) 6, NULL);
#line 59 "../src/Widgets/TaskView.vala"
	_tmp10_ = text;
#line 59 "../src/Widgets/TaskView.vala"
	g_object_set (_tmp10_, "editable", TRUE, NULL);
#line 60 "../src/Widgets/TaskView.vala"
	_tmp11_ = text;
#line 60 "../src/Widgets/TaskView.vala"
	g_object_set (_tmp11_, "max-width-chars", 10, NULL);
#line 61 "../src/Widgets/TaskView.vala"
	_tmp12_ = text;
#line 61 "../src/Widgets/TaskView.vala"
	g_object_set (_tmp12_, "ellipsize-set", TRUE, NULL);
#line 62 "../src/Widgets/TaskView.vala"
	_tmp13_ = text;
#line 62 "../src/Widgets/TaskView.vala"
	g_object_set (_tmp13_, "ellipsize", PANGO_ELLIPSIZE_END, NULL);
#line 64 "../src/Widgets/TaskView.vala"
	_tmp14_ = text;
#line 64 "../src/Widgets/TaskView.vala"
	_tmp15_ = gtk_tree_view_column_new_with_attributes ("Task", (GtkCellRenderer*) _tmp14_, "text", AGENDA_TASK_LIST_COLUMNS_TEXT, "strikethrough", AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH, NULL);
#line 64 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp15_);
#line 64 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (column);
#line 64 "../src/Widgets/TaskView.vala"
	column = _tmp15_;
#line 67 "../src/Widgets/TaskView.vala"
	_tmp16_ = column;
#line 67 "../src/Widgets/TaskView.vala"
	gtk_tree_view_column_set_expand (_tmp16_, TRUE);
#line 68 "../src/Widgets/TaskView.vala"
	_tmp17_ = column;
#line 68 "../src/Widgets/TaskView.vala"
	gtk_tree_view_append_column ((GtkTreeView*) self, _tmp17_);
#line 71 "../src/Widgets/TaskView.vala"
	_tmp18_ = delete_button;
#line 71 "../src/Widgets/TaskView.vala"
	g_object_set ((GtkCellRenderer*) _tmp18_, "xpad", (guint) 6, NULL);
#line 72 "../src/Widgets/TaskView.vala"
	_tmp19_ = delete_button;
#line 72 "../src/Widgets/TaskView.vala"
	_tmp20_ = gtk_tree_view_column_new_with_attributes ("Delete", (GtkCellRenderer*) _tmp19_, "icon_name", AGENDA_TASK_LIST_COLUMNS_DELETE, NULL);
#line 72 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp20_);
#line 72 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (column);
#line 72 "../src/Widgets/TaskView.vala"
	column = _tmp20_;
#line 74 "../src/Widgets/TaskView.vala"
	_tmp21_ = column;
#line 74 "../src/Widgets/TaskView.vala"
	gtk_tree_view_append_column ((GtkTreeView*) self, _tmp21_);
#line 77 "../src/Widgets/TaskView.vala"
	_tmp22_ = draghandle;
#line 77 "../src/Widgets/TaskView.vala"
	g_object_set ((GtkCellRenderer*) _tmp22_, "xpad", (guint) 6, NULL);
#line 78 "../src/Widgets/TaskView.vala"
	_tmp23_ = draghandle;
#line 78 "../src/Widgets/TaskView.vala"
	_tmp24_ = gtk_tree_view_column_new_with_attributes ("Drag", (GtkCellRenderer*) _tmp23_, "icon_name", AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE, NULL);
#line 78 "../src/Widgets/TaskView.vala"
	g_object_ref_sink (_tmp24_);
#line 78 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (column);
#line 78 "../src/Widgets/TaskView.vala"
	column = _tmp24_;
#line 80 "../src/Widgets/TaskView.vala"
	_tmp25_ = column;
#line 80 "../src/Widgets/TaskView.vala"
	gtk_tree_view_append_column ((GtkTreeView*) self, _tmp25_);
#line 82 "../src/Widgets/TaskView.vala"
	gtk_tree_view_set_tooltip_column ((GtkTreeView*) self, (gint) AGENDA_TASK_LIST_COLUMNS_TEXT);
#line 84 "../src/Widgets/TaskView.vala"
	_tmp26_ = text;
#line 84 "../src/Widgets/TaskView.vala"
	g_signal_connect_object ((GtkCellRenderer*) _tmp26_, "editing-started", (GCallback) __agenda_task_view___lambda4__gtk_cell_renderer_editing_started, self, 0);
#line 88 "../src/Widgets/TaskView.vala"
	_tmp27_ = text;
#line 88 "../src/Widgets/TaskView.vala"
	g_signal_connect_object ((GtkCellRenderer*) _tmp27_, "editing-canceled", (GCallback) __agenda_task_view___lambda5__gtk_cell_renderer_editing_canceled, self, 0);
#line 92 "../src/Widgets/TaskView.vala"
	_tmp28_ = text;
#line 92 "../src/Widgets/TaskView.vala"
	g_signal_connect_object (_tmp28_, "edited", (GCallback) _agenda_task_view_text_edited_gtk_cell_renderer_text_edited, self, 0);
#line 93 "../src/Widgets/TaskView.vala"
	_tmp29_ = toggle;
#line 93 "../src/Widgets/TaskView.vala"
	g_signal_connect_object (_tmp29_, "toggled", (GCallback) _agenda_task_view_toggle_clicked_gtk_cell_renderer_toggle_toggled, self, 0);
#line 94 "../src/Widgets/TaskView.vala"
	g_signal_connect_object ((GtkTreeView*) self, "row-activated", (GCallback) _agenda_task_view_list_row_activated_gtk_tree_view_row_activated, self, 0);
#line 95 "../src/Widgets/TaskView.vala"
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) __agenda_task_view___lambda6__gtk_widget_button_press_event, self, 0);
#line 34 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (draghandle);
#line 34 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (delete_button);
#line 34 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (toggle);
#line 34 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (text);
#line 34 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (column);
#line 34 "../src/Widgets/TaskView.vala"
	return obj;
#line 928 "TaskView.c"
}

static void
agenda_task_view_class_init (AgendaTaskViewClass * klass,
                             gpointer klass_data)
{
#line 24 "../src/Widgets/TaskView.vala"
	agenda_task_view_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/Widgets/TaskView.vala"
	g_type_class_adjust_private_offset (klass, &AgendaTaskView_private_offset);
#line 24 "../src/Widgets/TaskView.vala"
	G_OBJECT_CLASS (klass)->constructor = agenda_task_view_constructor;
#line 24 "../src/Widgets/TaskView.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_task_view_finalize;
#line 943 "TaskView.c"
}

static void
agenda_task_view_instance_init (AgendaTaskView * self,
                                gpointer klass)
{
#line 24 "../src/Widgets/TaskView.vala"
	self->priv = agenda_task_view_get_instance_private (self);
#line 952 "TaskView.c"
}

static void
agenda_task_view_finalize (GObject * obj)
{
	AgendaTaskView * self;
#line 24 "../src/Widgets/TaskView.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK_VIEW, AgendaTaskView);
#line 26 "../src/Widgets/TaskView.vala"
	_g_object_unref0 (self->priv->task_list);
#line 24 "../src/Widgets/TaskView.vala"
	G_OBJECT_CLASS (agenda_task_view_parent_class)->finalize (obj);
#line 965 "TaskView.c"
}

static GType
agenda_task_view_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaTaskViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_task_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaTaskView), 0, (GInstanceInitFunc) agenda_task_view_instance_init, NULL };
	GType agenda_task_view_type_id;
	agenda_task_view_type_id = g_type_register_static (gtk_tree_view_get_type (), "AgendaTaskView", &g_define_type_info, 0);
	AgendaTaskView_private_offset = g_type_add_instance_private (agenda_task_view_type_id, sizeof (AgendaTaskViewPrivate));
	return agenda_task_view_type_id;
}

GType
agenda_task_view_get_type (void)
{
	static volatile gsize agenda_task_view_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_task_view_type_id__volatile)) {
		GType agenda_task_view_type_id;
		agenda_task_view_type_id = agenda_task_view_get_type_once ();
		g_once_init_leave (&agenda_task_view_type_id__volatile, agenda_task_view_type_id);
	}
	return agenda_task_view_type_id__volatile;
}

