/* Task.c generated by valac 0.54.3, the Vala compiler
 * generated from Task.vala, do not modify */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_TASK (agenda_task_get_type ())
#define AGENDA_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK, AgendaTask))
#define AGENDA_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK, AgendaTaskClass))
#define AGENDA_IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK))
#define AGENDA_IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK))
#define AGENDA_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK, AgendaTaskClass))

typedef struct _AgendaTask AgendaTask;
typedef struct _AgendaTaskClass AgendaTaskClass;
typedef struct _AgendaTaskPrivate AgendaTaskPrivate;
enum  {
	AGENDA_TASK_0_PROPERTY,
	AGENDA_TASK_ID_PROPERTY,
	AGENDA_TASK_COMPLETE_PROPERTY,
	AGENDA_TASK_TEXT_PROPERTY,
	AGENDA_TASK_NUM_PROPERTIES
};
static GParamSpec* agenda_task_properties[AGENDA_TASK_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AgendaTask {
	GObject parent_instance;
	AgendaTaskPrivate * priv;
};

struct _AgendaTaskClass {
	GObjectClass parent_class;
};

struct _AgendaTaskPrivate {
	gchar* _id;
	gboolean _complete;
	gchar* _text;
};

static gint AgendaTask_private_offset;
static gpointer agenda_task_parent_class = NULL;

VALA_EXTERN GType agenda_task_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTask, g_object_unref)
VALA_EXTERN AgendaTask* agenda_task_new (void);
VALA_EXTERN AgendaTask* agenda_task_construct (GType object_type);
VALA_EXTERN AgendaTask* agenda_task_new_with_attributes (const gchar* id,
                                             gboolean complete,
                                             const gchar* text);
VALA_EXTERN AgendaTask* agenda_task_construct_with_attributes (GType object_type,
                                                   const gchar* id,
                                                   gboolean complete,
                                                   const gchar* text);
VALA_EXTERN gchar* agenda_task_to_string (AgendaTask* self);
VALA_EXTERN gboolean agenda_task_get_complete (AgendaTask* self);
VALA_EXTERN const gchar* agenda_task_get_text (AgendaTask* self);
VALA_EXTERN const gchar* agenda_task_get_id (AgendaTask* self);
VALA_EXTERN void agenda_task_set_id (AgendaTask* self,
                         const gchar* value);
VALA_EXTERN void agenda_task_set_complete (AgendaTask* self,
                               gboolean value);
VALA_EXTERN void agenda_task_set_text (AgendaTask* self,
                           const gchar* value);
static void agenda_task_finalize (GObject * obj);
static GType agenda_task_get_type_once (void);
static void _vala_agenda_task_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec);
static void _vala_agenda_task_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec);

static inline gpointer
agenda_task_get_instance_private (AgendaTask* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaTask_private_offset);
}

AgendaTask*
agenda_task_construct (GType object_type)
{
	AgendaTask * self = NULL;
#line 29 "../src/Models/Task.vala"
	self = (AgendaTask*) g_object_new (object_type, NULL);
#line 29 "../src/Models/Task.vala"
	return self;
#line 104 "Task.c"
}

AgendaTask*
agenda_task_new (void)
{
#line 29 "../src/Models/Task.vala"
	return agenda_task_construct (AGENDA_TYPE_TASK);
#line 112 "Task.c"
}

AgendaTask*
agenda_task_construct_with_attributes (GType object_type,
                                       const gchar* id,
                                       gboolean complete,
                                       const gchar* text)
{
	AgendaTask * self = NULL;
#line 32 "../src/Models/Task.vala"
	g_return_val_if_fail (id != NULL, NULL);
#line 32 "../src/Models/Task.vala"
	g_return_val_if_fail (text != NULL, NULL);
#line 33 "../src/Models/Task.vala"
	self = (AgendaTask*) g_object_new (object_type, "id", id, "complete", complete, "text", text, NULL);
#line 32 "../src/Models/Task.vala"
	return self;
#line 130 "Task.c"
}

AgendaTask*
agenda_task_new_with_attributes (const gchar* id,
                                 gboolean complete,
                                 const gchar* text)
{
#line 32 "../src/Models/Task.vala"
	return agenda_task_construct_with_attributes (AGENDA_TYPE_TASK, id, complete, text);
#line 140 "Task.c"
}

gchar*
agenda_task_to_string (AgendaTask* self)
{
	gchar* str = NULL;
	gboolean _tmp0_;
	gchar* result = NULL;
#line 39 "../src/Models/Task.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 42 "../src/Models/Task.vala"
	_tmp0_ = self->priv->_complete;
#line 42 "../src/Models/Task.vala"
	if (_tmp0_) {
#line 155 "Task.c"
		const gchar* _tmp1_;
		gchar* _tmp2_;
#line 43 "../src/Models/Task.vala"
		_tmp1_ = self->priv->_text;
#line 43 "../src/Models/Task.vala"
		_tmp2_ = g_strconcat ("t,", _tmp1_, NULL);
#line 43 "../src/Models/Task.vala"
		_g_free0 (str);
#line 43 "../src/Models/Task.vala"
		str = _tmp2_;
#line 166 "Task.c"
	} else {
		const gchar* _tmp3_;
		gchar* _tmp4_;
#line 45 "../src/Models/Task.vala"
		_tmp3_ = self->priv->_text;
#line 45 "../src/Models/Task.vala"
		_tmp4_ = g_strconcat ("f,", _tmp3_, NULL);
#line 45 "../src/Models/Task.vala"
		_g_free0 (str);
#line 45 "../src/Models/Task.vala"
		str = _tmp4_;
#line 178 "Task.c"
	}
#line 48 "../src/Models/Task.vala"
	result = str;
#line 48 "../src/Models/Task.vala"
	return result;
#line 184 "Task.c"
}

const gchar*
agenda_task_get_id (AgendaTask* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 25 "../src/Models/Task.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "../src/Models/Task.vala"
	_tmp0_ = self->priv->_id;
#line 25 "../src/Models/Task.vala"
	result = _tmp0_;
#line 25 "../src/Models/Task.vala"
	return result;
#line 200 "Task.c"
}

void
agenda_task_set_id (AgendaTask* self,
                    const gchar* value)
{
	gchar* old_value;
#line 25 "../src/Models/Task.vala"
	g_return_if_fail (self != NULL);
#line 25 "../src/Models/Task.vala"
	old_value = agenda_task_get_id (self);
#line 25 "../src/Models/Task.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 214 "Task.c"
		gchar* _tmp0_;
#line 25 "../src/Models/Task.vala"
		_tmp0_ = g_strdup (value);
#line 25 "../src/Models/Task.vala"
		_g_free0 (self->priv->_id);
#line 25 "../src/Models/Task.vala"
		self->priv->_id = _tmp0_;
#line 25 "../src/Models/Task.vala"
		g_object_notify_by_pspec ((GObject *) self, agenda_task_properties[AGENDA_TASK_ID_PROPERTY]);
#line 224 "Task.c"
	}
}

gboolean
agenda_task_get_complete (AgendaTask* self)
{
	gboolean result;
#line 26 "../src/Models/Task.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 26 "../src/Models/Task.vala"
	result = self->priv->_complete;
#line 26 "../src/Models/Task.vala"
	return result;
#line 238 "Task.c"
}

void
agenda_task_set_complete (AgendaTask* self,
                          gboolean value)
{
	gboolean old_value;
#line 26 "../src/Models/Task.vala"
	g_return_if_fail (self != NULL);
#line 26 "../src/Models/Task.vala"
	old_value = agenda_task_get_complete (self);
#line 26 "../src/Models/Task.vala"
	if (old_value != value) {
#line 26 "../src/Models/Task.vala"
		self->priv->_complete = value;
#line 26 "../src/Models/Task.vala"
		g_object_notify_by_pspec ((GObject *) self, agenda_task_properties[AGENDA_TASK_COMPLETE_PROPERTY]);
#line 256 "Task.c"
	}
}

const gchar*
agenda_task_get_text (AgendaTask* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 27 "../src/Models/Task.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 27 "../src/Models/Task.vala"
	_tmp0_ = self->priv->_text;
#line 27 "../src/Models/Task.vala"
	result = _tmp0_;
#line 27 "../src/Models/Task.vala"
	return result;
#line 273 "Task.c"
}

void
agenda_task_set_text (AgendaTask* self,
                      const gchar* value)
{
	gchar* old_value;
#line 27 "../src/Models/Task.vala"
	g_return_if_fail (self != NULL);
#line 27 "../src/Models/Task.vala"
	old_value = agenda_task_get_text (self);
#line 27 "../src/Models/Task.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 287 "Task.c"
		gchar* _tmp0_;
#line 27 "../src/Models/Task.vala"
		_tmp0_ = g_strdup (value);
#line 27 "../src/Models/Task.vala"
		_g_free0 (self->priv->_text);
#line 27 "../src/Models/Task.vala"
		self->priv->_text = _tmp0_;
#line 27 "../src/Models/Task.vala"
		g_object_notify_by_pspec ((GObject *) self, agenda_task_properties[AGENDA_TASK_TEXT_PROPERTY]);
#line 297 "Task.c"
	}
}

static void
agenda_task_class_init (AgendaTaskClass * klass,
                        gpointer klass_data)
{
#line 24 "../src/Models/Task.vala"
	agenda_task_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/Models/Task.vala"
	g_type_class_adjust_private_offset (klass, &AgendaTask_private_offset);
#line 24 "../src/Models/Task.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_agenda_task_get_property;
#line 24 "../src/Models/Task.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_agenda_task_set_property;
#line 24 "../src/Models/Task.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_task_finalize;
#line 24 "../src/Models/Task.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), AGENDA_TASK_ID_PROPERTY, agenda_task_properties[AGENDA_TASK_ID_PROPERTY] = g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 24 "../src/Models/Task.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), AGENDA_TASK_COMPLETE_PROPERTY, agenda_task_properties[AGENDA_TASK_COMPLETE_PROPERTY] = g_param_spec_boolean ("complete", "complete", "complete", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 24 "../src/Models/Task.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), AGENDA_TASK_TEXT_PROPERTY, agenda_task_properties[AGENDA_TASK_TEXT_PROPERTY] = g_param_spec_string ("text", "text", "text", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 321 "Task.c"
}

static void
agenda_task_instance_init (AgendaTask * self,
                           gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
#line 24 "../src/Models/Task.vala"
	self->priv = agenda_task_get_instance_private (self);
#line 25 "../src/Models/Task.vala"
	_tmp0_ = g_strdup ("");
#line 25 "../src/Models/Task.vala"
	self->priv->_id = _tmp0_;
#line 26 "../src/Models/Task.vala"
	self->priv->_complete = FALSE;
#line 27 "../src/Models/Task.vala"
	_tmp1_ = g_strdup ("");
#line 27 "../src/Models/Task.vala"
	self->priv->_text = _tmp1_;
#line 342 "Task.c"
}

static void
agenda_task_finalize (GObject * obj)
{
	AgendaTask * self;
#line 24 "../src/Models/Task.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK, AgendaTask);
#line 25 "../src/Models/Task.vala"
	_g_free0 (self->priv->_id);
#line 27 "../src/Models/Task.vala"
	_g_free0 (self->priv->_text);
#line 24 "../src/Models/Task.vala"
	G_OBJECT_CLASS (agenda_task_parent_class)->finalize (obj);
#line 357 "Task.c"
}

static GType
agenda_task_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaTaskClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_task_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaTask), 0, (GInstanceInitFunc) agenda_task_instance_init, NULL };
	GType agenda_task_type_id;
	agenda_task_type_id = g_type_register_static (G_TYPE_OBJECT, "AgendaTask", &g_define_type_info, 0);
	AgendaTask_private_offset = g_type_add_instance_private (agenda_task_type_id, sizeof (AgendaTaskPrivate));
	return agenda_task_type_id;
}

GType
agenda_task_get_type (void)
{
	static volatile gsize agenda_task_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_task_type_id__volatile)) {
		GType agenda_task_type_id;
		agenda_task_type_id = agenda_task_get_type_once ();
		g_once_init_leave (&agenda_task_type_id__volatile, agenda_task_type_id);
	}
	return agenda_task_type_id__volatile;
}

static void
_vala_agenda_task_get_property (GObject * object,
                                guint property_id,
                                GValue * value,
                                GParamSpec * pspec)
{
	AgendaTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AGENDA_TYPE_TASK, AgendaTask);
#line 24 "../src/Models/Task.vala"
	switch (property_id) {
#line 24 "../src/Models/Task.vala"
		case AGENDA_TASK_ID_PROPERTY:
#line 24 "../src/Models/Task.vala"
		g_value_set_string (value, agenda_task_get_id (self));
#line 24 "../src/Models/Task.vala"
		break;
#line 24 "../src/Models/Task.vala"
		case AGENDA_TASK_COMPLETE_PROPERTY:
#line 24 "../src/Models/Task.vala"
		g_value_set_boolean (value, agenda_task_get_complete (self));
#line 24 "../src/Models/Task.vala"
		break;
#line 24 "../src/Models/Task.vala"
		case AGENDA_TASK_TEXT_PROPERTY:
#line 24 "../src/Models/Task.vala"
		g_value_set_string (value, agenda_task_get_text (self));
#line 24 "../src/Models/Task.vala"
		break;
#line 410 "Task.c"
		default:
#line 24 "../src/Models/Task.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Models/Task.vala"
		break;
#line 416 "Task.c"
	}
}

static void
_vala_agenda_task_set_property (GObject * object,
                                guint property_id,
                                const GValue * value,
                                GParamSpec * pspec)
{
	AgendaTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AGENDA_TYPE_TASK, AgendaTask);
#line 24 "../src/Models/Task.vala"
	switch (property_id) {
#line 24 "../src/Models/Task.vala"
		case AGENDA_TASK_ID_PROPERTY:
#line 24 "../src/Models/Task.vala"
		agenda_task_set_id (self, g_value_get_string (value));
#line 24 "../src/Models/Task.vala"
		break;
#line 24 "../src/Models/Task.vala"
		case AGENDA_TASK_COMPLETE_PROPERTY:
#line 24 "../src/Models/Task.vala"
		agenda_task_set_complete (self, g_value_get_boolean (value));
#line 24 "../src/Models/Task.vala"
		break;
#line 24 "../src/Models/Task.vala"
		case AGENDA_TASK_TEXT_PROPERTY:
#line 24 "../src/Models/Task.vala"
		agenda_task_set_text (self, g_value_get_string (value));
#line 24 "../src/Models/Task.vala"
		break;
#line 448 "Task.c"
		default:
#line 24 "../src/Models/Task.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Models/Task.vala"
		break;
#line 454 "Task.c"
	}
}

