/* TaskListHistory.c generated by valac 0.54.3, the Vala compiler
 * generated from TaskListHistory.vala, do not modify */

#include <glib-object.h>
#include <gee.h>
#include <gtk/gtk.h>
#include <glib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_TASK_LIST_HISTORY (agenda_task_list_history_get_type ())
#define AGENDA_TASK_LIST_HISTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistory))
#define AGENDA_TASK_LIST_HISTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistoryClass))
#define AGENDA_IS_TASK_LIST_HISTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_LIST_HISTORY))
#define AGENDA_IS_TASK_LIST_HISTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_LIST_HISTORY))
#define AGENDA_TASK_LIST_HISTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistoryClass))

typedef struct _AgendaTaskListHistory AgendaTaskListHistory;
typedef struct _AgendaTaskListHistoryClass AgendaTaskListHistoryClass;
typedef struct _AgendaTaskListHistoryPrivate AgendaTaskListHistoryPrivate;

#define AGENDA_TYPE_TASK_LIST (agenda_task_list_get_type ())
#define AGENDA_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskList))
#define AGENDA_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))
#define AGENDA_IS_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_LIST))
#define AGENDA_IS_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_LIST))
#define AGENDA_TASK_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))

typedef struct _AgendaTaskList AgendaTaskList;
typedef struct _AgendaTaskListClass AgendaTaskListClass;
enum  {
	AGENDA_TASK_LIST_HISTORY_0_PROPERTY,
	AGENDA_TASK_LIST_HISTORY_SIZE_PROPERTY,
	AGENDA_TASK_LIST_HISTORY_INDEX_PROPERTY,
	AGENDA_TASK_LIST_HISTORY_NUM_PROPERTIES
};
static GParamSpec* agenda_task_list_history_properties[AGENDA_TASK_LIST_HISTORY_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AgendaTaskListHistory {
	GObject parent_instance;
	AgendaTaskListHistoryPrivate * priv;
};

struct _AgendaTaskListHistoryClass {
	GObjectClass parent_class;
};

struct _AgendaTaskListHistoryPrivate {
	GeeLinkedList* list;
	GeeBidirListIterator* iter;
};

static gint AgendaTaskListHistory_private_offset;
static gpointer agenda_task_list_history_parent_class = NULL;

VALA_EXTERN GType agenda_task_list_history_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskListHistory, g_object_unref)
VALA_EXTERN GType agenda_task_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskList, g_object_unref)
VALA_EXTERN void agenda_task_list_history_add (AgendaTaskListHistory* self,
                                   AgendaTaskList* state);
VALA_EXTERN AgendaTaskList* agenda_task_list_copy (AgendaTaskList* self);
VALA_EXTERN AgendaTaskList* agenda_task_list_history_get_next_state (AgendaTaskListHistory* self);
VALA_EXTERN AgendaTaskList* agenda_task_list_history_get_previous_state (AgendaTaskListHistory* self);
VALA_EXTERN AgendaTaskListHistory* agenda_task_list_history_new (void);
VALA_EXTERN AgendaTaskListHistory* agenda_task_list_history_construct (GType object_type);
VALA_EXTERN gint agenda_task_list_history_get_size (AgendaTaskListHistory* self);
VALA_EXTERN gint agenda_task_list_history_get_index (AgendaTaskListHistory* self);
static GObject * agenda_task_list_history_constructor (GType type,
                                                guint n_construct_properties,
                                                GObjectConstructParam * construct_properties);
static void agenda_task_list_history_finalize (GObject * obj);
static GType agenda_task_list_history_get_type_once (void);
static void _vala_agenda_task_list_history_get_property (GObject * object,
                                                  guint property_id,
                                                  GValue * value,
                                                  GParamSpec * pspec);

static inline gpointer
agenda_task_list_history_get_instance_private (AgendaTaskListHistory* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaTaskListHistory_private_offset);
}

void
agenda_task_list_history_add (AgendaTaskListHistory* self,
                              AgendaTaskList* state)
{
	GeeBidirListIterator* _tmp0_;
	AgendaTaskList* current_state = NULL;
	AgendaTaskList* _tmp6_;
	GeeLinkedList* _tmp7_;
	GeeLinkedList* _tmp8_;
	GeeBidirListIterator* _tmp9_;
	GeeBidirListIterator* _tmp10_;
#line 42 "../src/Models/TaskListHistory.vala"
	g_return_if_fail (self != NULL);
#line 42 "../src/Models/TaskListHistory.vala"
	g_return_if_fail (state != NULL);
#line 43 "../src/Models/TaskListHistory.vala"
	_tmp0_ = self->priv->iter;
#line 43 "../src/Models/TaskListHistory.vala"
	if (gee_iterator_has_next ((GeeIterator*) _tmp0_)) {
#line 114 "TaskListHistory.c"
		GeeList* temp_list = NULL;
		GeeLinkedList* _tmp1_;
		GeeBidirListIterator* _tmp2_;
		GeeList* _tmp3_;
		GeeLinkedList* _tmp4_;
		GeeList* _tmp5_;
#line 44 "../src/Models/TaskListHistory.vala"
		_tmp1_ = self->priv->list;
#line 44 "../src/Models/TaskListHistory.vala"
		_tmp2_ = self->priv->iter;
#line 44 "../src/Models/TaskListHistory.vala"
		_tmp3_ = gee_abstract_list_slice ((GeeAbstractList*) _tmp1_, 0, gee_list_iterator_index ((GeeListIterator*) _tmp2_) + 1);
#line 44 "../src/Models/TaskListHistory.vala"
		temp_list = _tmp3_;
#line 45 "../src/Models/TaskListHistory.vala"
		_tmp4_ = self->priv->list;
#line 45 "../src/Models/TaskListHistory.vala"
		_tmp5_ = temp_list;
#line 45 "../src/Models/TaskListHistory.vala"
		gee_collection_retain_all ((GeeCollection*) _tmp4_, (GeeCollection*) _tmp5_);
#line 43 "../src/Models/TaskListHistory.vala"
		_g_object_unref0 (temp_list);
#line 137 "TaskListHistory.c"
	}
#line 48 "../src/Models/TaskListHistory.vala"
	_tmp6_ = agenda_task_list_copy (state);
#line 48 "../src/Models/TaskListHistory.vala"
	current_state = _tmp6_;
#line 50 "../src/Models/TaskListHistory.vala"
	_tmp7_ = self->priv->list;
#line 50 "../src/Models/TaskListHistory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp7_, current_state);
#line 51 "../src/Models/TaskListHistory.vala"
	_tmp8_ = self->priv->list;
#line 51 "../src/Models/TaskListHistory.vala"
	_tmp9_ = gee_abstract_bidir_list_bidir_list_iterator ((GeeAbstractBidirList*) _tmp8_);
#line 51 "../src/Models/TaskListHistory.vala"
	_g_object_unref0 (self->priv->iter);
#line 51 "../src/Models/TaskListHistory.vala"
	self->priv->iter = _tmp9_;
#line 52 "../src/Models/TaskListHistory.vala"
	_tmp10_ = self->priv->iter;
#line 52 "../src/Models/TaskListHistory.vala"
	gee_bidir_iterator_last ((GeeBidirIterator*) _tmp10_);
#line 42 "../src/Models/TaskListHistory.vala"
	_g_object_unref0 (current_state);
#line 161 "TaskListHistory.c"
}

AgendaTaskList*
agenda_task_list_history_get_next_state (AgendaTaskListHistory* self)
{
	GeeBidirListIterator* _tmp0_;
	AgendaTaskList* result = NULL;
#line 55 "../src/Models/TaskListHistory.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 56 "../src/Models/TaskListHistory.vala"
	_tmp0_ = self->priv->iter;
#line 56 "../src/Models/TaskListHistory.vala"
	if (gee_iterator_next ((GeeIterator*) _tmp0_)) {
#line 175 "TaskListHistory.c"
		GeeBidirListIterator* _tmp1_;
		gpointer _tmp2_;
#line 57 "../src/Models/TaskListHistory.vala"
		_tmp1_ = self->priv->iter;
#line 57 "../src/Models/TaskListHistory.vala"
		_tmp2_ = gee_iterator_get ((GeeIterator*) _tmp1_);
#line 57 "../src/Models/TaskListHistory.vala"
		result = (AgendaTaskList*) _tmp2_;
#line 57 "../src/Models/TaskListHistory.vala"
		return result;
#line 186 "TaskListHistory.c"
	} else {
#line 59 "../src/Models/TaskListHistory.vala"
		result = NULL;
#line 59 "../src/Models/TaskListHistory.vala"
		return result;
#line 192 "TaskListHistory.c"
	}
}

AgendaTaskList*
agenda_task_list_history_get_previous_state (AgendaTaskListHistory* self)
{
	GeeBidirListIterator* _tmp0_;
	AgendaTaskList* result = NULL;
#line 63 "../src/Models/TaskListHistory.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 64 "../src/Models/TaskListHistory.vala"
	_tmp0_ = self->priv->iter;
#line 64 "../src/Models/TaskListHistory.vala"
	if (gee_bidir_iterator_previous ((GeeBidirIterator*) _tmp0_)) {
#line 207 "TaskListHistory.c"
		AgendaTaskList* state = NULL;
		GeeBidirListIterator* _tmp1_;
		gpointer _tmp2_;
#line 65 "../src/Models/TaskListHistory.vala"
		_tmp1_ = self->priv->iter;
#line 65 "../src/Models/TaskListHistory.vala"
		_tmp2_ = gee_iterator_get ((GeeIterator*) _tmp1_);
#line 65 "../src/Models/TaskListHistory.vala"
		state = (AgendaTaskList*) _tmp2_;
#line 66 "../src/Models/TaskListHistory.vala"
		result = state;
#line 66 "../src/Models/TaskListHistory.vala"
		return result;
#line 221 "TaskListHistory.c"
	} else {
#line 68 "../src/Models/TaskListHistory.vala"
		result = NULL;
#line 68 "../src/Models/TaskListHistory.vala"
		return result;
#line 227 "TaskListHistory.c"
	}
}

AgendaTaskListHistory*
agenda_task_list_history_construct (GType object_type)
{
	AgendaTaskListHistory * self = NULL;
#line 24 "../src/Models/TaskListHistory.vala"
	self = (AgendaTaskListHistory*) g_object_new (object_type, NULL);
#line 24 "../src/Models/TaskListHistory.vala"
	return self;
#line 239 "TaskListHistory.c"
}

AgendaTaskListHistory*
agenda_task_list_history_new (void)
{
#line 24 "../src/Models/TaskListHistory.vala"
	return agenda_task_list_history_construct (AGENDA_TYPE_TASK_LIST_HISTORY);
#line 247 "TaskListHistory.c"
}

gint
agenda_task_list_history_get_size (AgendaTaskListHistory* self)
{
	gint result;
	GeeLinkedList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
#line 35 "../src/Models/TaskListHistory.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 35 "../src/Models/TaskListHistory.vala"
	_tmp0_ = self->priv->list;
#line 35 "../src/Models/TaskListHistory.vala"
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
#line 35 "../src/Models/TaskListHistory.vala"
	_tmp2_ = _tmp1_;
#line 35 "../src/Models/TaskListHistory.vala"
	result = _tmp2_;
#line 35 "../src/Models/TaskListHistory.vala"
	return result;
#line 269 "TaskListHistory.c"
}

gint
agenda_task_list_history_get_index (AgendaTaskListHistory* self)
{
	gint result;
	GeeBidirListIterator* _tmp0_;
#line 39 "../src/Models/TaskListHistory.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 39 "../src/Models/TaskListHistory.vala"
	_tmp0_ = self->priv->iter;
#line 39 "../src/Models/TaskListHistory.vala"
	result = gee_list_iterator_index ((GeeListIterator*) _tmp0_);
#line 39 "../src/Models/TaskListHistory.vala"
	return result;
#line 285 "TaskListHistory.c"
}

static GObject *
agenda_task_list_history_constructor (GType type,
                                      guint n_construct_properties,
                                      GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	AgendaTaskListHistory * self;
	GeeLinkedList* _tmp0_;
	GeeLinkedList* _tmp1_;
	GeeBidirListIterator* _tmp2_;
#line 29 "../src/Models/TaskListHistory.vala"
	parent_class = G_OBJECT_CLASS (agenda_task_list_history_parent_class);
#line 29 "../src/Models/TaskListHistory.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 29 "../src/Models/TaskListHistory.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistory);
#line 30 "../src/Models/TaskListHistory.vala"
	_tmp0_ = gee_linked_list_new (AGENDA_TYPE_TASK_LIST, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 30 "../src/Models/TaskListHistory.vala"
	_g_object_unref0 (self->priv->list);
#line 30 "../src/Models/TaskListHistory.vala"
	self->priv->list = _tmp0_;
#line 31 "../src/Models/TaskListHistory.vala"
	_tmp1_ = self->priv->list;
#line 31 "../src/Models/TaskListHistory.vala"
	_tmp2_ = gee_abstract_bidir_list_bidir_list_iterator ((GeeAbstractBidirList*) _tmp1_);
#line 31 "../src/Models/TaskListHistory.vala"
	_g_object_unref0 (self->priv->iter);
#line 31 "../src/Models/TaskListHistory.vala"
	self->priv->iter = _tmp2_;
#line 29 "../src/Models/TaskListHistory.vala"
	return obj;
#line 321 "TaskListHistory.c"
}

static void
agenda_task_list_history_class_init (AgendaTaskListHistoryClass * klass,
                                     gpointer klass_data)
{
#line 24 "../src/Models/TaskListHistory.vala"
	agenda_task_list_history_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/Models/TaskListHistory.vala"
	g_type_class_adjust_private_offset (klass, &AgendaTaskListHistory_private_offset);
#line 24 "../src/Models/TaskListHistory.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_agenda_task_list_history_get_property;
#line 24 "../src/Models/TaskListHistory.vala"
	G_OBJECT_CLASS (klass)->constructor = agenda_task_list_history_constructor;
#line 24 "../src/Models/TaskListHistory.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_task_list_history_finalize;
#line 24 "../src/Models/TaskListHistory.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), AGENDA_TASK_LIST_HISTORY_SIZE_PROPERTY, agenda_task_list_history_properties[AGENDA_TASK_LIST_HISTORY_SIZE_PROPERTY] = g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 24 "../src/Models/TaskListHistory.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), AGENDA_TASK_LIST_HISTORY_INDEX_PROPERTY, agenda_task_list_history_properties[AGENDA_TASK_LIST_HISTORY_INDEX_PROPERTY] = g_param_spec_int ("index", "index", "index", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 342 "TaskListHistory.c"
}

static void
agenda_task_list_history_instance_init (AgendaTaskListHistory * self,
                                        gpointer klass)
{
#line 24 "../src/Models/TaskListHistory.vala"
	self->priv = agenda_task_list_history_get_instance_private (self);
#line 351 "TaskListHistory.c"
}

static void
agenda_task_list_history_finalize (GObject * obj)
{
	AgendaTaskListHistory * self;
#line 24 "../src/Models/TaskListHistory.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistory);
#line 26 "../src/Models/TaskListHistory.vala"
	_g_object_unref0 (self->priv->list);
#line 27 "../src/Models/TaskListHistory.vala"
	_g_object_unref0 (self->priv->iter);
#line 24 "../src/Models/TaskListHistory.vala"
	G_OBJECT_CLASS (agenda_task_list_history_parent_class)->finalize (obj);
#line 366 "TaskListHistory.c"
}

static GType
agenda_task_list_history_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaTaskListHistoryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_task_list_history_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaTaskListHistory), 0, (GInstanceInitFunc) agenda_task_list_history_instance_init, NULL };
	GType agenda_task_list_history_type_id;
	agenda_task_list_history_type_id = g_type_register_static (G_TYPE_OBJECT, "AgendaTaskListHistory", &g_define_type_info, 0);
	AgendaTaskListHistory_private_offset = g_type_add_instance_private (agenda_task_list_history_type_id, sizeof (AgendaTaskListHistoryPrivate));
	return agenda_task_list_history_type_id;
}

GType
agenda_task_list_history_get_type (void)
{
	static volatile gsize agenda_task_list_history_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_task_list_history_type_id__volatile)) {
		GType agenda_task_list_history_type_id;
		agenda_task_list_history_type_id = agenda_task_list_history_get_type_once ();
		g_once_init_leave (&agenda_task_list_history_type_id__volatile, agenda_task_list_history_type_id);
	}
	return agenda_task_list_history_type_id__volatile;
}

static void
_vala_agenda_task_list_history_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec)
{
	AgendaTaskListHistory * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistory);
#line 24 "../src/Models/TaskListHistory.vala"
	switch (property_id) {
#line 24 "../src/Models/TaskListHistory.vala"
		case AGENDA_TASK_LIST_HISTORY_SIZE_PROPERTY:
#line 24 "../src/Models/TaskListHistory.vala"
		g_value_set_int (value, agenda_task_list_history_get_size (self));
#line 24 "../src/Models/TaskListHistory.vala"
		break;
#line 24 "../src/Models/TaskListHistory.vala"
		case AGENDA_TASK_LIST_HISTORY_INDEX_PROPERTY:
#line 24 "../src/Models/TaskListHistory.vala"
		g_value_set_int (value, agenda_task_list_history_get_index (self));
#line 24 "../src/Models/TaskListHistory.vala"
		break;
#line 413 "TaskListHistory.c"
		default:
#line 24 "../src/Models/TaskListHistory.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Models/TaskListHistory.vala"
		break;
#line 419 "TaskListHistory.c"
	}
}

