/* TaskList.c generated by valac 0.54.3, the Vala compiler
 * generated from TaskList.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_TASK_LIST (agenda_task_list_get_type ())
#define AGENDA_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskList))
#define AGENDA_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))
#define AGENDA_IS_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_LIST))
#define AGENDA_IS_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_LIST))
#define AGENDA_TASK_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))

typedef struct _AgendaTaskList AgendaTaskList;
typedef struct _AgendaTaskListClass AgendaTaskListClass;
typedef struct _AgendaTaskListPrivate AgendaTaskListPrivate;

#define AGENDA_TYPE_TASK_LIST_HISTORY (agenda_task_list_history_get_type ())
#define AGENDA_TASK_LIST_HISTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistory))
#define AGENDA_TASK_LIST_HISTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistoryClass))
#define AGENDA_IS_TASK_LIST_HISTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_LIST_HISTORY))
#define AGENDA_IS_TASK_LIST_HISTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_LIST_HISTORY))
#define AGENDA_TASK_LIST_HISTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_LIST_HISTORY, AgendaTaskListHistoryClass))

typedef struct _AgendaTaskListHistory AgendaTaskListHistory;
typedef struct _AgendaTaskListHistoryClass AgendaTaskListHistoryClass;
enum  {
	AGENDA_TASK_LIST_0_PROPERTY,
	AGENDA_TASK_LIST_SIZE_PROPERTY,
	AGENDA_TASK_LIST_NUM_PROPERTIES
};
static GParamSpec* agenda_task_list_properties[AGENDA_TASK_LIST_NUM_PROPERTIES];
typedef enum  {
	AGENDA_TASK_LIST_COLUMNS_TOGGLE,
	AGENDA_TASK_LIST_COLUMNS_TEXT,
	AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH,
	AGENDA_TASK_LIST_COLUMNS_DELETE,
	AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE,
	AGENDA_TASK_LIST_COLUMNS_ID,
	AGENDA_TASK_LIST_COLUMNS_N_COLUMNS
} AgendaTaskListColumns;

#define AGENDA_TASK_LIST_TYPE_COLUMNS (agenda_task_list_columns_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define AGENDA_TYPE_TASK (agenda_task_get_type ())
#define AGENDA_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK, AgendaTask))
#define AGENDA_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK, AgendaTaskClass))
#define AGENDA_IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK))
#define AGENDA_IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK))
#define AGENDA_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK, AgendaTaskClass))

typedef struct _AgendaTask AgendaTask;
typedef struct _AgendaTaskClass AgendaTaskClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_GtkTreePath_free0(var) ((var == NULL) ? NULL : (var = (_vala_GtkTreePath_free (var), NULL)))
enum  {
	AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL,
	AGENDA_TASK_LIST_NUM_SIGNALS
};
static guint agenda_task_list_signals[AGENDA_TASK_LIST_NUM_SIGNALS] = {0};

struct _AgendaTaskList {
	GtkListStore parent_instance;
	AgendaTaskListPrivate * priv;
};

struct _AgendaTaskListClass {
	GtkListStoreClass parent_class;
};

struct _AgendaTaskListPrivate {
	AgendaTaskListHistory* undo_list;
	gboolean _record_undo_enable;
};

static gint AgendaTaskList_private_offset;
static gpointer agenda_task_list_parent_class = NULL;

VALA_EXTERN GType agenda_task_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskList, g_object_unref)
VALA_EXTERN GType agenda_task_list_history_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskListHistory, g_object_unref)
VALA_EXTERN GType agenda_task_list_columns_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType agenda_task_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTask, g_object_unref)
VALA_EXTERN void agenda_task_list_append_task (AgendaTaskList* self,
                                   AgendaTask* task);
VALA_EXTERN const gchar* agenda_task_get_id (AgendaTask* self);
VALA_EXTERN void agenda_task_set_id (AgendaTask* self,
                         const gchar* value);
VALA_EXTERN gboolean agenda_task_get_complete (AgendaTask* self);
VALA_EXTERN const gchar* agenda_task_get_text (AgendaTask* self);
VALA_EXTERN void agenda_task_list_clear_undo (AgendaTaskList* self);
VALA_EXTERN AgendaTaskListHistory* agenda_task_list_history_new (void);
VALA_EXTERN AgendaTaskListHistory* agenda_task_list_history_construct (GType object_type);
VALA_EXTERN void agenda_task_list_history_add (AgendaTaskListHistory* self,
                                   AgendaTaskList* state);
VALA_EXTERN gboolean agenda_task_list_contains (AgendaTaskList* self,
                                    const gchar* id);
VALA_EXTERN AgendaTaskList* agenda_task_list_copy (AgendaTaskList* self);
VALA_EXTERN AgendaTaskList* agenda_task_list_new (void);
VALA_EXTERN AgendaTaskList* agenda_task_list_construct (GType object_type);
VALA_EXTERN AgendaTask** agenda_task_list_get_all_tasks (AgendaTaskList* self,
                                             gint* result_length1);
VALA_EXTERN void agenda_task_list_load_tasks (AgendaTaskList* self,
                                  AgendaTask** tasks,
                                  gint tasks_length1);
VALA_EXTERN void agenda_task_list_disable_undo_recording (AgendaTaskList* self);
static void agenda_task_list_set_record_undo_enable (AgendaTaskList* self,
                                              gboolean value);
VALA_EXTERN void agenda_task_list_enable_undo_recording (AgendaTaskList* self);
VALA_EXTERN AgendaTask* agenda_task_list_get_task (AgendaTaskList* self,
                                       GtkTreeIter* iter);
static void _vala_array_add5 (AgendaTask** * array,
                       gint* length,
                       gint* size,
                       AgendaTask* value);
VALA_EXTERN AgendaTask* agenda_task_new_with_attributes (const gchar* id,
                                             gboolean complete,
                                             const gchar* text);
VALA_EXTERN AgendaTask* agenda_task_construct_with_attributes (GType object_type,
                                                   const gchar* id,
                                                   gboolean complete,
                                                   const gchar* text);
VALA_EXTERN gboolean agenda_task_list_has_duplicates_of (AgendaTaskList* self,
                                             const gchar* id);
VALA_EXTERN gboolean agenda_task_list_is_empty (AgendaTaskList* self);
static void agenda_task_list_on_row_changed (AgendaTaskList* self,
                                      GtkTreePath* path,
                                      GtkTreeIter* iter);
static gboolean agenda_task_list_get_record_undo_enable (AgendaTaskList* self);
static void agenda_task_list_on_row_deleted (AgendaTaskList* self,
                                      GtkTreePath* path);
VALA_EXTERN gboolean agenda_task_list_remove_task (AgendaTaskList* self,
                                       GtkTreePath* path);
VALA_EXTERN void agenda_task_list_remove_completed_tasks (AgendaTaskList* self);
VALA_EXTERN void agenda_task_list_redo (AgendaTaskList* self);
VALA_EXTERN AgendaTaskList* agenda_task_list_history_get_next_state (AgendaTaskListHistory* self);
static void agenda_task_list_restore_state (AgendaTaskList* self,
                                     AgendaTaskList* state);
VALA_EXTERN void agenda_task_list_undo (AgendaTaskList* self);
VALA_EXTERN AgendaTaskList* agenda_task_list_history_get_previous_state (AgendaTaskListHistory* self);
VALA_EXTERN void agenda_task_list_set_task_text (AgendaTaskList* self,
                                     const gchar* path,
                                     const gchar* text);
static void _vala_GtkTreePath_free (GtkTreePath* self);
VALA_EXTERN void agenda_task_list_toggle_task (AgendaTaskList* self,
                                   GtkTreePath* path);
VALA_EXTERN gint agenda_task_list_get_size (AgendaTaskList* self);
static GObject * agenda_task_list_constructor (GType type,
                                        guint n_construct_properties,
                                        GObjectConstructParam * construct_properties);
static void _agenda_task_list_on_row_changed_gtk_tree_model_row_changed (GtkTreeModel* _sender,
                                                                  GtkTreePath* path,
                                                                  GtkTreeIter* iter,
                                                                  gpointer self);
static void _agenda_task_list_on_row_deleted_gtk_tree_model_row_deleted (GtkTreeModel* _sender,
                                                                  GtkTreePath* path,
                                                                  gpointer self);
static void agenda_task_list_finalize (GObject * obj);
static GType agenda_task_list_get_type_once (void);
static void _vala_agenda_task_list_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec);
static void _vala_agenda_task_list_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
agenda_task_list_get_instance_private (AgendaTaskList* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaTaskList_private_offset);
}

static GType
agenda_task_list_columns_get_type_once (void)
{
	static const GEnumValue values[] = {{AGENDA_TASK_LIST_COLUMNS_TOGGLE, "AGENDA_TASK_LIST_COLUMNS_TOGGLE", "toggle"}, {AGENDA_TASK_LIST_COLUMNS_TEXT, "AGENDA_TASK_LIST_COLUMNS_TEXT", "text"}, {AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH, "AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH", "strikethrough"}, {AGENDA_TASK_LIST_COLUMNS_DELETE, "AGENDA_TASK_LIST_COLUMNS_DELETE", "delete"}, {AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE, "AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE", "draghandle"}, {AGENDA_TASK_LIST_COLUMNS_ID, "AGENDA_TASK_LIST_COLUMNS_ID", "id"}, {AGENDA_TASK_LIST_COLUMNS_N_COLUMNS, "AGENDA_TASK_LIST_COLUMNS_N_COLUMNS", "n-columns"}, {0, NULL, NULL}};
	GType agenda_task_list_columns_type_id;
	agenda_task_list_columns_type_id = g_enum_register_static ("AgendaTaskListColumns", values);
	return agenda_task_list_columns_type_id;
}

GType
agenda_task_list_columns_get_type (void)
{
	static volatile gsize agenda_task_list_columns_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_task_list_columns_type_id__volatile)) {
		GType agenda_task_list_columns_type_id;
		agenda_task_list_columns_type_id = agenda_task_list_columns_get_type_once ();
		g_once_init_leave (&agenda_task_list_columns_type_id__volatile, agenda_task_list_columns_type_id);
	}
	return agenda_task_list_columns_type_id__volatile;
}

/**
         * Add a task to the end of the task list
         *
         * @param task The task being appended to the list
         */
void
agenda_task_list_append_task (AgendaTaskList* self,
                              AgendaTask* task)
{
	GtkTreeIter iter = {0};
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GtkTreeIter _tmp4_ = {0};
	GtkTreeIter _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gboolean _tmp10_;
	gboolean _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp13_;
#line 73 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 73 "../src/Models/TaskList.vala"
	g_return_if_fail (task != NULL);
#line 76 "../src/Models/TaskList.vala"
	_tmp0_ = agenda_task_get_id (task);
#line 76 "../src/Models/TaskList.vala"
	_tmp1_ = _tmp0_;
#line 76 "../src/Models/TaskList.vala"
	if (g_strcmp0 (_tmp1_, "") == 0) {
#line 251 "TaskList.c"
		gchar* _tmp2_;
		gchar* _tmp3_;
#line 77 "../src/Models/TaskList.vala"
		_tmp2_ = g_uuid_string_random ();
#line 77 "../src/Models/TaskList.vala"
		_tmp3_ = _tmp2_;
#line 77 "../src/Models/TaskList.vala"
		agenda_task_set_id (task, _tmp3_);
#line 77 "../src/Models/TaskList.vala"
		_g_free0 (_tmp3_);
#line 262 "TaskList.c"
	}
#line 80 "../src/Models/TaskList.vala"
	gtk_list_store_append ((GtkListStore*) self, &_tmp4_);
#line 80 "../src/Models/TaskList.vala"
	iter = _tmp4_;
#line 81 "../src/Models/TaskList.vala"
	_tmp5_ = iter;
#line 81 "../src/Models/TaskList.vala"
	_tmp6_ = agenda_task_get_complete (task);
#line 81 "../src/Models/TaskList.vala"
	_tmp7_ = _tmp6_;
#line 81 "../src/Models/TaskList.vala"
	_tmp8_ = agenda_task_get_text (task);
#line 81 "../src/Models/TaskList.vala"
	_tmp9_ = _tmp8_;
#line 81 "../src/Models/TaskList.vala"
	_tmp10_ = agenda_task_get_complete (task);
#line 81 "../src/Models/TaskList.vala"
	_tmp11_ = _tmp10_;
#line 81 "../src/Models/TaskList.vala"
	_tmp12_ = agenda_task_get_id (task);
#line 81 "../src/Models/TaskList.vala"
	_tmp13_ = _tmp12_;
#line 81 "../src/Models/TaskList.vala"
	gtk_list_store_set ((GtkListStore*) self, &_tmp5_, AGENDA_TASK_LIST_COLUMNS_TOGGLE, _tmp7_, AGENDA_TASK_LIST_COLUMNS_TEXT, _tmp9_, AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH, _tmp11_, AGENDA_TASK_LIST_COLUMNS_DELETE, "edit-delete-symbolic", AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE, "view-list-symbolic", AGENDA_TASK_LIST_COLUMNS_ID, _tmp13_, -1);
#line 89 "../src/Models/TaskList.vala"
	g_signal_emit (self, agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL], 0);
#line 290 "TaskList.c"
}

void
agenda_task_list_clear_undo (AgendaTaskList* self)
{
	AgendaTaskListHistory* _tmp0_;
	AgendaTaskListHistory* _tmp1_;
#line 92 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 93 "../src/Models/TaskList.vala"
	_tmp0_ = agenda_task_list_history_new ();
#line 93 "../src/Models/TaskList.vala"
	_g_object_unref0 (self->priv->undo_list);
#line 93 "../src/Models/TaskList.vala"
	self->priv->undo_list = _tmp0_;
#line 94 "../src/Models/TaskList.vala"
	_tmp1_ = self->priv->undo_list;
#line 94 "../src/Models/TaskList.vala"
	agenda_task_list_history_add (_tmp1_, self);
#line 310 "TaskList.c"
}

/**
         * Test if the list contains a task with specific id
         *
         * @param id The id of the task
         */
gboolean
agenda_task_list_contains (AgendaTaskList* self,
                           const gchar* id)
{
	GtkTreeIter iter = {0};
	gboolean valid = FALSE;
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	gboolean result = FALSE;
#line 102 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 102 "../src/Models/TaskList.vala"
	g_return_val_if_fail (id != NULL, FALSE);
#line 104 "../src/Models/TaskList.vala"
	_tmp1_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) self, &_tmp0_);
#line 104 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 104 "../src/Models/TaskList.vala"
	valid = _tmp1_;
#line 106 "../src/Models/TaskList.vala"
	while (TRUE) {
#line 339 "TaskList.c"
		gchar* list_id = NULL;
		GtkTreeIter _tmp2_;
		gchar* _tmp3_ = NULL;
		const gchar* _tmp4_;
#line 106 "../src/Models/TaskList.vala"
		if (!valid) {
#line 106 "../src/Models/TaskList.vala"
			break;
#line 348 "TaskList.c"
		}
#line 108 "../src/Models/TaskList.vala"
		_tmp2_ = iter;
#line 108 "../src/Models/TaskList.vala"
		gtk_tree_model_get ((GtkTreeModel*) self, &_tmp2_, AGENDA_TASK_LIST_COLUMNS_ID, &_tmp3_, -1);
#line 108 "../src/Models/TaskList.vala"
		_g_free0 (list_id);
#line 108 "../src/Models/TaskList.vala"
		list_id = _tmp3_;
#line 110 "../src/Models/TaskList.vala"
		_tmp4_ = list_id;
#line 110 "../src/Models/TaskList.vala"
		if (g_strcmp0 (_tmp4_, id) == 0) {
#line 111 "../src/Models/TaskList.vala"
			result = TRUE;
#line 111 "../src/Models/TaskList.vala"
			_g_free0 (list_id);
#line 111 "../src/Models/TaskList.vala"
			return result;
#line 368 "TaskList.c"
		} else {
			gboolean _tmp5_;
#line 113 "../src/Models/TaskList.vala"
			_tmp5_ = gtk_tree_model_iter_next ((GtkTreeModel*) self, &iter);
#line 113 "../src/Models/TaskList.vala"
			valid = _tmp5_;
#line 375 "TaskList.c"
		}
#line 106 "../src/Models/TaskList.vala"
		_g_free0 (list_id);
#line 379 "TaskList.c"
	}
#line 117 "../src/Models/TaskList.vala"
	result = FALSE;
#line 117 "../src/Models/TaskList.vala"
	return result;
#line 385 "TaskList.c"
}

/**
         * Return a copy of the list
         */
AgendaTaskList*
agenda_task_list_copy (AgendaTaskList* self)
{
	AgendaTaskList* list_copy = NULL;
	AgendaTaskList* _tmp0_;
	AgendaTask** tasks = NULL;
	gint _tmp1_ = 0;
	AgendaTask** _tmp2_;
	gint tasks_length1;
	gint _tasks_size_;
	AgendaTaskList* result = NULL;
#line 123 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 124 "../src/Models/TaskList.vala"
	_tmp0_ = agenda_task_list_new ();
#line 124 "../src/Models/TaskList.vala"
	list_copy = _tmp0_;
#line 125 "../src/Models/TaskList.vala"
	_tmp2_ = agenda_task_list_get_all_tasks (self, &_tmp1_);
#line 125 "../src/Models/TaskList.vala"
	tasks = _tmp2_;
#line 125 "../src/Models/TaskList.vala"
	tasks_length1 = _tmp1_;
#line 125 "../src/Models/TaskList.vala"
	_tasks_size_ = tasks_length1;
#line 127 "../src/Models/TaskList.vala"
	agenda_task_list_load_tasks (list_copy, tasks, (gint) tasks_length1);
#line 129 "../src/Models/TaskList.vala"
	result = list_copy;
#line 129 "../src/Models/TaskList.vala"
	tasks = (_vala_array_free (tasks, tasks_length1, (GDestroyNotify) g_object_unref), NULL);
#line 129 "../src/Models/TaskList.vala"
	return result;
#line 424 "TaskList.c"
}

void
agenda_task_list_disable_undo_recording (AgendaTaskList* self)
{
#line 132 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 133 "../src/Models/TaskList.vala"
	agenda_task_list_set_record_undo_enable (self, FALSE);
#line 434 "TaskList.c"
}

void
agenda_task_list_enable_undo_recording (AgendaTaskList* self)
{
#line 136 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 137 "../src/Models/TaskList.vala"
	agenda_task_list_set_record_undo_enable (self, TRUE);
#line 444 "TaskList.c"
}

/**
         * Gets all tasks in the list
         *
         * @return Array of tasks
         */
static gpointer
_g_object_ref0 (gpointer self)
{
#line 153 "../src/Models/TaskList.vala"
	return self ? g_object_ref (self) : NULL;
#line 457 "TaskList.c"
}

static void
_vala_array_add5 (AgendaTask** * array,
                  gint* length,
                  gint* size,
                  AgendaTask* value)
{
#line 153 "../src/Models/TaskList.vala"
	if ((*length) == (*size)) {
#line 153 "../src/Models/TaskList.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 153 "../src/Models/TaskList.vala"
		*array = g_renew (AgendaTask*, *array, (*size) + 1);
#line 472 "TaskList.c"
	}
#line 153 "../src/Models/TaskList.vala"
	(*array)[(*length)++] = value;
#line 153 "../src/Models/TaskList.vala"
	(*array)[*length] = NULL;
#line 478 "TaskList.c"
}

AgendaTask**
agenda_task_list_get_all_tasks (AgendaTaskList* self,
                                gint* result_length1)
{
	GtkTreeIter iter = {0};
	gboolean valid = FALSE;
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	AgendaTask** tasks = NULL;
	AgendaTask** _tmp2_;
	gint tasks_length1;
	gint _tasks_size_;
	AgendaTask** _tmp8_;
	gint _tmp8__length1;
	AgendaTask** result = NULL;
#line 145 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 147 "../src/Models/TaskList.vala"
	_tmp1_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) self, &_tmp0_);
#line 147 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 147 "../src/Models/TaskList.vala"
	valid = _tmp1_;
#line 149 "../src/Models/TaskList.vala"
	_tmp2_ = g_new0 (AgendaTask*, 0 + 1);
#line 149 "../src/Models/TaskList.vala"
	tasks = _tmp2_;
#line 149 "../src/Models/TaskList.vala"
	tasks_length1 = 0;
#line 149 "../src/Models/TaskList.vala"
	_tasks_size_ = tasks_length1;
#line 151 "../src/Models/TaskList.vala"
	while (TRUE) {
#line 514 "TaskList.c"
		AgendaTask* task = NULL;
		GtkTreeIter _tmp3_;
		AgendaTask* _tmp4_;
		AgendaTask* _tmp5_;
		AgendaTask* _tmp6_;
		gboolean _tmp7_;
#line 151 "../src/Models/TaskList.vala"
		if (!valid) {
#line 151 "../src/Models/TaskList.vala"
			break;
#line 525 "TaskList.c"
		}
#line 152 "../src/Models/TaskList.vala"
		_tmp3_ = iter;
#line 152 "../src/Models/TaskList.vala"
		_tmp4_ = agenda_task_list_get_task (self, &_tmp3_);
#line 152 "../src/Models/TaskList.vala"
		task = _tmp4_;
#line 153 "../src/Models/TaskList.vala"
		_tmp5_ = task;
#line 153 "../src/Models/TaskList.vala"
		_tmp6_ = _g_object_ref0 (_tmp5_);
#line 153 "../src/Models/TaskList.vala"
		_vala_array_add5 (&tasks, &tasks_length1, &_tasks_size_, _tmp6_);
#line 154 "../src/Models/TaskList.vala"
		_tmp7_ = gtk_tree_model_iter_next ((GtkTreeModel*) self, &iter);
#line 154 "../src/Models/TaskList.vala"
		valid = _tmp7_;
#line 151 "../src/Models/TaskList.vala"
		_g_object_unref0 (task);
#line 545 "TaskList.c"
	}
#line 157 "../src/Models/TaskList.vala"
	_tmp8_ = tasks;
#line 157 "../src/Models/TaskList.vala"
	_tmp8__length1 = tasks_length1;
#line 157 "../src/Models/TaskList.vala"
	if (result_length1) {
#line 157 "../src/Models/TaskList.vala"
		*result_length1 = _tmp8__length1;
#line 555 "TaskList.c"
	}
#line 157 "../src/Models/TaskList.vala"
	result = _tmp8_;
#line 157 "../src/Models/TaskList.vala"
	return result;
#line 561 "TaskList.c"
}

AgendaTask*
agenda_task_list_get_task (AgendaTaskList* self,
                           GtkTreeIter* iter)
{
	gchar* id = NULL;
	gboolean complete = FALSE;
	gchar* text = NULL;
	GtkTreeIter _tmp0_;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	AgendaTask* _tmp4_;
	AgendaTask* result = NULL;
#line 160 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 160 "../src/Models/TaskList.vala"
	g_return_val_if_fail (iter != NULL, NULL);
#line 165 "../src/Models/TaskList.vala"
	_tmp0_ = *iter;
#line 165 "../src/Models/TaskList.vala"
	gtk_tree_model_get ((GtkTreeModel*) self, &_tmp0_, AGENDA_TASK_LIST_COLUMNS_ID, &_tmp1_, AGENDA_TASK_LIST_COLUMNS_TOGGLE, &_tmp2_, AGENDA_TASK_LIST_COLUMNS_TEXT, &_tmp3_, -1);
#line 165 "../src/Models/TaskList.vala"
	_g_free0 (id);
#line 165 "../src/Models/TaskList.vala"
	id = _tmp1_;
#line 165 "../src/Models/TaskList.vala"
	complete = _tmp2_;
#line 165 "../src/Models/TaskList.vala"
	_g_free0 (text);
#line 165 "../src/Models/TaskList.vala"
	text = _tmp3_;
#line 170 "../src/Models/TaskList.vala"
	_tmp4_ = agenda_task_new_with_attributes (id, complete, text);
#line 170 "../src/Models/TaskList.vala"
	result = _tmp4_;
#line 170 "../src/Models/TaskList.vala"
	_g_free0 (text);
#line 170 "../src/Models/TaskList.vala"
	_g_free0 (id);
#line 170 "../src/Models/TaskList.vala"
	return result;
#line 605 "TaskList.c"
}

gboolean
agenda_task_list_has_duplicates_of (AgendaTaskList* self,
                                    const gchar* id)
{
	GtkTreeIter iter = {0};
	gboolean valid = FALSE;
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	gint count = 0;
	gboolean result = FALSE;
#line 173 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 173 "../src/Models/TaskList.vala"
	g_return_val_if_fail (id != NULL, FALSE);
#line 175 "../src/Models/TaskList.vala"
	_tmp1_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) self, &_tmp0_);
#line 175 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 175 "../src/Models/TaskList.vala"
	valid = _tmp1_;
#line 176 "../src/Models/TaskList.vala"
	count = 0;
#line 178 "../src/Models/TaskList.vala"
	while (TRUE) {
#line 632 "TaskList.c"
		gchar* list_id = NULL;
		GtkTreeIter _tmp2_;
		gchar* _tmp3_ = NULL;
		const gchar* _tmp4_;
		gboolean _tmp6_;
#line 178 "../src/Models/TaskList.vala"
		if (!valid) {
#line 178 "../src/Models/TaskList.vala"
			break;
#line 642 "TaskList.c"
		}
#line 180 "../src/Models/TaskList.vala"
		_tmp2_ = iter;
#line 180 "../src/Models/TaskList.vala"
		gtk_tree_model_get ((GtkTreeModel*) self, &_tmp2_, AGENDA_TASK_LIST_COLUMNS_ID, &_tmp3_, -1);
#line 180 "../src/Models/TaskList.vala"
		_g_free0 (list_id);
#line 180 "../src/Models/TaskList.vala"
		list_id = _tmp3_;
#line 182 "../src/Models/TaskList.vala"
		_tmp4_ = list_id;
#line 182 "../src/Models/TaskList.vala"
		if (g_strcmp0 (_tmp4_, id) == 0) {
#line 656 "TaskList.c"
			gint _tmp5_;
#line 183 "../src/Models/TaskList.vala"
			_tmp5_ = count;
#line 183 "../src/Models/TaskList.vala"
			count = _tmp5_ + 1;
#line 662 "TaskList.c"
		}
#line 184 "../src/Models/TaskList.vala"
		_tmp6_ = gtk_tree_model_iter_next ((GtkTreeModel*) self, &iter);
#line 184 "../src/Models/TaskList.vala"
		valid = _tmp6_;
#line 178 "../src/Models/TaskList.vala"
		_g_free0 (list_id);
#line 670 "TaskList.c"
	}
#line 187 "../src/Models/TaskList.vala"
	if (count > 1) {
#line 188 "../src/Models/TaskList.vala"
		result = TRUE;
#line 188 "../src/Models/TaskList.vala"
		return result;
#line 678 "TaskList.c"
	} else {
#line 190 "../src/Models/TaskList.vala"
		result = FALSE;
#line 190 "../src/Models/TaskList.vala"
		return result;
#line 684 "TaskList.c"
	}
}

/**
         * Gets if the task list is empty or not
         *
         * @return True if the list is empty
         */
gboolean
agenda_task_list_is_empty (AgendaTaskList* self)
{
	GtkTreeIter iter = {0};
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	gboolean result = FALSE;
#line 198 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 200 "../src/Models/TaskList.vala"
	_tmp1_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) self, &_tmp0_);
#line 200 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 200 "../src/Models/TaskList.vala"
	result = !_tmp1_;
#line 200 "../src/Models/TaskList.vala"
	return result;
#line 710 "TaskList.c"
}

void
agenda_task_list_load_tasks (AgendaTaskList* self,
                             AgendaTask** tasks,
                             gint tasks_length1)
{
#line 203 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 720 "TaskList.c"
	{
		AgendaTask** task_collection = NULL;
		gint task_collection_length1 = 0;
		gint _task_collection_size_ = 0;
		gint task_it = 0;
#line 204 "../src/Models/TaskList.vala"
		task_collection = tasks;
#line 204 "../src/Models/TaskList.vala"
		task_collection_length1 = tasks_length1;
#line 204 "../src/Models/TaskList.vala"
		for (task_it = 0; task_it < task_collection_length1; task_it = task_it + 1) {
#line 732 "TaskList.c"
			AgendaTask* _tmp0_;
			AgendaTask* task = NULL;
#line 204 "../src/Models/TaskList.vala"
			_tmp0_ = _g_object_ref0 (task_collection[task_it]);
#line 204 "../src/Models/TaskList.vala"
			task = _tmp0_;
#line 739 "TaskList.c"
			{
				AgendaTask* _tmp1_;
				gboolean _tmp2_;
				gboolean _tmp3_;
				AgendaTask* _tmp4_;
				const gchar* _tmp5_;
				const gchar* _tmp6_;
				AgendaTask* _tmp7_;
				gboolean _tmp8_;
				gboolean _tmp9_;
				AgendaTask* _tmp10_;
				const gchar* _tmp11_;
				const gchar* _tmp12_;
#line 205 "../src/Models/TaskList.vala"
				_tmp1_ = task;
#line 205 "../src/Models/TaskList.vala"
				_tmp2_ = agenda_task_get_complete (_tmp1_);
#line 205 "../src/Models/TaskList.vala"
				_tmp3_ = _tmp2_;
#line 205 "../src/Models/TaskList.vala"
				_tmp4_ = task;
#line 205 "../src/Models/TaskList.vala"
				_tmp5_ = agenda_task_get_text (_tmp4_);
#line 205 "../src/Models/TaskList.vala"
				_tmp6_ = _tmp5_;
#line 205 "../src/Models/TaskList.vala"
				_tmp7_ = task;
#line 205 "../src/Models/TaskList.vala"
				_tmp8_ = agenda_task_get_complete (_tmp7_);
#line 205 "../src/Models/TaskList.vala"
				_tmp9_ = _tmp8_;
#line 205 "../src/Models/TaskList.vala"
				_tmp10_ = task;
#line 205 "../src/Models/TaskList.vala"
				_tmp11_ = agenda_task_get_id (_tmp10_);
#line 205 "../src/Models/TaskList.vala"
				_tmp12_ = _tmp11_;
#line 205 "../src/Models/TaskList.vala"
				gtk_list_store_insert_with_values ((GtkListStore*) self, NULL, -1, AGENDA_TASK_LIST_COLUMNS_TOGGLE, _tmp3_, AGENDA_TASK_LIST_COLUMNS_TEXT, _tmp6_, AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH, _tmp9_, AGENDA_TASK_LIST_COLUMNS_DELETE, "edit-delete-symbolic", AGENDA_TASK_LIST_COLUMNS_DRAGHANDLE, "view-list-symbolic", AGENDA_TASK_LIST_COLUMNS_ID, _tmp12_, -1);
#line 204 "../src/Models/TaskList.vala"
				_g_object_unref0 (task);
#line 781 "TaskList.c"
			}
		}
	}
}

static void
agenda_task_list_on_row_changed (AgendaTaskList* self,
                                 GtkTreePath* path,
                                 GtkTreeIter* iter)
{
	gchar* list_id = NULL;
	GtkTreeIter _tmp0_;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_;
#line 215 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 215 "../src/Models/TaskList.vala"
	g_return_if_fail (path != NULL);
#line 215 "../src/Models/TaskList.vala"
	g_return_if_fail (iter != NULL);
#line 218 "../src/Models/TaskList.vala"
	_tmp0_ = *iter;
#line 218 "../src/Models/TaskList.vala"
	gtk_tree_model_get ((GtkTreeModel*) self, &_tmp0_, AGENDA_TASK_LIST_COLUMNS_ID, &_tmp1_, -1);
#line 218 "../src/Models/TaskList.vala"
	_g_free0 (list_id);
#line 218 "../src/Models/TaskList.vala"
	list_id = _tmp1_;
#line 219 "../src/Models/TaskList.vala"
	_tmp3_ = self->priv->_record_undo_enable;
#line 219 "../src/Models/TaskList.vala"
	if (_tmp3_) {
#line 815 "TaskList.c"
		const gchar* _tmp4_;
#line 219 "../src/Models/TaskList.vala"
		_tmp4_ = list_id;
#line 219 "../src/Models/TaskList.vala"
		_tmp2_ = !agenda_task_list_has_duplicates_of (self, _tmp4_);
#line 821 "TaskList.c"
	} else {
#line 219 "../src/Models/TaskList.vala"
		_tmp2_ = FALSE;
#line 825 "TaskList.c"
	}
#line 219 "../src/Models/TaskList.vala"
	if (_tmp2_) {
#line 829 "TaskList.c"
		AgendaTaskListHistory* _tmp5_;
#line 220 "../src/Models/TaskList.vala"
		_tmp5_ = self->priv->undo_list;
#line 220 "../src/Models/TaskList.vala"
		agenda_task_list_history_add (_tmp5_, self);
#line 221 "../src/Models/TaskList.vala"
		g_signal_emit (self, agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL], 0);
#line 837 "TaskList.c"
	}
#line 215 "../src/Models/TaskList.vala"
	_g_free0 (list_id);
#line 841 "TaskList.c"
}

static void
agenda_task_list_on_row_deleted (AgendaTaskList* self,
                                 GtkTreePath* path)
{
	gboolean _tmp0_;
#line 225 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 225 "../src/Models/TaskList.vala"
	g_return_if_fail (path != NULL);
#line 230 "../src/Models/TaskList.vala"
	_tmp0_ = self->priv->_record_undo_enable;
#line 230 "../src/Models/TaskList.vala"
	if (_tmp0_) {
#line 857 "TaskList.c"
		AgendaTaskListHistory* _tmp1_;
#line 231 "../src/Models/TaskList.vala"
		_tmp1_ = self->priv->undo_list;
#line 231 "../src/Models/TaskList.vala"
		agenda_task_list_history_add (_tmp1_, self);
#line 863 "TaskList.c"
	}
#line 232 "../src/Models/TaskList.vala"
	g_signal_emit (self, agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL], 0);
#line 867 "TaskList.c"
}

gboolean
agenda_task_list_remove_task (AgendaTaskList* self,
                              GtkTreePath* path)
{
	GtkTreeIter iter = {0};
	gchar* id = NULL;
	gchar* text = NULL;
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	gboolean result = FALSE;
#line 235 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 235 "../src/Models/TaskList.vala"
	g_return_val_if_fail (path != NULL, FALSE);
#line 240 "../src/Models/TaskList.vala"
	_tmp1_ = gtk_tree_model_get_iter ((GtkTreeModel*) self, &_tmp0_, path);
#line 240 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 240 "../src/Models/TaskList.vala"
	if (_tmp1_) {
#line 890 "TaskList.c"
		GtkTreeIter _tmp2_;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
#line 241 "../src/Models/TaskList.vala"
		_tmp2_ = iter;
#line 241 "../src/Models/TaskList.vala"
		gtk_tree_model_get ((GtkTreeModel*) self, &_tmp2_, AGENDA_TASK_LIST_COLUMNS_ID, &_tmp3_, AGENDA_TASK_LIST_COLUMNS_TEXT, &_tmp4_, -1);
#line 241 "../src/Models/TaskList.vala"
		_g_free0 (id);
#line 241 "../src/Models/TaskList.vala"
		id = _tmp3_;
#line 241 "../src/Models/TaskList.vala"
		_g_free0 (text);
#line 241 "../src/Models/TaskList.vala"
		text = _tmp4_;
#line 243 "../src/Models/TaskList.vala"
		gtk_list_store_remove ((GtkListStore*) self, &iter);
#line 248 "../src/Models/TaskList.vala"
		result = TRUE;
#line 248 "../src/Models/TaskList.vala"
		_g_free0 (text);
#line 248 "../src/Models/TaskList.vala"
		_g_free0 (id);
#line 248 "../src/Models/TaskList.vala"
		return result;
#line 916 "TaskList.c"
	} else {
#line 250 "../src/Models/TaskList.vala"
		result = FALSE;
#line 250 "../src/Models/TaskList.vala"
		_g_free0 (text);
#line 250 "../src/Models/TaskList.vala"
		_g_free0 (id);
#line 250 "../src/Models/TaskList.vala"
		return result;
#line 926 "TaskList.c"
	}
}

void
agenda_task_list_remove_completed_tasks (AgendaTaskList* self)
{
	GtkTreeIter iter = {0};
	gboolean valid = FALSE;
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	gboolean active = FALSE;
	gint counter = 0;
#line 254 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 256 "../src/Models/TaskList.vala"
	_tmp1_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) self, &_tmp0_);
#line 256 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 256 "../src/Models/TaskList.vala"
	valid = _tmp1_;
#line 258 "../src/Models/TaskList.vala"
	counter = 0;
#line 260 "../src/Models/TaskList.vala"
	while (TRUE) {
#line 951 "TaskList.c"
		GtkTreeIter _tmp2_;
		gboolean _tmp3_ = FALSE;
#line 260 "../src/Models/TaskList.vala"
		if (!valid) {
#line 260 "../src/Models/TaskList.vala"
			break;
#line 958 "TaskList.c"
		}
#line 261 "../src/Models/TaskList.vala"
		_tmp2_ = iter;
#line 261 "../src/Models/TaskList.vala"
		gtk_tree_model_get ((GtkTreeModel*) self, &_tmp2_, AGENDA_TASK_LIST_COLUMNS_TOGGLE, &_tmp3_, -1);
#line 261 "../src/Models/TaskList.vala"
		active = _tmp3_;
#line 263 "../src/Models/TaskList.vala"
		if (active) {
#line 968 "TaskList.c"
			GtkTreeIter _tmp4_ = {0};
			gboolean _tmp5_;
			gint _tmp6_;
#line 265 "../src/Models/TaskList.vala"
			gtk_list_store_remove ((GtkListStore*) self, &iter);
#line 269 "../src/Models/TaskList.vala"
			_tmp5_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) self, &_tmp4_);
#line 269 "../src/Models/TaskList.vala"
			iter = _tmp4_;
#line 269 "../src/Models/TaskList.vala"
			valid = _tmp5_;
#line 270 "../src/Models/TaskList.vala"
			_tmp6_ = counter;
#line 270 "../src/Models/TaskList.vala"
			counter = _tmp6_ + 1;
#line 984 "TaskList.c"
		} else {
			gboolean _tmp7_;
#line 272 "../src/Models/TaskList.vala"
			_tmp7_ = gtk_tree_model_iter_next ((GtkTreeModel*) self, &iter);
#line 272 "../src/Models/TaskList.vala"
			valid = _tmp7_;
#line 991 "TaskList.c"
		}
	}
#line 276 "../src/Models/TaskList.vala"
	g_signal_emit (self, agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL], 0);
#line 996 "TaskList.c"
}

void
agenda_task_list_redo (AgendaTaskList* self)
{
	AgendaTaskList* state = NULL;
	AgendaTaskListHistory* _tmp0_;
	AgendaTaskList* _tmp1_;
	AgendaTaskList* _tmp2_;
#line 279 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 280 "../src/Models/TaskList.vala"
	_tmp0_ = self->priv->undo_list;
#line 280 "../src/Models/TaskList.vala"
	_tmp1_ = agenda_task_list_history_get_next_state (_tmp0_);
#line 280 "../src/Models/TaskList.vala"
	state = _tmp1_;
#line 282 "../src/Models/TaskList.vala"
	_tmp2_ = state;
#line 282 "../src/Models/TaskList.vala"
	if (_tmp2_ != NULL) {
#line 1018 "TaskList.c"
		AgendaTaskList* _tmp3_;
#line 283 "../src/Models/TaskList.vala"
		_tmp3_ = state;
#line 283 "../src/Models/TaskList.vala"
		agenda_task_list_restore_state (self, _tmp3_);
#line 1024 "TaskList.c"
	}
#line 279 "../src/Models/TaskList.vala"
	_g_object_unref0 (state);
#line 1028 "TaskList.c"
}

void
agenda_task_list_undo (AgendaTaskList* self)
{
	AgendaTaskList* state = NULL;
	AgendaTaskListHistory* _tmp0_;
	AgendaTaskList* _tmp1_;
	AgendaTaskList* _tmp2_;
#line 286 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 287 "../src/Models/TaskList.vala"
	_tmp0_ = self->priv->undo_list;
#line 287 "../src/Models/TaskList.vala"
	_tmp1_ = agenda_task_list_history_get_previous_state (_tmp0_);
#line 287 "../src/Models/TaskList.vala"
	state = _tmp1_;
#line 289 "../src/Models/TaskList.vala"
	_tmp2_ = state;
#line 289 "../src/Models/TaskList.vala"
	if (_tmp2_ != NULL) {
#line 1050 "TaskList.c"
		AgendaTaskList* _tmp3_;
#line 290 "../src/Models/TaskList.vala"
		_tmp3_ = state;
#line 290 "../src/Models/TaskList.vala"
		agenda_task_list_restore_state (self, _tmp3_);
#line 1056 "TaskList.c"
	}
#line 286 "../src/Models/TaskList.vala"
	_g_object_unref0 (state);
#line 1060 "TaskList.c"
}

static void
agenda_task_list_restore_state (AgendaTaskList* self,
                                AgendaTaskList* state)
{
	AgendaTask** tasks = NULL;
	gint _tmp0_ = 0;
	AgendaTask** _tmp1_;
	gint tasks_length1;
	gint _tasks_size_;
#line 293 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 293 "../src/Models/TaskList.vala"
	g_return_if_fail (state != NULL);
#line 294 "../src/Models/TaskList.vala"
	agenda_task_list_disable_undo_recording (self);
#line 295 "../src/Models/TaskList.vala"
	gtk_list_store_clear ((GtkListStore*) self);
#line 297 "../src/Models/TaskList.vala"
	_tmp1_ = agenda_task_list_get_all_tasks (state, &_tmp0_);
#line 297 "../src/Models/TaskList.vala"
	tasks = _tmp1_;
#line 297 "../src/Models/TaskList.vala"
	tasks_length1 = _tmp0_;
#line 297 "../src/Models/TaskList.vala"
	_tasks_size_ = tasks_length1;
#line 299 "../src/Models/TaskList.vala"
	agenda_task_list_load_tasks (self, tasks, (gint) tasks_length1);
#line 301 "../src/Models/TaskList.vala"
	agenda_task_list_enable_undo_recording (self);
#line 302 "../src/Models/TaskList.vala"
	g_signal_emit (self, agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL], 0);
#line 293 "../src/Models/TaskList.vala"
	tasks = (_vala_array_free (tasks, tasks_length1, (GDestroyNotify) g_object_unref), NULL);
#line 1096 "TaskList.c"
}

static void
_vala_GtkTreePath_free (GtkTreePath* self)
{
#line 305 "../src/Models/TaskList.vala"
	g_boxed_free (gtk_tree_path_get_type (), self);
#line 1104 "TaskList.c"
}

void
agenda_task_list_set_task_text (AgendaTaskList* self,
                                const gchar* path,
                                const gchar* text)
{
	GtkTreeIter iter = {0};
	GtkTreePath* tree_path = NULL;
	GtkTreePath* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	GtkTreeIter _tmp2_;
#line 305 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 305 "../src/Models/TaskList.vala"
	g_return_if_fail (path != NULL);
#line 305 "../src/Models/TaskList.vala"
	g_return_if_fail (text != NULL);
#line 307 "../src/Models/TaskList.vala"
	_tmp0_ = gtk_tree_path_new_from_string (path);
#line 307 "../src/Models/TaskList.vala"
	tree_path = _tmp0_;
#line 309 "../src/Models/TaskList.vala"
	gtk_tree_model_get_iter ((GtkTreeModel*) self, &_tmp1_, tree_path);
#line 309 "../src/Models/TaskList.vala"
	iter = _tmp1_;
#line 310 "../src/Models/TaskList.vala"
	_tmp2_ = iter;
#line 310 "../src/Models/TaskList.vala"
	gtk_list_store_set ((GtkListStore*) self, &_tmp2_, AGENDA_TASK_LIST_COLUMNS_TEXT, text, -1);
#line 305 "../src/Models/TaskList.vala"
	__vala_GtkTreePath_free0 (tree_path);
#line 1137 "TaskList.c"
}

void
agenda_task_list_toggle_task (AgendaTaskList* self,
                              GtkTreePath* path)
{
	gboolean toggle = FALSE;
	GtkTreeIter iter = {0};
	GtkTreeIter _tmp0_ = {0};
	GtkTreeIter _tmp1_;
	gboolean _tmp2_ = FALSE;
	GtkTreeIter _tmp3_;
#line 313 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 313 "../src/Models/TaskList.vala"
	g_return_if_fail (path != NULL);
#line 317 "../src/Models/TaskList.vala"
	gtk_tree_model_get_iter ((GtkTreeModel*) self, &_tmp0_, path);
#line 317 "../src/Models/TaskList.vala"
	iter = _tmp0_;
#line 319 "../src/Models/TaskList.vala"
	_tmp1_ = iter;
#line 319 "../src/Models/TaskList.vala"
	gtk_tree_model_get ((GtkTreeModel*) self, &_tmp1_, AGENDA_TASK_LIST_COLUMNS_TOGGLE, &_tmp2_, -1);
#line 319 "../src/Models/TaskList.vala"
	toggle = _tmp2_;
#line 320 "../src/Models/TaskList.vala"
	_tmp3_ = iter;
#line 320 "../src/Models/TaskList.vala"
	gtk_list_store_set ((GtkListStore*) self, &_tmp3_, AGENDA_TASK_LIST_COLUMNS_TOGGLE, !toggle, AGENDA_TASK_LIST_COLUMNS_STRIKETHROUGH, !toggle, -1);
#line 324 "../src/Models/TaskList.vala"
	g_signal_emit (self, agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL], 0);
#line 1170 "TaskList.c"
}

AgendaTaskList*
agenda_task_list_construct (GType object_type)
{
	AgendaTaskList * self = NULL;
#line 24 "../src/Models/TaskList.vala"
	self = (AgendaTaskList*) g_object_new (object_type, NULL);
#line 24 "../src/Models/TaskList.vala"
	return self;
#line 1181 "TaskList.c"
}

AgendaTaskList*
agenda_task_list_new (void)
{
#line 24 "../src/Models/TaskList.vala"
	return agenda_task_list_construct (AGENDA_TYPE_TASK_LIST);
#line 1189 "TaskList.c"
}

static gboolean
agenda_task_list_get_record_undo_enable (AgendaTaskList* self)
{
	gboolean result;
#line 41 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 41 "../src/Models/TaskList.vala"
	result = self->priv->_record_undo_enable;
#line 41 "../src/Models/TaskList.vala"
	return result;
#line 1202 "TaskList.c"
}

static void
agenda_task_list_set_record_undo_enable (AgendaTaskList* self,
                                         gboolean value)
{
#line 42 "../src/Models/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 42 "../src/Models/TaskList.vala"
	self->priv->_record_undo_enable = value;
#line 1213 "TaskList.c"
}

gint
agenda_task_list_get_size (AgendaTaskList* self)
{
	gint result;
#line 47 "../src/Models/TaskList.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 47 "../src/Models/TaskList.vala"
	result = gtk_tree_model_iter_n_children ((GtkTreeModel*) self, NULL);
#line 47 "../src/Models/TaskList.vala"
	return result;
#line 1226 "TaskList.c"
}

static void
_agenda_task_list_on_row_changed_gtk_tree_model_row_changed (GtkTreeModel* _sender,
                                                             GtkTreePath* path,
                                                             GtkTreeIter* iter,
                                                             gpointer self)
{
#line 64 "../src/Models/TaskList.vala"
	agenda_task_list_on_row_changed ((AgendaTaskList*) self, path, iter);
#line 1237 "TaskList.c"
}

static void
_agenda_task_list_on_row_deleted_gtk_tree_model_row_deleted (GtkTreeModel* _sender,
                                                             GtkTreePath* path,
                                                             gpointer self)
{
#line 65 "../src/Models/TaskList.vala"
	agenda_task_list_on_row_deleted ((AgendaTaskList*) self, path);
#line 1247 "TaskList.c"
}

static GObject *
agenda_task_list_constructor (GType type,
                              guint n_construct_properties,
                              GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	AgendaTaskList * self;
	AgendaTaskListHistory* _tmp0_;
	GType* types = NULL;
	GType* _tmp1_;
	gint types_length1;
	gint _types_size_;
	GType* _tmp2_;
	gint _tmp2__length1;
#line 50 "../src/Models/TaskList.vala"
	parent_class = G_OBJECT_CLASS (agenda_task_list_parent_class);
#line 50 "../src/Models/TaskList.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 50 "../src/Models/TaskList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK_LIST, AgendaTaskList);
#line 51 "../src/Models/TaskList.vala"
	_tmp0_ = agenda_task_list_history_new ();
#line 51 "../src/Models/TaskList.vala"
	_g_object_unref0 (self->priv->undo_list);
#line 51 "../src/Models/TaskList.vala"
	self->priv->undo_list = _tmp0_;
#line 53 "../src/Models/TaskList.vala"
	_tmp1_ = g_new0 (GType, 6);
#line 53 "../src/Models/TaskList.vala"
	_tmp1_[0] = G_TYPE_BOOLEAN;
#line 53 "../src/Models/TaskList.vala"
	_tmp1_[1] = G_TYPE_STRING;
#line 53 "../src/Models/TaskList.vala"
	_tmp1_[2] = G_TYPE_BOOLEAN;
#line 53 "../src/Models/TaskList.vala"
	_tmp1_[3] = G_TYPE_STRING;
#line 53 "../src/Models/TaskList.vala"
	_tmp1_[4] = G_TYPE_STRING;
#line 53 "../src/Models/TaskList.vala"
	_tmp1_[5] = G_TYPE_STRING;
#line 53 "../src/Models/TaskList.vala"
	types = _tmp1_;
#line 53 "../src/Models/TaskList.vala"
	types_length1 = 6;
#line 53 "../src/Models/TaskList.vala"
	_types_size_ = types_length1;
#line 62 "../src/Models/TaskList.vala"
	_tmp2_ = types;
#line 62 "../src/Models/TaskList.vala"
	_tmp2__length1 = types_length1;
#line 62 "../src/Models/TaskList.vala"
	gtk_list_store_set_column_types ((GtkListStore*) self, (gint) _tmp2__length1, _tmp2_);
#line 64 "../src/Models/TaskList.vala"
	g_signal_connect_object ((GtkTreeModel*) self, "row-changed", (GCallback) _agenda_task_list_on_row_changed_gtk_tree_model_row_changed, self, 0);
#line 65 "../src/Models/TaskList.vala"
	g_signal_connect_object ((GtkTreeModel*) self, "row-deleted", (GCallback) _agenda_task_list_on_row_deleted_gtk_tree_model_row_deleted, self, 0);
#line 50 "../src/Models/TaskList.vala"
	types = (g_free (types), NULL);
#line 50 "../src/Models/TaskList.vala"
	return obj;
#line 1311 "TaskList.c"
}

static void
agenda_task_list_class_init (AgendaTaskListClass * klass,
                             gpointer klass_data)
{
#line 24 "../src/Models/TaskList.vala"
	agenda_task_list_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/Models/TaskList.vala"
	g_type_class_adjust_private_offset (klass, &AgendaTaskList_private_offset);
#line 24 "../src/Models/TaskList.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_agenda_task_list_get_property;
#line 24 "../src/Models/TaskList.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_agenda_task_list_set_property;
#line 24 "../src/Models/TaskList.vala"
	G_OBJECT_CLASS (klass)->constructor = agenda_task_list_constructor;
#line 24 "../src/Models/TaskList.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_task_list_finalize;
#line 24 "../src/Models/TaskList.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), AGENDA_TASK_LIST_SIZE_PROPERTY, agenda_task_list_properties[AGENDA_TASK_LIST_SIZE_PROPERTY] = g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 24 "../src/Models/TaskList.vala"
	agenda_task_list_signals[AGENDA_TASK_LIST_LIST_CHANGED_SIGNAL] = g_signal_new ("list-changed", AGENDA_TYPE_TASK_LIST, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1334 "TaskList.c"
}

static void
agenda_task_list_instance_init (AgendaTaskList * self,
                                gpointer klass)
{
#line 24 "../src/Models/TaskList.vala"
	self->priv = agenda_task_list_get_instance_private (self);
#line 40 "../src/Models/TaskList.vala"
	self->priv->_record_undo_enable = TRUE;
#line 1345 "TaskList.c"
}

static void
agenda_task_list_finalize (GObject * obj)
{
	AgendaTaskList * self;
#line 24 "../src/Models/TaskList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_TASK_LIST, AgendaTaskList);
#line 38 "../src/Models/TaskList.vala"
	_g_object_unref0 (self->priv->undo_list);
#line 24 "../src/Models/TaskList.vala"
	G_OBJECT_CLASS (agenda_task_list_parent_class)->finalize (obj);
#line 1358 "TaskList.c"
}

static GType
agenda_task_list_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaTaskListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_task_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaTaskList), 0, (GInstanceInitFunc) agenda_task_list_instance_init, NULL };
	GType agenda_task_list_type_id;
	agenda_task_list_type_id = g_type_register_static (gtk_list_store_get_type (), "AgendaTaskList", &g_define_type_info, 0);
	AgendaTaskList_private_offset = g_type_add_instance_private (agenda_task_list_type_id, sizeof (AgendaTaskListPrivate));
	return agenda_task_list_type_id;
}

GType
agenda_task_list_get_type (void)
{
	static volatile gsize agenda_task_list_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_task_list_type_id__volatile)) {
		GType agenda_task_list_type_id;
		agenda_task_list_type_id = agenda_task_list_get_type_once ();
		g_once_init_leave (&agenda_task_list_type_id__volatile, agenda_task_list_type_id);
	}
	return agenda_task_list_type_id__volatile;
}

static void
_vala_agenda_task_list_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec)
{
	AgendaTaskList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AGENDA_TYPE_TASK_LIST, AgendaTaskList);
#line 24 "../src/Models/TaskList.vala"
	switch (property_id) {
#line 24 "../src/Models/TaskList.vala"
		case AGENDA_TASK_LIST_SIZE_PROPERTY:
#line 24 "../src/Models/TaskList.vala"
		g_value_set_int (value, agenda_task_list_get_size (self));
#line 24 "../src/Models/TaskList.vala"
		break;
#line 1399 "TaskList.c"
		default:
#line 24 "../src/Models/TaskList.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Models/TaskList.vala"
		break;
#line 1405 "TaskList.c"
	}
}

static void
_vala_agenda_task_list_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec)
{
	AgendaTaskList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, AGENDA_TYPE_TASK_LIST, AgendaTaskList);
#line 24 "../src/Models/TaskList.vala"
	switch (property_id) {
#line 1419 "TaskList.c"
		default:
#line 24 "../src/Models/TaskList.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Models/TaskList.vala"
		break;
#line 1425 "TaskList.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

