/* Agenda.c generated by valac 0.54.3, the Vala compiler
 * generated from Agenda.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_AGENDA (agenda_agenda_get_type ())
#define AGENDA_AGENDA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_AGENDA, AgendaAgenda))
#define AGENDA_AGENDA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_AGENDA, AgendaAgendaClass))
#define AGENDA_IS_AGENDA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_AGENDA))
#define AGENDA_IS_AGENDA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_AGENDA))
#define AGENDA_AGENDA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_AGENDA, AgendaAgendaClass))

typedef struct _AgendaAgenda AgendaAgenda;
typedef struct _AgendaAgendaClass AgendaAgendaClass;
typedef struct _AgendaAgendaPrivate AgendaAgendaPrivate;

#define AGENDA_TYPE_AGENDA_WINDOW (agenda_agenda_window_get_type ())
#define AGENDA_AGENDA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindow))
#define AGENDA_AGENDA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindowClass))
#define AGENDA_IS_AGENDA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_AGENDA_WINDOW))
#define AGENDA_IS_AGENDA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_AGENDA_WINDOW))
#define AGENDA_AGENDA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindowClass))

typedef struct _AgendaAgendaWindow AgendaAgendaWindow;
typedef struct _AgendaAgendaWindowClass AgendaAgendaWindowClass;
enum  {
	AGENDA_AGENDA_0_PROPERTY,
	AGENDA_AGENDA_NUM_PROPERTIES
};
static GParamSpec* agenda_agenda_properties[AGENDA_AGENDA_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AgendaAgenda {
	GtkApplication parent_instance;
	AgendaAgendaPrivate * priv;
};

struct _AgendaAgendaClass {
	GtkApplicationClass parent_class;
};

struct _AgendaAgendaPrivate {
	AgendaAgendaWindow* window;
};

static gint AgendaAgenda_private_offset;
static gpointer agenda_agenda_parent_class = NULL;
VALA_EXTERN GSettings* agenda_agenda_settings;
GSettings* agenda_agenda_settings = NULL;
static AgendaAgenda* agenda_agenda_app;
static AgendaAgenda* agenda_agenda_app = NULL;

VALA_EXTERN GType agenda_agenda_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaAgenda, g_object_unref)
VALA_EXTERN GType agenda_agenda_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaAgendaWindow, g_object_unref)
VALA_EXTERN AgendaAgenda* agenda_agenda_new (void);
VALA_EXTERN AgendaAgenda* agenda_agenda_construct (GType object_type);
static void agenda_agenda_real_activate (GApplication* base);
VALA_EXTERN AgendaAgendaWindow* agenda_agenda_window_new (AgendaAgenda* app);
VALA_EXTERN AgendaAgendaWindow* agenda_agenda_window_construct (GType object_type,
                                                    AgendaAgenda* app);
VALA_EXTERN gboolean agenda_agenda_window_main_quit (AgendaAgendaWindow* self);
static gboolean _agenda_agenda_window_main_quit_gtk_widget_delete_event (GtkWidget* _sender,
                                                                  GdkEventAny* event,
                                                                  gpointer self);
VALA_EXTERN void agenda_agenda_window_update (AgendaAgendaWindow* self);
VALA_EXTERN gboolean agenda_agenda_elementary_stylesheet (void);
VALA_EXTERN AgendaAgenda* agenda_agenda_get_instance (void);
static gint agenda_agenda_main (gchar** args,
                         gint args_length1);
static void agenda_agenda_finalize (GObject * obj);
static GType agenda_agenda_get_type_once (void);

static inline gpointer
agenda_agenda_get_instance_private (AgendaAgenda* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaAgenda_private_offset);
}

AgendaAgenda*
agenda_agenda_construct (GType object_type)
{
	AgendaAgenda * self = NULL;
#line 37 "../src/Agenda.vala"
	self = (AgendaAgenda*) g_object_new (object_type, "application-id", "com.github.dahenson.agenda", "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 36 "../src/Agenda.vala"
	return self;
#line 107 "Agenda.c"
}

AgendaAgenda*
agenda_agenda_new (void)
{
#line 36 "../src/Agenda.vala"
	return agenda_agenda_construct (AGENDA_TYPE_AGENDA);
#line 115 "Agenda.c"
}

static gboolean
_agenda_agenda_window_main_quit_gtk_widget_delete_event (GtkWidget* _sender,
                                                         GdkEventAny* event,
                                                         gpointer self)
{
	gboolean result;
	result = agenda_agenda_window_main_quit ((AgendaAgendaWindow*) self);
#line 48 "../src/Agenda.vala"
	return result;
#line 127 "Agenda.c"
}

static void
agenda_agenda_real_activate (GApplication* base)
{
	AgendaAgenda * self;
	AgendaAgendaWindow* _tmp0_;
	AgendaAgendaWindow* _tmp2_;
	AgendaAgendaWindow* _tmp3_;
	AgendaAgendaWindow* _tmp4_;
	AgendaAgendaWindow* _tmp5_;
	AgendaAgendaWindow* _tmp6_;
#line 41 "../src/Agenda.vala"
	self = (AgendaAgenda*) base;
#line 42 "../src/Agenda.vala"
	_tmp0_ = self->priv->window;
#line 42 "../src/Agenda.vala"
	if (_tmp0_ != NULL) {
#line 146 "Agenda.c"
		AgendaAgendaWindow* _tmp1_;
#line 43 "../src/Agenda.vala"
		_tmp1_ = self->priv->window;
#line 43 "../src/Agenda.vala"
		gtk_window_present ((GtkWindow*) _tmp1_);
#line 44 "../src/Agenda.vala"
		return;
#line 154 "Agenda.c"
	}
#line 47 "../src/Agenda.vala"
	_tmp2_ = agenda_agenda_window_new (self);
#line 47 "../src/Agenda.vala"
	g_object_ref_sink (_tmp2_);
#line 47 "../src/Agenda.vala"
	_g_object_unref0 (self->priv->window);
#line 47 "../src/Agenda.vala"
	self->priv->window = _tmp2_;
#line 48 "../src/Agenda.vala"
	_tmp3_ = self->priv->window;
#line 48 "../src/Agenda.vala"
	_tmp4_ = self->priv->window;
#line 48 "../src/Agenda.vala"
	g_signal_connect_object ((GtkWidget*) _tmp3_, "delete-event", (GCallback) _agenda_agenda_window_main_quit_gtk_widget_delete_event, _tmp4_, 0);
#line 49 "../src/Agenda.vala"
	_tmp5_ = self->priv->window;
#line 49 "../src/Agenda.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp5_);
#line 50 "../src/Agenda.vala"
	_tmp6_ = self->priv->window;
#line 50 "../src/Agenda.vala"
	agenda_agenda_window_update (_tmp6_);
#line 52 "../src/Agenda.vala"
	if (agenda_agenda_elementary_stylesheet ()) {
#line 180 "Agenda.c"
		GtkCssProvider* elementary_provider = NULL;
		GtkCssProvider* _tmp7_;
		GtkCssProvider* _tmp8_;
		GdkScreen* _tmp9_;
		GtkCssProvider* _tmp10_;
#line 53 "../src/Agenda.vala"
		_tmp7_ = gtk_css_provider_new ();
#line 53 "../src/Agenda.vala"
		elementary_provider = _tmp7_;
#line 54 "../src/Agenda.vala"
		_tmp8_ = elementary_provider;
#line 54 "../src/Agenda.vala"
		gtk_css_provider_load_from_resource (_tmp8_, "com/github/dahenson/agenda/Agenda.css");
#line 56 "../src/Agenda.vala"
		_tmp9_ = gdk_screen_get_default ();
#line 56 "../src/Agenda.vala"
		_tmp10_ = elementary_provider;
#line 56 "../src/Agenda.vala"
		gtk_style_context_add_provider_for_screen (_tmp9_, (GtkStyleProvider*) _tmp10_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 52 "../src/Agenda.vala"
		_g_object_unref0 (elementary_provider);
#line 202 "Agenda.c"
	}
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 68 "../src/Agenda.vala"
	return self ? g_object_ref (self) : NULL;
#line 211 "Agenda.c"
}

AgendaAgenda*
agenda_agenda_get_instance (void)
{
	AgendaAgenda* _tmp0_;
	AgendaAgenda* _tmp2_;
	AgendaAgenda* _tmp3_;
	AgendaAgenda* result = NULL;
#line 64 "../src/Agenda.vala"
	_tmp0_ = agenda_agenda_app;
#line 64 "../src/Agenda.vala"
	if (_tmp0_ == NULL) {
#line 225 "Agenda.c"
		AgendaAgenda* _tmp1_;
#line 65 "../src/Agenda.vala"
		_tmp1_ = agenda_agenda_new ();
#line 65 "../src/Agenda.vala"
		_g_object_unref0 (agenda_agenda_app);
#line 65 "../src/Agenda.vala"
		agenda_agenda_app = _tmp1_;
#line 233 "Agenda.c"
	}
#line 68 "../src/Agenda.vala"
	_tmp2_ = agenda_agenda_app;
#line 68 "../src/Agenda.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 68 "../src/Agenda.vala"
	result = _tmp3_;
#line 68 "../src/Agenda.vala"
	return result;
#line 243 "Agenda.c"
}

static gint
agenda_agenda_main (gchar** args,
                    gint args_length1)
{
	AgendaAgenda* _tmp0_;
	const gchar* _tmp1_;
	AgendaAgenda* _tmp2_;
	gint result = 0;
#line 72 "../src/Agenda.vala"
	_tmp0_ = agenda_agenda_new ();
#line 72 "../src/Agenda.vala"
	_g_object_unref0 (agenda_agenda_app);
#line 72 "../src/Agenda.vala"
	agenda_agenda_app = _tmp0_;
#line 74 "../src/Agenda.vala"
	_tmp1_ = args[1];
#line 74 "../src/Agenda.vala"
	if (g_strcmp0 (_tmp1_, "-s") == 0) {
#line 75 "../src/Agenda.vala"
		result = 0;
#line 75 "../src/Agenda.vala"
		return result;
#line 268 "Agenda.c"
	}
#line 78 "../src/Agenda.vala"
	_tmp2_ = agenda_agenda_app;
#line 78 "../src/Agenda.vala"
	result = g_application_run ((GApplication*) _tmp2_, (gint) args_length1, args);
#line 78 "../src/Agenda.vala"
	return result;
#line 276 "Agenda.c"
}

int
main (int argc,
      char ** argv)
{
#line 71 "../src/Agenda.vala"
	return agenda_agenda_main (argv, argc);
#line 285 "Agenda.c"
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result = FALSE;
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1531 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1531 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1531 "glib-2.0.vapi"
	return result;
#line 304 "Agenda.c"
}

gboolean
agenda_agenda_elementary_stylesheet (void)
{
	GtkSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gboolean _tmp4_;
	gboolean result = FALSE;
#line 82 "../src/Agenda.vala"
	_tmp0_ = gtk_settings_get_default ();
#line 82 "../src/Agenda.vala"
	g_object_get (_tmp0_, "gtk-theme-name", &_tmp1_, NULL);
#line 82 "../src/Agenda.vala"
	_tmp2_ = _tmp1_;
#line 82 "../src/Agenda.vala"
	_tmp3_ = _tmp2_;
#line 82 "../src/Agenda.vala"
	_tmp4_ = string_contains (_tmp3_, "elementary");
#line 82 "../src/Agenda.vala"
	_g_free0 (_tmp3_);
#line 82 "../src/Agenda.vala"
	result = _tmp4_;
#line 82 "../src/Agenda.vala"
	return result;
#line 332 "Agenda.c"
}

static void
agenda_agenda_class_init (AgendaAgendaClass * klass,
                          gpointer klass_data)
{
	GSettings* _tmp0_;
#line 27 "../src/Agenda.vala"
	agenda_agenda_parent_class = g_type_class_peek_parent (klass);
#line 27 "../src/Agenda.vala"
	g_type_class_adjust_private_offset (klass, &AgendaAgenda_private_offset);
#line 27 "../src/Agenda.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) agenda_agenda_real_activate;
#line 27 "../src/Agenda.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_agenda_finalize;
#line 33 "../src/Agenda.vala"
	_tmp0_ = g_settings_new ("com.github.dahenson.agenda");
#line 33 "../src/Agenda.vala"
	_g_object_unref0 (agenda_agenda_settings);
#line 33 "../src/Agenda.vala"
	agenda_agenda_settings = _tmp0_;
#line 354 "Agenda.c"
}

static void
agenda_agenda_instance_init (AgendaAgenda * self,
                             gpointer klass)
{
#line 27 "../src/Agenda.vala"
	self->priv = agenda_agenda_get_instance_private (self);
#line 30 "../src/Agenda.vala"
	self->priv->window = NULL;
#line 365 "Agenda.c"
}

static void
agenda_agenda_finalize (GObject * obj)
{
	AgendaAgenda * self;
#line 27 "../src/Agenda.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_AGENDA, AgendaAgenda);
#line 30 "../src/Agenda.vala"
	_g_object_unref0 (self->priv->window);
#line 27 "../src/Agenda.vala"
	G_OBJECT_CLASS (agenda_agenda_parent_class)->finalize (obj);
#line 378 "Agenda.c"
}

static GType
agenda_agenda_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaAgendaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_agenda_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaAgenda), 0, (GInstanceInitFunc) agenda_agenda_instance_init, NULL };
	GType agenda_agenda_type_id;
	agenda_agenda_type_id = g_type_register_static (gtk_application_get_type (), "AgendaAgenda", &g_define_type_info, 0);
	AgendaAgenda_private_offset = g_type_add_instance_private (agenda_agenda_type_id, sizeof (AgendaAgendaPrivate));
	return agenda_agenda_type_id;
}

GType
agenda_agenda_get_type (void)
{
	static volatile gsize agenda_agenda_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_agenda_type_id__volatile)) {
		GType agenda_agenda_type_id;
		agenda_agenda_type_id = agenda_agenda_get_type_once ();
		g_once_init_leave (&agenda_agenda_type_id__volatile, agenda_agenda_type_id);
	}
	return agenda_agenda_type_id__volatile;
}

