/* Window.c generated by valac 0.54.3, the Vala compiler
 * generated from Window.vala, do not modify */

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <granite.h>
#include <gdk/gdk.h>
#include <cairo-gobject.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_AGENDA_WINDOW (agenda_agenda_window_get_type ())
#define AGENDA_AGENDA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindow))
#define AGENDA_AGENDA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindowClass))
#define AGENDA_IS_AGENDA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_AGENDA_WINDOW))
#define AGENDA_IS_AGENDA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_AGENDA_WINDOW))
#define AGENDA_AGENDA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindowClass))

typedef struct _AgendaAgendaWindow AgendaAgendaWindow;
typedef struct _AgendaAgendaWindowClass AgendaAgendaWindowClass;
typedef struct _AgendaAgendaWindowPrivate AgendaAgendaWindowPrivate;

#define AGENDA_TYPE_FILE_BACKEND (agenda_file_backend_get_type ())
#define AGENDA_FILE_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_FILE_BACKEND, AgendaFileBackend))
#define AGENDA_FILE_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_FILE_BACKEND, AgendaFileBackendClass))
#define AGENDA_IS_FILE_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_FILE_BACKEND))
#define AGENDA_IS_FILE_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_FILE_BACKEND))
#define AGENDA_FILE_BACKEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_FILE_BACKEND, AgendaFileBackendClass))

typedef struct _AgendaFileBackend AgendaFileBackend;
typedef struct _AgendaFileBackendClass AgendaFileBackendClass;

#define AGENDA_TYPE_TASK_VIEW (agenda_task_view_get_type ())
#define AGENDA_TASK_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_VIEW, AgendaTaskView))
#define AGENDA_TASK_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_VIEW, AgendaTaskViewClass))
#define AGENDA_IS_TASK_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_VIEW))
#define AGENDA_IS_TASK_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_VIEW))
#define AGENDA_TASK_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_VIEW, AgendaTaskViewClass))

typedef struct _AgendaTaskView AgendaTaskView;
typedef struct _AgendaTaskViewClass AgendaTaskViewClass;

#define AGENDA_TYPE_TASK_LIST (agenda_task_list_get_type ())
#define AGENDA_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskList))
#define AGENDA_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))
#define AGENDA_IS_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK_LIST))
#define AGENDA_IS_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK_LIST))
#define AGENDA_TASK_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK_LIST, AgendaTaskListClass))

typedef struct _AgendaTaskList AgendaTaskList;
typedef struct _AgendaTaskListClass AgendaTaskListClass;

#define AGENDA_TYPE_HISTORY_LIST (agenda_history_list_get_type ())
#define AGENDA_HISTORY_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_HISTORY_LIST, AgendaHistoryList))
#define AGENDA_HISTORY_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_HISTORY_LIST, AgendaHistoryListClass))
#define AGENDA_IS_HISTORY_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_HISTORY_LIST))
#define AGENDA_IS_HISTORY_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_HISTORY_LIST))
#define AGENDA_HISTORY_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_HISTORY_LIST, AgendaHistoryListClass))

typedef struct _AgendaHistoryList AgendaHistoryList;
typedef struct _AgendaHistoryListClass AgendaHistoryListClass;
enum  {
	AGENDA_AGENDA_WINDOW_0_PROPERTY,
	AGENDA_AGENDA_WINDOW_NUM_PROPERTIES
};
static GParamSpec* agenda_agenda_window_properties[AGENDA_AGENDA_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define AGENDA_TYPE_AGENDA (agenda_agenda_get_type ())
#define AGENDA_AGENDA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_AGENDA, AgendaAgenda))
#define AGENDA_AGENDA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_AGENDA, AgendaAgendaClass))
#define AGENDA_IS_AGENDA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_AGENDA))
#define AGENDA_IS_AGENDA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_AGENDA))
#define AGENDA_AGENDA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_AGENDA, AgendaAgendaClass))

typedef struct _AgendaAgenda AgendaAgenda;
typedef struct _AgendaAgendaClass AgendaAgendaClass;

#define AGENDA_TYPE_TASK (agenda_task_get_type ())
#define AGENDA_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK, AgendaTask))
#define AGENDA_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK, AgendaTaskClass))
#define AGENDA_IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK))
#define AGENDA_IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK))
#define AGENDA_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK, AgendaTaskClass))

typedef struct _AgendaTask AgendaTask;
typedef struct _AgendaTaskClass AgendaTaskClass;

#define AGENDA_TYPE_BACKEND (agenda_backend_get_type ())
#define AGENDA_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_BACKEND, AgendaBackend))
#define AGENDA_IS_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_BACKEND))
#define AGENDA_BACKEND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), AGENDA_TYPE_BACKEND, AgendaBackendIface))

typedef struct _AgendaBackend AgendaBackend;
typedef struct _AgendaBackendIface AgendaBackendIface;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
typedef struct _AgendaTaskViewPrivate AgendaTaskViewPrivate;

struct _AgendaAgendaWindow {
	GtkApplicationWindow parent_instance;
	AgendaAgendaWindowPrivate * priv;
};

struct _AgendaAgendaWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _AgendaAgendaWindowPrivate {
	guint configure_id;
	GSettings* privacy_setting;
	AgendaFileBackend* backend;
	GraniteWidgetsWelcome* agenda_welcome;
	AgendaTaskView* task_view;
	AgendaTaskList* task_list;
	GtkScrolledWindow* scrolled_window;
	GtkEntry* task_entry;
	AgendaHistoryList* history_list;
};

struct _AgendaBackendIface {
	GTypeInterface parent_iface;
	AgendaTask** (*load_tasks) (AgendaBackend* self, gint* result_length1);
	gchar** (*load_history) (AgendaBackend* self, gint* result_length1);
	void (*save_tasks) (AgendaBackend* self, AgendaTask** tasks, gint tasks_length1);
	void (*save_history) (AgendaBackend* self, gchar** history, gint history_length1);
};

struct _AgendaTaskView {
	GtkTreeView parent_instance;
	AgendaTaskViewPrivate * priv;
	gboolean is_editing;
};

struct _AgendaTaskViewClass {
	GtkTreeViewClass parent_class;
};

static gint AgendaAgendaWindow_private_offset;
static gpointer agenda_agenda_window_parent_class = NULL;
VALA_EXTERN GSettings* agenda_agenda_settings;

#define AGENDA_MIN_WIDTH 500
#define AGENDA_MIN_HEIGHT 600
#define AGENDA_HINT_STRING _ ("Add a new task…")
VALA_EXTERN GType agenda_agenda_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaAgendaWindow, g_object_unref)
VALA_EXTERN GType agenda_file_backend_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaFileBackend, g_object_unref)
VALA_EXTERN GType agenda_task_view_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskView, g_object_unref)
VALA_EXTERN GType agenda_task_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTaskList, g_object_unref)
VALA_EXTERN GType agenda_history_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaHistoryList, g_object_unref)
VALA_EXTERN GType agenda_agenda_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaAgenda, g_object_unref)
VALA_EXTERN AgendaAgendaWindow* agenda_agenda_window_new (AgendaAgenda* app);
VALA_EXTERN AgendaAgendaWindow* agenda_agenda_window_construct (GType object_type,
                                                    AgendaAgenda* app);
VALA_EXTERN void agenda_agenda_window_restore_window_position (AgendaAgendaWindow* self);
VALA_EXTERN AgendaTaskList* agenda_task_list_new (void);
VALA_EXTERN AgendaTaskList* agenda_task_list_construct (GType object_type);
VALA_EXTERN AgendaTaskView* agenda_task_view_new_with_list (AgendaTaskList* list);
VALA_EXTERN AgendaTaskView* agenda_task_view_construct_with_list (GType object_type,
                                                      AgendaTaskList* list);
VALA_EXTERN AgendaHistoryList* agenda_history_list_new (void);
VALA_EXTERN AgendaHistoryList* agenda_history_list_construct (GType object_type);
VALA_EXTERN AgendaFileBackend* agenda_file_backend_new (void);
VALA_EXTERN AgendaFileBackend* agenda_file_backend_construct (GType object_type);
static void agenda_agenda_window_load_list (AgendaAgendaWindow* self);
static void agenda_agenda_window_setup_ui (AgendaAgendaWindow* self);
static void _gtk_window_close_g_simple_action_activate (GSimpleAction* _sender,
                                                 GVariant* parameter,
                                                 gpointer self);
VALA_EXTERN void agenda_task_list_undo (AgendaTaskList* self);
static void _agenda_task_list_undo_g_simple_action_activate (GSimpleAction* _sender,
                                                      GVariant* parameter,
                                                      gpointer self);
VALA_EXTERN void agenda_task_list_redo (AgendaTaskList* self);
static void _agenda_task_list_redo_g_simple_action_activate (GSimpleAction* _sender,
                                                      GVariant* parameter,
                                                      gpointer self);
VALA_EXTERN void agenda_task_list_disable_undo_recording (AgendaTaskList* self);
VALA_EXTERN GType agenda_task_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTask, g_object_unref)
VALA_EXTERN GType agenda_backend_get_type (void) G_GNUC_CONST ;
VALA_EXTERN AgendaTask** agenda_backend_load_tasks (AgendaBackend* self,
                                        gint* result_length1);
VALA_EXTERN void agenda_task_list_append_task (AgendaTaskList* self,
                                   AgendaTask* task);
VALA_EXTERN gchar** agenda_backend_load_history (AgendaBackend* self,
                                     gint* result_length1);
VALA_EXTERN gboolean agenda_agenda_window_privacy_mode_off (AgendaAgendaWindow* self);
VALA_EXTERN void agenda_history_list_add_item (AgendaHistoryList* self,
                                   const gchar* text);
VALA_EXTERN void agenda_task_list_enable_undo_recording (AgendaTaskList* self);
VALA_EXTERN void agenda_task_list_clear_undo (AgendaTaskList* self);
VALA_EXTERN void agenda_agenda_window_append_task (AgendaAgendaWindow* self);
static void _agenda_agenda_window_append_task_gtk_entry_activate (GtkEntry* _sender,
                                                           gpointer self);
static void _agenda_agenda_window_append_task_gtk_entry_icon_press (GtkEntry* _sender,
                                                             GtkEntryIconPosition icon_pos,
                                                             GdkEvent* event,
                                                             gpointer self);
static void __lambda7_ (AgendaAgendaWindow* self);
static void ___lambda7__gtk_editable_changed (GtkEditable* _sender,
                                       gpointer self);
static void __lambda8_ (AgendaAgendaWindow* self,
                 GtkMenu* menu);
static void __lambda9_ (AgendaAgendaWindow* self);
static void ___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender,
                                         gpointer self);
static void ___lambda8__gtk_entry_populate_popup (GtkEntry* _sender,
                                           GtkMenu* popup,
                                           gpointer self);
static gboolean __lambda10_ (AgendaAgendaWindow* self,
                      GdkEventFocus* e);
static gboolean ___lambda10__gtk_widget_focus_out_event (GtkWidget* _sender,
                                                  GdkEventFocus* event,
                                                  gpointer self);
static void __lambda11_ (AgendaAgendaWindow* self);
VALA_EXTERN void agenda_backend_save_tasks (AgendaBackend* self,
                                AgendaTask** tasks,
                                gint tasks_length1);
VALA_EXTERN AgendaTask** agenda_task_list_get_all_tasks (AgendaTaskList* self,
                                             gint* result_length1);
VALA_EXTERN void agenda_agenda_window_update (AgendaAgendaWindow* self);
static void ___lambda11__agenda_task_list_list_changed (AgendaTaskList* _sender,
                                                 gpointer self);
VALA_EXTERN gboolean agenda_agenda_window_key_down_event (AgendaAgendaWindow* self,
                                              GdkEventKey* e);
static gboolean _agenda_agenda_window_key_down_event_gtk_widget_key_press_event (GtkWidget* _sender,
                                                                          GdkEventKey* event,
                                                                          gpointer self);
VALA_EXTERN AgendaTask* agenda_task_new_with_attributes (const gchar* id,
                                             gboolean complete,
                                             const gchar* text);
VALA_EXTERN AgendaTask* agenda_task_construct_with_attributes (GType object_type,
                                                   const gchar* id,
                                                   gboolean complete,
                                                   const gchar* text);
VALA_EXTERN const gchar* agenda_task_get_text (AgendaTask* self);
static gint _variant_get1 (GVariant* value);
static gint _variant_get2 (GVariant* value);
static gint _variant_get3 (GVariant* value);
static gint _variant_get4 (GVariant* value);
VALA_EXTERN gboolean agenda_agenda_window_main_quit (AgendaAgendaWindow* self);
VALA_EXTERN void agenda_backend_save_history (AgendaBackend* self,
                                  gchar** history,
                                  gint history_length1);
VALA_EXTERN gchar** agenda_history_list_get_all_tasks (AgendaHistoryList* self,
                                           gint* result_length1);
VALA_EXTERN void agenda_task_view_toggle_selected_task (AgendaTaskView* self);
VALA_EXTERN gboolean agenda_task_list_is_empty (AgendaTaskList* self);
static void agenda_agenda_window_show_welcome (AgendaAgendaWindow* self);
static void agenda_agenda_window_hide_welcome (AgendaAgendaWindow* self);
static gboolean agenda_agenda_window_real_configure_event (GtkWidget* base,
                                                    GdkEventConfigure* event);
static gboolean __lambda12_ (AgendaAgendaWindow* self);
static GVariant* _variant_new1 (gint* value,
                         gint value_length1);
static GVariant* _variant_new2 (gint* value,
                         gint value_length1);
static gboolean ___lambda12__gsource_func (gpointer self);
static void agenda_agenda_window_finalize (GObject * obj);
static GType agenda_agenda_window_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
agenda_agenda_window_get_instance_private (AgendaAgendaWindow* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaAgendaWindow_private_offset);
}

static void
_gtk_window_close_g_simple_action_activate (GSimpleAction* _sender,
                                            GVariant* parameter,
                                            gpointer self)
{
#line 106 "../src/Window.vala"
	gtk_window_close ((GtkWindow*) self);
#line 302 "Window.c"
}

static void
_agenda_task_list_undo_g_simple_action_activate (GSimpleAction* _sender,
                                                 GVariant* parameter,
                                                 gpointer self)
{
#line 108 "../src/Window.vala"
	agenda_task_list_undo ((AgendaTaskList*) self);
#line 312 "Window.c"
}

static void
_agenda_task_list_redo_g_simple_action_activate (GSimpleAction* _sender,
                                                 GVariant* parameter,
                                                 gpointer self)
{
#line 109 "../src/Window.vala"
	agenda_task_list_redo ((AgendaTaskList*) self);
#line 322 "Window.c"
}

AgendaAgendaWindow*
agenda_agenda_window_construct (GType object_type,
                                AgendaAgenda* app)
{
	AgendaAgendaWindow * self = NULL;
	GSimpleAction* window_close_action = NULL;
	GSimpleAction* _tmp0_;
	GSimpleAction* app_quit_action = NULL;
	GSimpleAction* _tmp1_;
	GSimpleAction* undo_action = NULL;
	GSimpleAction* _tmp2_;
	GSimpleAction* redo_action = NULL;
	GSimpleAction* _tmp3_;
	GSimpleAction* _tmp4_;
	GSimpleAction* _tmp5_;
	GSimpleAction* _tmp6_;
	GSimpleAction* _tmp7_;
	gchar* _tmp8_;
	gchar** _tmp9_;
	gchar** _tmp10_;
	gint _tmp10__length1;
	gchar* _tmp11_;
	gchar** _tmp12_;
	gchar** _tmp13_;
	gint _tmp13__length1;
	gchar* _tmp14_;
	gchar** _tmp15_;
	gchar** _tmp16_;
	gint _tmp16__length1;
	gchar* _tmp17_;
	gchar** _tmp18_;
	gchar** _tmp19_;
	gint _tmp19__length1;
	GtkStyleContext* _tmp20_;
	GtkHeaderBar* header = NULL;
	GtkHeaderBar* _tmp21_;
	GtkHeaderBar* _tmp22_;
	GtkHeaderBar* _tmp23_;
	GtkStyleContext* _tmp24_;
	GtkHeaderBar* _tmp25_;
	GtkStyleContext* _tmp26_;
	GtkHeaderBar* _tmp27_;
	GdkGeometry geo = {0};
	GdkGeometry _tmp28_;
	gboolean first = FALSE;
	GSettings* _tmp29_;
	const gchar* _tmp30_ = NULL;
	GraniteWidgetsWelcome* _tmp31_;
	AgendaTaskList* _tmp32_;
	AgendaTaskList* _tmp33_;
	AgendaTaskView* _tmp34_;
	GtkScrolledWindow* _tmp35_;
	GtkEntry* _tmp36_;
	AgendaHistoryList* _tmp37_;
	AgendaFileBackend* _tmp39_;
	GSimpleAction* _tmp40_;
	GSimpleAction* _tmp41_;
	GSimpleAction* _tmp42_;
	AgendaTaskList* _tmp43_;
	GSimpleAction* _tmp44_;
	AgendaTaskList* _tmp45_;
#line 45 "../src/Window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 46 "../src/Window.vala"
	self = (AgendaAgendaWindow*) g_object_new (object_type, "application", app, NULL);
#line 48 "../src/Window.vala"
	_tmp0_ = g_simple_action_new ("close", NULL);
#line 48 "../src/Window.vala"
	window_close_action = _tmp0_;
#line 49 "../src/Window.vala"
	_tmp1_ = g_simple_action_new ("quit", NULL);
#line 49 "../src/Window.vala"
	app_quit_action = _tmp1_;
#line 50 "../src/Window.vala"
	_tmp2_ = g_simple_action_new ("undo", NULL);
#line 50 "../src/Window.vala"
	undo_action = _tmp2_;
#line 51 "../src/Window.vala"
	_tmp3_ = g_simple_action_new ("redo", NULL);
#line 51 "../src/Window.vala"
	redo_action = _tmp3_;
#line 53 "../src/Window.vala"
	_tmp4_ = window_close_action;
#line 53 "../src/Window.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp4_);
#line 54 "../src/Window.vala"
	_tmp5_ = app_quit_action;
#line 54 "../src/Window.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp5_);
#line 55 "../src/Window.vala"
	_tmp6_ = undo_action;
#line 55 "../src/Window.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp6_);
#line 56 "../src/Window.vala"
	_tmp7_ = redo_action;
#line 56 "../src/Window.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp7_);
#line 58 "../src/Window.vala"
	_tmp8_ = g_strdup ("<Ctrl>W");
#line 58 "../src/Window.vala"
	_tmp9_ = g_new0 (gchar*, 1 + 1);
#line 58 "../src/Window.vala"
	_tmp9_[0] = _tmp8_;
#line 58 "../src/Window.vala"
	_tmp10_ = _tmp9_;
#line 58 "../src/Window.vala"
	_tmp10__length1 = 1;
#line 58 "../src/Window.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) app, "win.close", _tmp10_);
#line 58 "../src/Window.vala"
	_tmp10_ = (_vala_array_free (_tmp10_, _tmp10__length1, (GDestroyNotify) g_free), NULL);
#line 59 "../src/Window.vala"
	_tmp11_ = g_strdup ("<Ctrl>Q");
#line 59 "../src/Window.vala"
	_tmp12_ = g_new0 (gchar*, 1 + 1);
#line 59 "../src/Window.vala"
	_tmp12_[0] = _tmp11_;
#line 59 "../src/Window.vala"
	_tmp13_ = _tmp12_;
#line 59 "../src/Window.vala"
	_tmp13__length1 = 1;
#line 59 "../src/Window.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) app, "win.quit", _tmp13_);
#line 59 "../src/Window.vala"
	_tmp13_ = (_vala_array_free (_tmp13_, _tmp13__length1, (GDestroyNotify) g_free), NULL);
#line 60 "../src/Window.vala"
	_tmp14_ = g_strdup ("<Ctrl>Z");
#line 60 "../src/Window.vala"
	_tmp15_ = g_new0 (gchar*, 1 + 1);
#line 60 "../src/Window.vala"
	_tmp15_[0] = _tmp14_;
#line 60 "../src/Window.vala"
	_tmp16_ = _tmp15_;
#line 60 "../src/Window.vala"
	_tmp16__length1 = 1;
#line 60 "../src/Window.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) app, "win.undo", _tmp16_);
#line 60 "../src/Window.vala"
	_tmp16_ = (_vala_array_free (_tmp16_, _tmp16__length1, (GDestroyNotify) g_free), NULL);
#line 61 "../src/Window.vala"
	_tmp17_ = g_strdup ("<Ctrl>Y");
#line 61 "../src/Window.vala"
	_tmp18_ = g_new0 (gchar*, 1 + 1);
#line 61 "../src/Window.vala"
	_tmp18_[0] = _tmp17_;
#line 61 "../src/Window.vala"
	_tmp19_ = _tmp18_;
#line 61 "../src/Window.vala"
	_tmp19__length1 = 1;
#line 61 "../src/Window.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) app, "win.redo", _tmp19_);
#line 61 "../src/Window.vala"
	_tmp19_ = (_vala_array_free (_tmp19_, _tmp19__length1, (GDestroyNotify) g_free), NULL);
#line 63 "../src/Window.vala"
	_tmp20_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 63 "../src/Window.vala"
	gtk_style_context_add_class (_tmp20_, "rounded");
#line 64 "../src/Window.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, AGENDA_MIN_WIDTH, AGENDA_MIN_HEIGHT);
#line 66 "../src/Window.vala"
	_tmp21_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 66 "../src/Window.vala"
	g_object_ref_sink (_tmp21_);
#line 66 "../src/Window.vala"
	header = _tmp21_;
#line 67 "../src/Window.vala"
	_tmp22_ = header;
#line 67 "../src/Window.vala"
	gtk_header_bar_set_show_close_button (_tmp22_, TRUE);
#line 68 "../src/Window.vala"
	_tmp23_ = header;
#line 68 "../src/Window.vala"
	_tmp24_ = gtk_widget_get_style_context ((GtkWidget*) _tmp23_);
#line 68 "../src/Window.vala"
	gtk_style_context_add_class (_tmp24_, "titlebar");
#line 69 "../src/Window.vala"
	_tmp25_ = header;
#line 69 "../src/Window.vala"
	_tmp26_ = gtk_widget_get_style_context ((GtkWidget*) _tmp25_);
#line 69 "../src/Window.vala"
	gtk_style_context_add_class (_tmp26_, GTK_STYLE_CLASS_FLAT);
#line 70 "../src/Window.vala"
	_tmp27_ = header;
#line 70 "../src/Window.vala"
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp27_);
#line 73 "../src/Window.vala"
	memset (&geo, 0, sizeof (GdkGeometry));
#line 74 "../src/Window.vala"
	geo.min_width = AGENDA_MIN_WIDTH;
#line 75 "../src/Window.vala"
	geo.min_height = AGENDA_MIN_HEIGHT;
#line 76 "../src/Window.vala"
	geo.max_width = 1024;
#line 77 "../src/Window.vala"
	geo.max_height = 2048;
#line 79 "../src/Window.vala"
	_tmp28_ = geo;
#line 79 "../src/Window.vala"
	gtk_window_set_geometry_hints ((GtkWindow*) self, NULL, &_tmp28_, GDK_HINT_MIN_SIZE | GDK_HINT_MAX_SIZE);
#line 84 "../src/Window.vala"
	agenda_agenda_window_restore_window_position (self);
#line 86 "../src/Window.vala"
	_tmp29_ = agenda_agenda_settings;
#line 86 "../src/Window.vala"
	first = g_settings_get_boolean (_tmp29_, "first-time");
#line 89 "../src/Window.vala"
	if (first) {
#line 89 "../src/Window.vala"
		_tmp30_ = _ ("(add one below)");
#line 534 "Window.c"
	} else {
#line 89 "../src/Window.vala"
		_tmp30_ = _ ("(way to go)");
#line 538 "Window.c"
	}
#line 87 "../src/Window.vala"
	_tmp31_ = granite_widgets_welcome_new (_ ("No Tasks!"), _tmp30_);
#line 87 "../src/Window.vala"
	g_object_ref_sink (_tmp31_);
#line 87 "../src/Window.vala"
	_g_object_unref0 (self->priv->agenda_welcome);
#line 87 "../src/Window.vala"
	self->priv->agenda_welcome = _tmp31_;
#line 90 "../src/Window.vala"
	_tmp32_ = agenda_task_list_new ();
#line 90 "../src/Window.vala"
	_g_object_unref0 (self->priv->task_list);
#line 90 "../src/Window.vala"
	self->priv->task_list = _tmp32_;
#line 91 "../src/Window.vala"
	_tmp33_ = self->priv->task_list;
#line 91 "../src/Window.vala"
	_tmp34_ = agenda_task_view_new_with_list (_tmp33_);
#line 91 "../src/Window.vala"
	g_object_ref_sink (_tmp34_);
#line 91 "../src/Window.vala"
	_g_object_unref0 (self->priv->task_view);
#line 91 "../src/Window.vala"
	self->priv->task_view = _tmp34_;
#line 92 "../src/Window.vala"
	_tmp35_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 92 "../src/Window.vala"
	g_object_ref_sink (_tmp35_);
#line 92 "../src/Window.vala"
	_g_object_unref0 (self->priv->scrolled_window);
#line 92 "../src/Window.vala"
	self->priv->scrolled_window = _tmp35_;
#line 93 "../src/Window.vala"
	_tmp36_ = (GtkEntry*) gtk_entry_new ();
#line 93 "../src/Window.vala"
	g_object_ref_sink (_tmp36_);
#line 93 "../src/Window.vala"
	_g_object_unref0 (self->priv->task_entry);
#line 93 "../src/Window.vala"
	self->priv->task_entry = _tmp36_;
#line 95 "../src/Window.vala"
	_tmp37_ = agenda_history_list_new ();
#line 95 "../src/Window.vala"
	_g_object_unref0 (self->priv->history_list);
#line 95 "../src/Window.vala"
	self->priv->history_list = _tmp37_;
#line 97 "../src/Window.vala"
	if (first) {
#line 588 "Window.c"
		GSettings* _tmp38_;
#line 98 "../src/Window.vala"
		_tmp38_ = agenda_agenda_settings;
#line 98 "../src/Window.vala"
		g_settings_set_boolean (_tmp38_, "first-time", FALSE);
#line 594 "Window.c"
	}
#line 101 "../src/Window.vala"
	_tmp39_ = agenda_file_backend_new ();
#line 101 "../src/Window.vala"
	_g_object_unref0 (self->priv->backend);
#line 101 "../src/Window.vala"
	self->priv->backend = _tmp39_;
#line 103 "../src/Window.vala"
	agenda_agenda_window_load_list (self);
#line 104 "../src/Window.vala"
	agenda_agenda_window_setup_ui (self);
#line 106 "../src/Window.vala"
	_tmp40_ = window_close_action;
#line 106 "../src/Window.vala"
	g_signal_connect_object (_tmp40_, "activate", (GCallback) _gtk_window_close_g_simple_action_activate, (GtkWindow*) self, 0);
#line 107 "../src/Window.vala"
	_tmp41_ = app_quit_action;
#line 107 "../src/Window.vala"
	g_signal_connect_object (_tmp41_, "activate", (GCallback) _gtk_window_close_g_simple_action_activate, (GtkWindow*) self, 0);
#line 108 "../src/Window.vala"
	_tmp42_ = undo_action;
#line 108 "../src/Window.vala"
	_tmp43_ = self->priv->task_list;
#line 108 "../src/Window.vala"
	g_signal_connect_object (_tmp42_, "activate", (GCallback) _agenda_task_list_undo_g_simple_action_activate, _tmp43_, 0);
#line 109 "../src/Window.vala"
	_tmp44_ = redo_action;
#line 109 "../src/Window.vala"
	_tmp45_ = self->priv->task_list;
#line 109 "../src/Window.vala"
	g_signal_connect_object (_tmp44_, "activate", (GCallback) _agenda_task_list_redo_g_simple_action_activate, _tmp45_, 0);
#line 45 "../src/Window.vala"
	_g_object_unref0 (header);
#line 45 "../src/Window.vala"
	_g_object_unref0 (redo_action);
#line 45 "../src/Window.vala"
	_g_object_unref0 (undo_action);
#line 45 "../src/Window.vala"
	_g_object_unref0 (app_quit_action);
#line 45 "../src/Window.vala"
	_g_object_unref0 (window_close_action);
#line 45 "../src/Window.vala"
	return self;
#line 638 "Window.c"
}

AgendaAgendaWindow*
agenda_agenda_window_new (AgendaAgenda* app)
{
#line 45 "../src/Window.vala"
	return agenda_agenda_window_construct (AGENDA_TYPE_AGENDA_WINDOW, app);
#line 646 "Window.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 116 "../src/Window.vala"
	return self ? g_object_ref (self) : NULL;
#line 654 "Window.c"
}

static void
agenda_agenda_window_load_list (AgendaAgendaWindow* self)
{
	AgendaTaskList* _tmp0_;
	AgendaTask** tasks = NULL;
	AgendaFileBackend* _tmp1_;
	gint _tmp2_ = 0;
	AgendaTask** _tmp3_;
	gint tasks_length1;
	gint _tasks_size_;
	AgendaTask** _tmp4_;
	gint _tmp4__length1;
	gchar** history = NULL;
	AgendaFileBackend* _tmp8_;
	gint _tmp9_ = 0;
	gchar** _tmp10_;
	gint history_length1;
	gint _history_size_;
	AgendaTaskList* _tmp15_;
	AgendaTaskList* _tmp16_;
#line 112 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 113 "../src/Window.vala"
	_tmp0_ = self->priv->task_list;
#line 113 "../src/Window.vala"
	agenda_task_list_disable_undo_recording (_tmp0_);
#line 115 "../src/Window.vala"
	_tmp1_ = self->priv->backend;
#line 115 "../src/Window.vala"
	_tmp3_ = agenda_backend_load_tasks ((AgendaBackend*) _tmp1_, &_tmp2_);
#line 115 "../src/Window.vala"
	tasks = _tmp3_;
#line 115 "../src/Window.vala"
	tasks_length1 = _tmp2_;
#line 115 "../src/Window.vala"
	_tasks_size_ = tasks_length1;
#line 116 "../src/Window.vala"
	_tmp4_ = tasks;
#line 116 "../src/Window.vala"
	_tmp4__length1 = tasks_length1;
#line 697 "Window.c"
	{
		AgendaTask** task_collection = NULL;
		gint task_collection_length1 = 0;
		gint _task_collection_size_ = 0;
		gint task_it = 0;
#line 116 "../src/Window.vala"
		task_collection = _tmp4_;
#line 116 "../src/Window.vala"
		task_collection_length1 = _tmp4__length1;
#line 116 "../src/Window.vala"
		for (task_it = 0; task_it < task_collection_length1; task_it = task_it + 1) {
#line 709 "Window.c"
			AgendaTask* _tmp5_;
			AgendaTask* task = NULL;
#line 116 "../src/Window.vala"
			_tmp5_ = _g_object_ref0 (task_collection[task_it]);
#line 116 "../src/Window.vala"
			task = _tmp5_;
#line 716 "Window.c"
			{
				AgendaTaskList* _tmp6_;
				AgendaTask* _tmp7_;
#line 117 "../src/Window.vala"
				_tmp6_ = self->priv->task_list;
#line 117 "../src/Window.vala"
				_tmp7_ = task;
#line 117 "../src/Window.vala"
				agenda_task_list_append_task (_tmp6_, _tmp7_);
#line 116 "../src/Window.vala"
				_g_object_unref0 (task);
#line 728 "Window.c"
			}
		}
	}
#line 120 "../src/Window.vala"
	_tmp8_ = self->priv->backend;
#line 120 "../src/Window.vala"
	_tmp10_ = agenda_backend_load_history ((AgendaBackend*) _tmp8_, &_tmp9_);
#line 120 "../src/Window.vala"
	history = _tmp10_;
#line 120 "../src/Window.vala"
	history_length1 = _tmp9_;
#line 120 "../src/Window.vala"
	_history_size_ = history_length1;
#line 121 "../src/Window.vala"
	if (agenda_agenda_window_privacy_mode_off (self)) {
#line 744 "Window.c"
		gchar** _tmp11_;
		gint _tmp11__length1;
#line 122 "../src/Window.vala"
		_tmp11_ = history;
#line 122 "../src/Window.vala"
		_tmp11__length1 = history_length1;
#line 751 "Window.c"
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
#line 122 "../src/Window.vala"
			line_collection = _tmp11_;
#line 122 "../src/Window.vala"
			line_collection_length1 = _tmp11__length1;
#line 122 "../src/Window.vala"
			for (line_it = 0; line_it < line_collection_length1; line_it = line_it + 1) {
#line 763 "Window.c"
				gchar* _tmp12_;
				gchar* line = NULL;
#line 122 "../src/Window.vala"
				_tmp12_ = g_strdup (line_collection[line_it]);
#line 122 "../src/Window.vala"
				line = _tmp12_;
#line 770 "Window.c"
				{
					AgendaHistoryList* _tmp13_;
					const gchar* _tmp14_;
#line 123 "../src/Window.vala"
					_tmp13_ = self->priv->history_list;
#line 123 "../src/Window.vala"
					_tmp14_ = line;
#line 123 "../src/Window.vala"
					agenda_history_list_add_item (_tmp13_, _tmp14_);
#line 122 "../src/Window.vala"
					_g_free0 (line);
#line 782 "Window.c"
				}
			}
		}
	}
#line 127 "../src/Window.vala"
	_tmp15_ = self->priv->task_list;
#line 127 "../src/Window.vala"
	agenda_task_list_enable_undo_recording (_tmp15_);
#line 128 "../src/Window.vala"
	_tmp16_ = self->priv->task_list;
#line 128 "../src/Window.vala"
	agenda_task_list_clear_undo (_tmp16_);
#line 112 "../src/Window.vala"
	history = (_vala_array_free (history, history_length1, (GDestroyNotify) g_free), NULL);
#line 112 "../src/Window.vala"
	tasks = (_vala_array_free (tasks, tasks_length1, (GDestroyNotify) g_object_unref), NULL);
#line 799 "Window.c"
}

static void
_agenda_agenda_window_append_task_gtk_entry_activate (GtkEntry* _sender,
                                                      gpointer self)
{
#line 149 "../src/Window.vala"
	agenda_agenda_window_append_task ((AgendaAgendaWindow*) self);
#line 808 "Window.c"
}

static void
_agenda_agenda_window_append_task_gtk_entry_icon_press (GtkEntry* _sender,
                                                        GtkEntryIconPosition icon_pos,
                                                        GdkEvent* event,
                                                        gpointer self)
{
#line 150 "../src/Window.vala"
	agenda_agenda_window_append_task ((AgendaAgendaWindow*) self);
#line 819 "Window.c"
}

static void
__lambda7_ (AgendaAgendaWindow* self)
{
	gchar* str = NULL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
#line 153 "../src/Window.vala"
	_tmp0_ = self->priv->task_entry;
#line 153 "../src/Window.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 153 "../src/Window.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 153 "../src/Window.vala"
	str = _tmp2_;
#line 154 "../src/Window.vala"
	_tmp3_ = str;
#line 154 "../src/Window.vala"
	if (g_strcmp0 (_tmp3_, "") == 0) {
#line 842 "Window.c"
		GtkEntry* _tmp4_;
#line 155 "../src/Window.vala"
		_tmp4_ = self->priv->task_entry;
#line 155 "../src/Window.vala"
		gtk_entry_set_icon_from_icon_name (_tmp4_, GTK_ENTRY_ICON_SECONDARY, NULL);
#line 848 "Window.c"
	} else {
		GtkEntry* _tmp5_;
#line 158 "../src/Window.vala"
		_tmp5_ = self->priv->task_entry;
#line 158 "../src/Window.vala"
		gtk_entry_set_icon_from_icon_name (_tmp5_, GTK_ENTRY_ICON_SECONDARY, "list-add-symbolic");
#line 855 "Window.c"
	}
#line 152 "../src/Window.vala"
	_g_free0 (str);
#line 859 "Window.c"
}

static void
___lambda7__gtk_editable_changed (GtkEditable* _sender,
                                  gpointer self)
{
#line 152 "../src/Window.vala"
	__lambda7_ ((AgendaAgendaWindow*) self);
#line 868 "Window.c"
}

static void
__lambda9_ (AgendaAgendaWindow* self)
{
	AgendaHistoryList* _tmp0_;
#line 173 "../src/Window.vala"
	_tmp0_ = self->priv->history_list;
#line 173 "../src/Window.vala"
	gtk_list_store_clear ((GtkListStore*) _tmp0_);
#line 879 "Window.c"
}

static void
___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender,
                                    gpointer self)
{
#line 172 "../src/Window.vala"
	__lambda9_ ((AgendaAgendaWindow*) self);
#line 888 "Window.c"
}

static void
__lambda8_ (AgendaAgendaWindow* self,
            GtkMenu* menu)
{
	GtkTreeIter iter = {0};
	gboolean valid = FALSE;
	AgendaHistoryList* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_;
	GtkSeparatorMenuItem* separator = NULL;
	GtkSeparatorMenuItem* _tmp3_;
	GtkMenuItem* item_clear_history = NULL;
	GtkMenuItem* _tmp4_;
	GtkSeparatorMenuItem* _tmp5_;
	GtkMenuItem* _tmp6_;
	GtkMenuItem* _tmp7_;
#line 163 "../src/Window.vala"
	g_return_if_fail (menu != NULL);
#line 165 "../src/Window.vala"
	_tmp0_ = self->priv->history_list;
#line 165 "../src/Window.vala"
	_tmp2_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) _tmp0_, &_tmp1_);
#line 165 "../src/Window.vala"
	iter = _tmp1_;
#line 165 "../src/Window.vala"
	valid = _tmp2_;
#line 166 "../src/Window.vala"
	_tmp3_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
#line 166 "../src/Window.vala"
	g_object_ref_sink (_tmp3_);
#line 166 "../src/Window.vala"
	separator = _tmp3_;
#line 167 "../src/Window.vala"
	_tmp4_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("Clear history"));
#line 167 "../src/Window.vala"
	g_object_ref_sink (_tmp4_);
#line 167 "../src/Window.vala"
	item_clear_history = _tmp4_;
#line 169 "../src/Window.vala"
	_tmp5_ = separator;
#line 169 "../src/Window.vala"
	gtk_menu_shell_insert ((GtkMenuShell*) menu, (GtkWidget*) _tmp5_, 6);
#line 170 "../src/Window.vala"
	_tmp6_ = item_clear_history;
#line 170 "../src/Window.vala"
	gtk_menu_shell_insert ((GtkMenuShell*) menu, (GtkWidget*) _tmp6_, 7);
#line 172 "../src/Window.vala"
	_tmp7_ = item_clear_history;
#line 172 "../src/Window.vala"
	g_signal_connect_object (_tmp7_, "activate", (GCallback) ___lambda9__gtk_menu_item_activate, self, 0);
#line 176 "../src/Window.vala"
	if (valid) {
#line 943 "Window.c"
		GtkMenuItem* _tmp8_;
#line 177 "../src/Window.vala"
		_tmp8_ = item_clear_history;
#line 177 "../src/Window.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp8_, TRUE);
#line 949 "Window.c"
	} else {
		GtkMenuItem* _tmp9_;
#line 179 "../src/Window.vala"
		_tmp9_ = item_clear_history;
#line 179 "../src/Window.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp9_, FALSE);
#line 956 "Window.c"
	}
#line 182 "../src/Window.vala"
	gtk_widget_show_all ((GtkWidget*) menu);
#line 163 "../src/Window.vala"
	_g_object_unref0 (item_clear_history);
#line 163 "../src/Window.vala"
	_g_object_unref0 (separator);
#line 964 "Window.c"
}

static void
___lambda8__gtk_entry_populate_popup (GtkEntry* _sender,
                                      GtkMenu* popup,
                                      gpointer self)
{
#line 163 "../src/Window.vala"
	__lambda8_ ((AgendaAgendaWindow*) self, popup);
#line 974 "Window.c"
}

static gboolean
__lambda10_ (AgendaAgendaWindow* self,
             GdkEventFocus* e)
{
	GtkTreeSelection* selected = NULL;
	AgendaTaskView* _tmp0_;
	GtkTreeSelection* _tmp1_;
	GtkTreeSelection* _tmp2_;
	gboolean result = FALSE;
#line 185 "../src/Window.vala"
	g_return_val_if_fail (e != NULL, FALSE);
#line 187 "../src/Window.vala"
	_tmp0_ = self->priv->task_view;
#line 187 "../src/Window.vala"
	_tmp1_ = gtk_tree_view_get_selection ((GtkTreeView*) _tmp0_);
#line 187 "../src/Window.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 187 "../src/Window.vala"
	_g_object_unref0 (selected);
#line 187 "../src/Window.vala"
	selected = _tmp2_;
#line 188 "../src/Window.vala"
	gtk_tree_selection_unselect_all (selected);
#line 189 "../src/Window.vala"
	result = FALSE;
#line 189 "../src/Window.vala"
	_g_object_unref0 (selected);
#line 189 "../src/Window.vala"
	return result;
#line 1006 "Window.c"
}

static gboolean
___lambda10__gtk_widget_focus_out_event (GtkWidget* _sender,
                                         GdkEventFocus* event,
                                         gpointer self)
{
	gboolean result;
	result = __lambda10_ ((AgendaAgendaWindow*) self, event);
#line 185 "../src/Window.vala"
	return result;
#line 1018 "Window.c"
}

static void
__lambda11_ (AgendaAgendaWindow* self)
{
	AgendaFileBackend* _tmp0_;
	AgendaTaskList* _tmp1_;
	gint _tmp2_ = 0;
	AgendaTask** _tmp3_;
	AgendaTask** _tmp4_;
	gint _tmp4__length1;
#line 193 "../src/Window.vala"
	_tmp0_ = self->priv->backend;
#line 193 "../src/Window.vala"
	_tmp1_ = self->priv->task_list;
#line 193 "../src/Window.vala"
	_tmp3_ = agenda_task_list_get_all_tasks (_tmp1_, &_tmp2_);
#line 193 "../src/Window.vala"
	_tmp4_ = _tmp3_;
#line 193 "../src/Window.vala"
	_tmp4__length1 = _tmp2_;
#line 193 "../src/Window.vala"
	agenda_backend_save_tasks ((AgendaBackend*) _tmp0_, _tmp4_, (gint) _tmp2_);
#line 193 "../src/Window.vala"
	_tmp4_ = (_vala_array_free (_tmp4_, _tmp4__length1, (GDestroyNotify) g_object_unref), NULL);
#line 194 "../src/Window.vala"
	agenda_agenda_window_update (self);
#line 1046 "Window.c"
}

static void
___lambda11__agenda_task_list_list_changed (AgendaTaskList* _sender,
                                            gpointer self)
{
#line 192 "../src/Window.vala"
	__lambda11_ ((AgendaAgendaWindow*) self);
#line 1055 "Window.c"
}

static gboolean
_agenda_agenda_window_key_down_event_gtk_widget_key_press_event (GtkWidget* _sender,
                                                                 GdkEventKey* event,
                                                                 gpointer self)
{
	gboolean result;
	result = agenda_agenda_window_key_down_event ((AgendaAgendaWindow*) self, event);
#line 197 "../src/Window.vala"
	return result;
#line 1067 "Window.c"
}

static void
agenda_agenda_window_setup_ui (AgendaAgendaWindow* self)
{
	GtkEntry* _tmp0_;
	GtkEntry* _tmp1_;
	GtkStyleContext* _tmp2_;
	GtkEntry* _tmp3_;
	GtkEntry* _tmp4_;
	GtkEntry* _tmp5_;
	GtkEntry* _tmp6_;
	GtkEntry* _tmp7_;
	GtkEntryCompletion* completion = NULL;
	GtkEntryCompletion* _tmp8_;
	AgendaHistoryList* _tmp9_;
	GtkEntry* _tmp10_;
	GtkEntry* _tmp11_;
	GtkEntry* _tmp12_;
	GtkEntry* _tmp13_;
	GtkEntry* _tmp14_;
	AgendaTaskView* _tmp15_;
	AgendaTaskList* _tmp16_;
	AgendaTaskView* _tmp17_;
	GtkScrolledWindow* _tmp18_;
	GtkScrolledWindow* _tmp19_;
	GtkScrolledWindow* _tmp20_;
	AgendaTaskView* _tmp21_;
	GraniteWidgetsWelcome* _tmp22_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp23_;
	GraniteWidgetsWelcome* _tmp24_;
	GtkScrolledWindow* _tmp25_;
	GtkEntry* _tmp26_;
	GtkEntry* _tmp27_;
	GtkEntry* _tmp28_;
	GtkEntry* _tmp29_;
	GtkEntry* _tmp30_;
	GtkEntry* _tmp31_;
#line 131 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 132 "../src/Window.vala"
	gtk_window_set_title ((GtkWindow*) self, "Agenda");
#line 134 "../src/Window.vala"
	_tmp0_ = self->priv->task_entry;
#line 134 "../src/Window.vala"
	gtk_widget_set_name ((GtkWidget*) _tmp0_, "TaskEntry");
#line 135 "../src/Window.vala"
	_tmp1_ = self->priv->task_entry;
#line 135 "../src/Window.vala"
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) _tmp1_);
#line 135 "../src/Window.vala"
	gtk_style_context_add_class (_tmp2_, "task-entry");
#line 136 "../src/Window.vala"
	_tmp3_ = self->priv->task_entry;
#line 136 "../src/Window.vala"
	gtk_entry_set_placeholder_text (_tmp3_, AGENDA_HINT_STRING);
#line 137 "../src/Window.vala"
	_tmp4_ = self->priv->task_entry;
#line 137 "../src/Window.vala"
	gtk_entry_set_max_length (_tmp4_, 64);
#line 138 "../src/Window.vala"
	_tmp5_ = self->priv->task_entry;
#line 138 "../src/Window.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp5_, TRUE);
#line 139 "../src/Window.vala"
	_tmp6_ = self->priv->task_entry;
#line 139 "../src/Window.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp6_, GTK_ALIGN_START);
#line 140 "../src/Window.vala"
	_tmp7_ = self->priv->task_entry;
#line 140 "../src/Window.vala"
	gtk_entry_set_icon_tooltip_text (_tmp7_, GTK_ENTRY_ICON_SECONDARY, _ ("Add to list…"));
#line 143 "../src/Window.vala"
	_tmp8_ = gtk_entry_completion_new ();
#line 143 "../src/Window.vala"
	completion = _tmp8_;
#line 144 "../src/Window.vala"
	_tmp9_ = self->priv->history_list;
#line 144 "../src/Window.vala"
	gtk_entry_completion_set_model (completion, (GtkTreeModel*) _tmp9_);
#line 145 "../src/Window.vala"
	gtk_entry_completion_set_text_column (completion, 0);
#line 147 "../src/Window.vala"
	_tmp10_ = self->priv->task_entry;
#line 147 "../src/Window.vala"
	gtk_entry_set_completion (_tmp10_, completion);
#line 149 "../src/Window.vala"
	_tmp11_ = self->priv->task_entry;
#line 149 "../src/Window.vala"
	g_signal_connect_object (_tmp11_, "activate", (GCallback) _agenda_agenda_window_append_task_gtk_entry_activate, self, 0);
#line 150 "../src/Window.vala"
	_tmp12_ = self->priv->task_entry;
#line 150 "../src/Window.vala"
	g_signal_connect_object (_tmp12_, "icon-press", (GCallback) _agenda_agenda_window_append_task_gtk_entry_icon_press, self, 0);
#line 152 "../src/Window.vala"
	_tmp13_ = self->priv->task_entry;
#line 152 "../src/Window.vala"
	g_signal_connect_object ((GtkEditable*) _tmp13_, "changed", (GCallback) ___lambda7__gtk_editable_changed, self, 0);
#line 163 "../src/Window.vala"
	_tmp14_ = self->priv->task_entry;
#line 163 "../src/Window.vala"
	g_signal_connect_object (_tmp14_, "populate-popup", (GCallback) ___lambda8__gtk_entry_populate_popup, self, 0);
#line 185 "../src/Window.vala"
	_tmp15_ = self->priv->task_view;
#line 185 "../src/Window.vala"
	g_signal_connect_object ((GtkWidget*) _tmp15_, "focus-out-event", (GCallback) ___lambda10__gtk_widget_focus_out_event, self, 0);
#line 192 "../src/Window.vala"
	_tmp16_ = self->priv->task_list;
#line 192 "../src/Window.vala"
	g_signal_connect_object (_tmp16_, "list-changed", (GCallback) ___lambda11__agenda_task_list_list_changed, self, 0);
#line 197 "../src/Window.vala"
	g_signal_connect_object ((GtkWidget*) self, "key-press-event", (GCallback) _agenda_agenda_window_key_down_event_gtk_widget_key_press_event, self, 0);
#line 199 "../src/Window.vala"
	_tmp17_ = self->priv->task_view;
#line 199 "../src/Window.vala"
	g_object_set ((GtkWidget*) _tmp17_, "expand", TRUE, NULL);
#line 200 "../src/Window.vala"
	_tmp18_ = self->priv->scrolled_window;
#line 200 "../src/Window.vala"
	g_object_set ((GtkWidget*) _tmp18_, "expand", TRUE, NULL);
#line 201 "../src/Window.vala"
	_tmp19_ = self->priv->scrolled_window;
#line 201 "../src/Window.vala"
	gtk_scrolled_window_set_policy (_tmp19_, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
#line 203 "../src/Window.vala"
	_tmp20_ = self->priv->scrolled_window;
#line 203 "../src/Window.vala"
	_tmp21_ = self->priv->task_view;
#line 203 "../src/Window.vala"
	gtk_container_add ((GtkContainer*) _tmp20_, (GtkWidget*) _tmp21_);
#line 205 "../src/Window.vala"
	_tmp22_ = self->priv->agenda_welcome;
#line 205 "../src/Window.vala"
	g_object_set ((GtkWidget*) _tmp22_, "expand", TRUE, NULL);
#line 207 "../src/Window.vala"
	_tmp23_ = (GtkGrid*) gtk_grid_new ();
#line 207 "../src/Window.vala"
	g_object_ref_sink (_tmp23_);
#line 207 "../src/Window.vala"
	grid = _tmp23_;
#line 208 "../src/Window.vala"
	g_object_set ((GtkWidget*) grid, "expand", TRUE, NULL);
#line 209 "../src/Window.vala"
	gtk_grid_set_row_homogeneous (grid, FALSE);
#line 210 "../src/Window.vala"
	_tmp24_ = self->priv->agenda_welcome;
#line 210 "../src/Window.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp24_, 0, 0, 1, 1);
#line 211 "../src/Window.vala"
	_tmp25_ = self->priv->scrolled_window;
#line 211 "../src/Window.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp25_, 0, 1, 1, 1);
#line 212 "../src/Window.vala"
	_tmp26_ = self->priv->task_entry;
#line 212 "../src/Window.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp26_, 0, 2, 1, 1);
#line 214 "../src/Window.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) grid);
#line 216 "../src/Window.vala"
	_tmp27_ = self->priv->task_entry;
#line 216 "../src/Window.vala"
	gtk_widget_set_margin_start ((GtkWidget*) _tmp27_, 10);
#line 217 "../src/Window.vala"
	_tmp28_ = self->priv->task_entry;
#line 217 "../src/Window.vala"
	gtk_widget_set_margin_end ((GtkWidget*) _tmp28_, 10);
#line 218 "../src/Window.vala"
	_tmp29_ = self->priv->task_entry;
#line 218 "../src/Window.vala"
	gtk_widget_set_margin_top ((GtkWidget*) _tmp29_, 10);
#line 219 "../src/Window.vala"
	_tmp30_ = self->priv->task_entry;
#line 219 "../src/Window.vala"
	gtk_widget_set_margin_bottom ((GtkWidget*) _tmp30_, 10);
#line 221 "../src/Window.vala"
	_tmp31_ = self->priv->task_entry;
#line 221 "../src/Window.vala"
	gtk_widget_grab_focus ((GtkWidget*) _tmp31_);
#line 131 "../src/Window.vala"
	_g_object_unref0 (grid);
#line 131 "../src/Window.vala"
	_g_object_unref0 (completion);
#line 1251 "Window.c"
}

void
agenda_agenda_window_append_task (AgendaAgendaWindow* self)
{
	AgendaTask* task = NULL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	AgendaTask* _tmp3_;
	AgendaTaskList* _tmp4_;
	AgendaHistoryList* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	GtkEntry* _tmp8_;
#line 224 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 225 "../src/Window.vala"
	_tmp0_ = self->priv->task_entry;
#line 225 "../src/Window.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 225 "../src/Window.vala"
	_tmp2_ = _tmp1_;
#line 225 "../src/Window.vala"
	_tmp3_ = agenda_task_new_with_attributes ("", FALSE, _tmp2_);
#line 225 "../src/Window.vala"
	task = _tmp3_;
#line 230 "../src/Window.vala"
	_tmp4_ = self->priv->task_list;
#line 230 "../src/Window.vala"
	agenda_task_list_append_task (_tmp4_, task);
#line 231 "../src/Window.vala"
	_tmp5_ = self->priv->history_list;
#line 231 "../src/Window.vala"
	_tmp6_ = agenda_task_get_text (task);
#line 231 "../src/Window.vala"
	_tmp7_ = _tmp6_;
#line 231 "../src/Window.vala"
	agenda_history_list_add_item (_tmp5_, _tmp7_);
#line 232 "../src/Window.vala"
	_tmp8_ = self->priv->task_entry;
#line 232 "../src/Window.vala"
	gtk_entry_set_text (_tmp8_, "");
#line 224 "../src/Window.vala"
	_g_object_unref0 (task);
#line 1297 "Window.c"
}

gboolean
agenda_agenda_window_privacy_mode_off (AgendaAgendaWindow* self)
{
	gboolean remember_app_usage = FALSE;
	GSettings* _tmp0_;
	gboolean remember_recent_files = FALSE;
	GSettings* _tmp1_;
	gboolean _tmp2_ = FALSE;
	gboolean result = FALSE;
#line 235 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 236 "../src/Window.vala"
	_tmp0_ = self->priv->privacy_setting;
#line 236 "../src/Window.vala"
	remember_app_usage = g_settings_get_boolean (_tmp0_, "remember-app-usage");
#line 237 "../src/Window.vala"
	_tmp1_ = self->priv->privacy_setting;
#line 237 "../src/Window.vala"
	remember_recent_files = g_settings_get_boolean (_tmp1_, "remember-recent-files");
#line 239 "../src/Window.vala"
	if (remember_app_usage) {
#line 239 "../src/Window.vala"
		_tmp2_ = TRUE;
#line 1323 "Window.c"
	} else {
#line 239 "../src/Window.vala"
		_tmp2_ = remember_recent_files;
#line 1327 "Window.c"
	}
#line 239 "../src/Window.vala"
	result = _tmp2_;
#line 239 "../src/Window.vala"
	return result;
#line 1333 "Window.c"
}

static gint
_variant_get1 (GVariant* value)
{
#line 247 "../src/Window.vala"
	return g_variant_get_int32 (value);
#line 1341 "Window.c"
}

static gint
_variant_get2 (GVariant* value)
{
#line 248 "../src/Window.vala"
	return g_variant_get_int32 (value);
#line 1349 "Window.c"
}

static gint
_variant_get3 (GVariant* value)
{
#line 259 "../src/Window.vala"
	return g_variant_get_int32 (value);
#line 1357 "Window.c"
}

static gint
_variant_get4 (GVariant* value)
{
#line 260 "../src/Window.vala"
	return g_variant_get_int32 (value);
#line 1365 "Window.c"
}

void
agenda_agenda_window_restore_window_position (AgendaAgendaWindow* self)
{
	GVariant* size = NULL;
	GSettings* _tmp0_;
	GVariant* _tmp1_;
	GVariant* position = NULL;
	GSettings* _tmp2_;
	GVariant* _tmp3_;
	GVariant* _tmp4_;
	GVariant* _tmp15_;
#line 242 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 243 "../src/Window.vala"
	_tmp0_ = agenda_agenda_settings;
#line 243 "../src/Window.vala"
	_tmp1_ = g_settings_get_value (_tmp0_, "window-size");
#line 243 "../src/Window.vala"
	size = _tmp1_;
#line 244 "../src/Window.vala"
	_tmp2_ = agenda_agenda_settings;
#line 244 "../src/Window.vala"
	_tmp3_ = g_settings_get_value (_tmp2_, "window-position");
#line 244 "../src/Window.vala"
	position = _tmp3_;
#line 246 "../src/Window.vala"
	_tmp4_ = position;
#line 246 "../src/Window.vala"
	if (g_variant_n_children (_tmp4_) == ((gsize) 2)) {
#line 1397 "Window.c"
		gint x = 0;
		GVariant* _tmp5_;
		GVariant* _tmp6_;
		GVariant* _tmp7_;
		gint _tmp8_;
		gint _tmp9_;
		gint y = 0;
		GVariant* _tmp10_;
		GVariant* _tmp11_;
		GVariant* _tmp12_;
		gint _tmp13_;
		gint _tmp14_;
#line 247 "../src/Window.vala"
		_tmp5_ = position;
#line 247 "../src/Window.vala"
		_tmp6_ = g_variant_get_child_value (_tmp5_, (gsize) 0);
#line 247 "../src/Window.vala"
		_tmp7_ = _tmp6_;
#line 247 "../src/Window.vala"
		_tmp8_ = _variant_get1 (_tmp7_);
#line 247 "../src/Window.vala"
		_tmp9_ = _tmp8_;
#line 247 "../src/Window.vala"
		_g_variant_unref0 (_tmp7_);
#line 247 "../src/Window.vala"
		x = _tmp9_;
#line 248 "../src/Window.vala"
		_tmp10_ = position;
#line 248 "../src/Window.vala"
		_tmp11_ = g_variant_get_child_value (_tmp10_, (gsize) 1);
#line 248 "../src/Window.vala"
		_tmp12_ = _tmp11_;
#line 248 "../src/Window.vala"
		_tmp13_ = _variant_get2 (_tmp12_);
#line 248 "../src/Window.vala"
		_tmp14_ = _tmp13_;
#line 248 "../src/Window.vala"
		_g_variant_unref0 (_tmp12_);
#line 248 "../src/Window.vala"
		y = _tmp14_;
#line 250 "../src/Window.vala"
		g_debug ("Window.vala:250: Moving window to coordinates %d, %d", x, y);
#line 251 "../src/Window.vala"
		gtk_window_move ((GtkWindow*) self, x, y);
#line 1442 "Window.c"
	} else {
#line 253 "../src/Window.vala"
		g_debug ("Window.vala:253: Moving window to the centre of the screen");
#line 254 "../src/Window.vala"
		g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
#line 1448 "Window.c"
	}
#line 257 "../src/Window.vala"
	_tmp15_ = size;
#line 257 "../src/Window.vala"
	if (g_variant_n_children (_tmp15_) == ((gsize) 2)) {
#line 1454 "Window.c"
		GtkAllocation rect = {0};
		GVariant* _tmp16_;
		GVariant* _tmp17_;
		GVariant* _tmp18_;
		gint _tmp19_;
		GVariant* _tmp20_;
		GVariant* _tmp21_;
		GVariant* _tmp22_;
		gint _tmp23_;
		GtkAllocation _tmp24_;
		GtkAllocation _tmp25_;
		GtkAllocation _tmp26_;
#line 258 "../src/Window.vala"
		memset (&rect, 0, sizeof (GtkAllocation));
#line 259 "../src/Window.vala"
		_tmp16_ = size;
#line 259 "../src/Window.vala"
		_tmp17_ = g_variant_get_child_value (_tmp16_, (gsize) 0);
#line 259 "../src/Window.vala"
		_tmp18_ = _tmp17_;
#line 259 "../src/Window.vala"
		_tmp19_ = _variant_get3 (_tmp18_);
#line 259 "../src/Window.vala"
		rect.width = _tmp19_;
#line 259 "../src/Window.vala"
		_g_variant_unref0 (_tmp18_);
#line 260 "../src/Window.vala"
		_tmp20_ = size;
#line 260 "../src/Window.vala"
		_tmp21_ = g_variant_get_child_value (_tmp20_, (gsize) 1);
#line 260 "../src/Window.vala"
		_tmp22_ = _tmp21_;
#line 260 "../src/Window.vala"
		_tmp23_ = _variant_get4 (_tmp22_);
#line 260 "../src/Window.vala"
		rect.height = _tmp23_;
#line 260 "../src/Window.vala"
		_g_variant_unref0 (_tmp22_);
#line 262 "../src/Window.vala"
		_tmp24_ = rect;
#line 262 "../src/Window.vala"
		_tmp25_ = rect;
#line 262 "../src/Window.vala"
		g_debug ("Window.vala:262: Resizing to width and height: %d, %d", _tmp24_.width, _tmp25_.height);
#line 263 "../src/Window.vala"
		_tmp26_ = rect;
#line 263 "../src/Window.vala"
		gtk_widget_set_allocation ((GtkWidget*) self, &_tmp26_);
#line 1503 "Window.c"
	} else {
#line 265 "../src/Window.vala"
		g_debug ("Window.vala:265: Not resizing window");
#line 1507 "Window.c"
	}
#line 242 "../src/Window.vala"
	_g_variant_unref0 (position);
#line 242 "../src/Window.vala"
	_g_variant_unref0 (size);
#line 1513 "Window.c"
}

gboolean
agenda_agenda_window_main_quit (AgendaAgendaWindow* self)
{
	AgendaFileBackend* _tmp0_;
	AgendaTaskList* _tmp1_;
	gint _tmp2_ = 0;
	AgendaTask** _tmp3_;
	AgendaTask** _tmp4_;
	gint _tmp4__length1;
	AgendaFileBackend* _tmp5_;
	AgendaHistoryList* _tmp6_;
	gint _tmp7_ = 0;
	gchar** _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gboolean result = FALSE;
#line 269 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 270 "../src/Window.vala"
	_tmp0_ = self->priv->backend;
#line 270 "../src/Window.vala"
	_tmp1_ = self->priv->task_list;
#line 270 "../src/Window.vala"
	_tmp3_ = agenda_task_list_get_all_tasks (_tmp1_, &_tmp2_);
#line 270 "../src/Window.vala"
	_tmp4_ = _tmp3_;
#line 270 "../src/Window.vala"
	_tmp4__length1 = _tmp2_;
#line 270 "../src/Window.vala"
	agenda_backend_save_tasks ((AgendaBackend*) _tmp0_, _tmp4_, (gint) _tmp2_);
#line 270 "../src/Window.vala"
	_tmp4_ = (_vala_array_free (_tmp4_, _tmp4__length1, (GDestroyNotify) g_object_unref), NULL);
#line 271 "../src/Window.vala"
	_tmp5_ = self->priv->backend;
#line 271 "../src/Window.vala"
	_tmp6_ = self->priv->history_list;
#line 271 "../src/Window.vala"
	_tmp8_ = agenda_history_list_get_all_tasks (_tmp6_, &_tmp7_);
#line 271 "../src/Window.vala"
	_tmp9_ = _tmp8_;
#line 271 "../src/Window.vala"
	_tmp9__length1 = _tmp7_;
#line 271 "../src/Window.vala"
	agenda_backend_save_history ((AgendaBackend*) _tmp5_, _tmp9_, (gint) _tmp7_);
#line 271 "../src/Window.vala"
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
#line 272 "../src/Window.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 274 "../src/Window.vala"
	result = FALSE;
#line 274 "../src/Window.vala"
	return result;
#line 1568 "Window.c"
}

gboolean
agenda_agenda_window_key_down_event (AgendaAgendaWindow* self,
                                     GdkEventKey* e)
{
	gboolean result = FALSE;
#line 277 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 277 "../src/Window.vala"
	g_return_val_if_fail (e != NULL, FALSE);
#line 278 "../src/Window.vala"
	switch (e->keyval) {
#line 278 "../src/Window.vala"
		case GDK_KEY_Escape:
#line 1584 "Window.c"
		{
			AgendaTaskView* _tmp0_;
#line 280 "../src/Window.vala"
			_tmp0_ = self->priv->task_view;
#line 280 "../src/Window.vala"
			if (!_tmp0_->is_editing) {
#line 281 "../src/Window.vala"
				agenda_agenda_window_main_quit (self);
#line 1593 "Window.c"
			}
#line 283 "../src/Window.vala"
			break;
#line 1597 "Window.c"
		}
#line 278 "../src/Window.vala"
		case GDK_KEY_Delete:
#line 1601 "Window.c"
		{
			gboolean _tmp1_ = FALSE;
			GtkEntry* _tmp2_;
			gboolean _tmp3_;
			gboolean _tmp4_;
#line 285 "../src/Window.vala"
			_tmp2_ = self->priv->task_entry;
#line 285 "../src/Window.vala"
			g_object_get ((GtkWidget*) _tmp2_, "has-focus", &_tmp3_, NULL);
#line 285 "../src/Window.vala"
			_tmp4_ = _tmp3_;
#line 285 "../src/Window.vala"
			if (!_tmp4_) {
#line 1615 "Window.c"
				AgendaTaskView* _tmp5_;
#line 285 "../src/Window.vala"
				_tmp5_ = self->priv->task_view;
#line 285 "../src/Window.vala"
				_tmp1_ = !_tmp5_->is_editing;
#line 1621 "Window.c"
			} else {
#line 285 "../src/Window.vala"
				_tmp1_ = FALSE;
#line 1625 "Window.c"
			}
#line 285 "../src/Window.vala"
			if (_tmp1_) {
#line 1629 "Window.c"
				AgendaTaskView* _tmp6_;
#line 286 "../src/Window.vala"
				_tmp6_ = self->priv->task_view;
#line 286 "../src/Window.vala"
				agenda_task_view_toggle_selected_task (_tmp6_);
#line 287 "../src/Window.vala"
				agenda_agenda_window_update (self);
#line 1637 "Window.c"
			}
#line 289 "../src/Window.vala"
			break;
#line 1641 "Window.c"
		}
		default:
#line 278 "../src/Window.vala"
		break;
#line 1646 "Window.c"
	}
#line 292 "../src/Window.vala"
	result = FALSE;
#line 292 "../src/Window.vala"
	return result;
#line 1652 "Window.c"
}

void
agenda_agenda_window_update (AgendaAgendaWindow* self)
{
	AgendaTaskList* _tmp0_;
#line 295 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 296 "../src/Window.vala"
	_tmp0_ = self->priv->task_list;
#line 296 "../src/Window.vala"
	if (agenda_task_list_is_empty (_tmp0_)) {
#line 297 "../src/Window.vala"
		agenda_agenda_window_show_welcome (self);
#line 1667 "Window.c"
	} else {
#line 299 "../src/Window.vala"
		agenda_agenda_window_hide_welcome (self);
#line 1671 "Window.c"
	}
}

static void
agenda_agenda_window_show_welcome (AgendaAgendaWindow* self)
{
	GtkScrolledWindow* _tmp0_;
	GraniteWidgetsWelcome* _tmp1_;
#line 302 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 303 "../src/Window.vala"
	_tmp0_ = self->priv->scrolled_window;
#line 303 "../src/Window.vala"
	gtk_widget_hide ((GtkWidget*) _tmp0_);
#line 304 "../src/Window.vala"
	_tmp1_ = self->priv->agenda_welcome;
#line 304 "../src/Window.vala"
	gtk_widget_show ((GtkWidget*) _tmp1_);
#line 1690 "Window.c"
}

static void
agenda_agenda_window_hide_welcome (AgendaAgendaWindow* self)
{
	GraniteWidgetsWelcome* _tmp0_;
	GtkScrolledWindow* _tmp1_;
#line 307 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 308 "../src/Window.vala"
	_tmp0_ = self->priv->agenda_welcome;
#line 308 "../src/Window.vala"
	gtk_widget_hide ((GtkWidget*) _tmp0_);
#line 309 "../src/Window.vala"
	_tmp1_ = self->priv->scrolled_window;
#line 309 "../src/Window.vala"
	gtk_widget_show ((GtkWidget*) _tmp1_);
#line 1708 "Window.c"
}

static GVariant*
_variant_new1 (gint* value,
               gint value_length1)
{
	gint* _tmp6_;
	GVariantBuilder _tmp7_;
	gint _tmp8_;
#line 327 "../src/Window.vala"
	_tmp6_ = value;
#line 327 "../src/Window.vala"
	g_variant_builder_init (&_tmp7_, G_VARIANT_TYPE ("ai"));
#line 327 "../src/Window.vala"
	for (_tmp8_ = 0; _tmp8_ < value_length1; _tmp8_++) {
#line 327 "../src/Window.vala"
		g_variant_builder_add_value (&_tmp7_, g_variant_new_int32 (*_tmp6_));
#line 327 "../src/Window.vala"
		_tmp6_++;
#line 1728 "Window.c"
	}
#line 327 "../src/Window.vala"
	return g_variant_ref_sink (g_variant_builder_end (&_tmp7_));
#line 1732 "Window.c"
}

static GVariant*
_variant_new2 (gint* value,
               gint value_length1)
{
	gint* _tmp17_;
	GVariantBuilder _tmp18_;
	gint _tmp19_;
#line 333 "../src/Window.vala"
	_tmp17_ = value;
#line 333 "../src/Window.vala"
	g_variant_builder_init (&_tmp18_, G_VARIANT_TYPE ("ai"));
#line 333 "../src/Window.vala"
	for (_tmp19_ = 0; _tmp19_ < value_length1; _tmp19_++) {
#line 333 "../src/Window.vala"
		g_variant_builder_add_value (&_tmp18_, g_variant_new_int32 (*_tmp17_));
#line 333 "../src/Window.vala"
		_tmp17_++;
#line 1752 "Window.c"
	}
#line 333 "../src/Window.vala"
	return g_variant_ref_sink (g_variant_builder_end (&_tmp18_));
#line 1756 "Window.c"
}

static gboolean
__lambda12_ (AgendaAgendaWindow* self)
{
	gint x = 0;
	gint y = 0;
	GdkRectangle rect = {0};
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	GtkAllocation _tmp2_ = {0};
	GSettings* _tmp3_;
	gint* _tmp4_;
	gint* _tmp5_;
	gint _tmp5__length1;
	GVariant* _tmp9_;
	GdkRectangle _tmp10_;
	GdkRectangle _tmp11_;
	GSettings* _tmp12_;
	GdkRectangle _tmp13_;
	GdkRectangle _tmp14_;
	gint* _tmp15_;
	gint* _tmp16_;
	gint _tmp16__length1;
	GVariant* _tmp20_;
	gboolean result = FALSE;
#line 318 "../src/Window.vala"
	self->priv->configure_id = (guint) 0;
#line 323 "../src/Window.vala"
	gtk_window_get_position ((GtkWindow*) self, &_tmp0_, &_tmp1_);
#line 323 "../src/Window.vala"
	x = _tmp0_;
#line 323 "../src/Window.vala"
	y = _tmp1_;
#line 324 "../src/Window.vala"
	gtk_widget_get_allocation ((GtkWidget*) self, &_tmp2_);
#line 324 "../src/Window.vala"
	rect = _tmp2_;
#line 326 "../src/Window.vala"
	g_debug ("Window.vala:326: Saving window position to %d, %d", x, y);
#line 327 "../src/Window.vala"
	_tmp3_ = agenda_agenda_settings;
#line 327 "../src/Window.vala"
	_tmp4_ = g_new0 (gint, 2);
#line 327 "../src/Window.vala"
	_tmp4_[0] = x;
#line 327 "../src/Window.vala"
	_tmp4_[1] = y;
#line 327 "../src/Window.vala"
	_tmp5_ = _tmp4_;
#line 327 "../src/Window.vala"
	_tmp5__length1 = 2;
#line 327 "../src/Window.vala"
	_tmp9_ = _variant_new1 (_tmp5_, 2);
#line 327 "../src/Window.vala"
	g_settings_set_value (_tmp3_, "window-position", _tmp9_);
#line 327 "../src/Window.vala"
	_g_variant_unref0 (_tmp9_);
#line 327 "../src/Window.vala"
	_tmp5_ = (g_free (_tmp5_), NULL);
#line 330 "../src/Window.vala"
	_tmp10_ = rect;
#line 330 "../src/Window.vala"
	_tmp11_ = rect;
#line 330 "../src/Window.vala"
	g_debug ("Window.vala:330: Saving window size of width and height: %d, %d", _tmp10_.width, _tmp11_.height);
#line 333 "../src/Window.vala"
	_tmp12_ = agenda_agenda_settings;
#line 333 "../src/Window.vala"
	_tmp13_ = rect;
#line 333 "../src/Window.vala"
	_tmp14_ = rect;
#line 333 "../src/Window.vala"
	_tmp15_ = g_new0 (gint, 2);
#line 333 "../src/Window.vala"
	_tmp15_[0] = _tmp13_.width;
#line 333 "../src/Window.vala"
	_tmp15_[1] = _tmp14_.height;
#line 333 "../src/Window.vala"
	_tmp16_ = _tmp15_;
#line 333 "../src/Window.vala"
	_tmp16__length1 = 2;
#line 333 "../src/Window.vala"
	_tmp20_ = _variant_new2 (_tmp16_, 2);
#line 333 "../src/Window.vala"
	g_settings_set_value (_tmp12_, "window-size", _tmp20_);
#line 333 "../src/Window.vala"
	_g_variant_unref0 (_tmp20_);
#line 333 "../src/Window.vala"
	_tmp16_ = (g_free (_tmp16_), NULL);
#line 336 "../src/Window.vala"
	result = FALSE;
#line 336 "../src/Window.vala"
	return result;
#line 1851 "Window.c"
}

static gboolean
___lambda12__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda12_ ((AgendaAgendaWindow*) self);
#line 317 "../src/Window.vala"
	return result;
#line 1861 "Window.c"
}

static gboolean
agenda_agenda_window_real_configure_event (GtkWidget* base,
                                           GdkEventConfigure* event)
{
	AgendaAgendaWindow * self;
	gboolean result = FALSE;
#line 312 "../src/Window.vala"
	self = (AgendaAgendaWindow*) base;
#line 312 "../src/Window.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 313 "../src/Window.vala"
	if (self->priv->configure_id != ((guint) 0)) {
#line 314 "../src/Window.vala"
		g_source_remove (self->priv->configure_id);
#line 1878 "Window.c"
	}
#line 317 "../src/Window.vala"
	self->priv->configure_id = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 100, ___lambda12__gsource_func, g_object_ref (self), g_object_unref);
#line 339 "../src/Window.vala"
	result = GTK_WIDGET_CLASS (agenda_agenda_window_parent_class)->configure_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_window_get_type (), GtkApplicationWindow), event);
#line 339 "../src/Window.vala"
	return result;
#line 1886 "Window.c"
}

static void
agenda_agenda_window_class_init (AgendaAgendaWindowClass * klass,
                                 gpointer klass_data)
{
#line 29 "../src/Window.vala"
	agenda_agenda_window_parent_class = g_type_class_peek_parent (klass);
#line 29 "../src/Window.vala"
	g_type_class_adjust_private_offset (klass, &AgendaAgendaWindow_private_offset);
#line 29 "../src/Window.vala"
	((GtkWidgetClass *) klass)->configure_event = (gboolean (*) (GtkWidget*, GdkEventConfigure*)) agenda_agenda_window_real_configure_event;
#line 29 "../src/Window.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_agenda_window_finalize;
#line 1901 "Window.c"
}

static void
agenda_agenda_window_instance_init (AgendaAgendaWindow * self,
                                    gpointer klass)
{
	GSettings* _tmp0_;
#line 29 "../src/Window.vala"
	self->priv = agenda_agenda_window_get_instance_private (self);
#line 33 "../src/Window.vala"
	_tmp0_ = g_settings_new ("org.gnome.desktop.privacy");
#line 33 "../src/Window.vala"
	self->priv->privacy_setting = _tmp0_;
#line 1915 "Window.c"
}

static void
agenda_agenda_window_finalize (GObject * obj)
{
	AgendaAgendaWindow * self;
#line 29 "../src/Window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_AGENDA_WINDOW, AgendaAgendaWindow);
#line 33 "../src/Window.vala"
	_g_object_unref0 (self->priv->privacy_setting);
#line 36 "../src/Window.vala"
	_g_object_unref0 (self->priv->backend);
#line 38 "../src/Window.vala"
	_g_object_unref0 (self->priv->agenda_welcome);
#line 39 "../src/Window.vala"
	_g_object_unref0 (self->priv->task_view);
#line 40 "../src/Window.vala"
	_g_object_unref0 (self->priv->task_list);
#line 41 "../src/Window.vala"
	_g_object_unref0 (self->priv->scrolled_window);
#line 42 "../src/Window.vala"
	_g_object_unref0 (self->priv->task_entry);
#line 43 "../src/Window.vala"
	_g_object_unref0 (self->priv->history_list);
#line 29 "../src/Window.vala"
	G_OBJECT_CLASS (agenda_agenda_window_parent_class)->finalize (obj);
#line 1942 "Window.c"
}

static GType
agenda_agenda_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaAgendaWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_agenda_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaAgendaWindow), 0, (GInstanceInitFunc) agenda_agenda_window_instance_init, NULL };
	GType agenda_agenda_window_type_id;
	agenda_agenda_window_type_id = g_type_register_static (gtk_application_window_get_type (), "AgendaAgendaWindow", &g_define_type_info, 0);
	AgendaAgendaWindow_private_offset = g_type_add_instance_private (agenda_agenda_window_type_id, sizeof (AgendaAgendaWindowPrivate));
	return agenda_agenda_window_type_id;
}

GType
agenda_agenda_window_get_type (void)
{
	static volatile gsize agenda_agenda_window_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_agenda_window_type_id__volatile)) {
		GType agenda_agenda_window_type_id;
		agenda_agenda_window_type_id = agenda_agenda_window_get_type_once ();
		g_once_init_leave (&agenda_agenda_window_type_id__volatile, agenda_agenda_window_type_id);
	}
	return agenda_agenda_window_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

