/* BackendInterface.c generated by valac 0.54.3, the Vala compiler
 * generated from BackendInterface.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_BACKEND (agenda_backend_get_type ())
#define AGENDA_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_BACKEND, AgendaBackend))
#define AGENDA_IS_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_BACKEND))
#define AGENDA_BACKEND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), AGENDA_TYPE_BACKEND, AgendaBackendIface))

typedef struct _AgendaBackend AgendaBackend;
typedef struct _AgendaBackendIface AgendaBackendIface;

#define AGENDA_TYPE_TASK (agenda_task_get_type ())
#define AGENDA_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK, AgendaTask))
#define AGENDA_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK, AgendaTaskClass))
#define AGENDA_IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK))
#define AGENDA_IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK))
#define AGENDA_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK, AgendaTaskClass))

typedef struct _AgendaTask AgendaTask;
typedef struct _AgendaTaskClass AgendaTaskClass;

struct _AgendaBackendIface {
	GTypeInterface parent_iface;
	AgendaTask** (*load_tasks) (AgendaBackend* self, gint* result_length1);
	gchar** (*load_history) (AgendaBackend* self, gint* result_length1);
	void (*save_tasks) (AgendaBackend* self, AgendaTask** tasks, gint tasks_length1);
	void (*save_history) (AgendaBackend* self, gchar** history, gint history_length1);
};

VALA_EXTERN GType agenda_task_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTask, g_object_unref)
VALA_EXTERN GType agenda_backend_get_type (void) G_GNUC_CONST ;
VALA_EXTERN AgendaTask** agenda_backend_load_tasks (AgendaBackend* self,
                                        gint* result_length1);
VALA_EXTERN gchar** agenda_backend_load_history (AgendaBackend* self,
                                     gint* result_length1);
VALA_EXTERN void agenda_backend_save_tasks (AgendaBackend* self,
                                AgendaTask** tasks,
                                gint tasks_length1);
VALA_EXTERN void agenda_backend_save_history (AgendaBackend* self,
                                  gchar** history,
                                  gint history_length1);
static GType agenda_backend_get_type_once (void);

AgendaTask**
agenda_backend_load_tasks (AgendaBackend* self,
                           gint* result_length1)
{
	AgendaBackendIface* _iface_;
#line 24 "../src/Backend/BackendInterface.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 24 "../src/Backend/BackendInterface.vala"
	_iface_ = AGENDA_BACKEND_GET_INTERFACE (self);
#line 24 "../src/Backend/BackendInterface.vala"
	if (_iface_->load_tasks) {
#line 24 "../src/Backend/BackendInterface.vala"
		return _iface_->load_tasks (self, result_length1);
#line 74 "BackendInterface.c"
	}
#line 24 "../src/Backend/BackendInterface.vala"
	return NULL;
#line 78 "BackendInterface.c"
}

gchar**
agenda_backend_load_history (AgendaBackend* self,
                             gint* result_length1)
{
	AgendaBackendIface* _iface_;
#line 25 "../src/Backend/BackendInterface.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "../src/Backend/BackendInterface.vala"
	_iface_ = AGENDA_BACKEND_GET_INTERFACE (self);
#line 25 "../src/Backend/BackendInterface.vala"
	if (_iface_->load_history) {
#line 25 "../src/Backend/BackendInterface.vala"
		return _iface_->load_history (self, result_length1);
#line 94 "BackendInterface.c"
	}
#line 25 "../src/Backend/BackendInterface.vala"
	return NULL;
#line 98 "BackendInterface.c"
}

void
agenda_backend_save_tasks (AgendaBackend* self,
                           AgendaTask** tasks,
                           gint tasks_length1)
{
	AgendaBackendIface* _iface_;
#line 26 "../src/Backend/BackendInterface.vala"
	g_return_if_fail (self != NULL);
#line 26 "../src/Backend/BackendInterface.vala"
	_iface_ = AGENDA_BACKEND_GET_INTERFACE (self);
#line 26 "../src/Backend/BackendInterface.vala"
	if (_iface_->save_tasks) {
#line 26 "../src/Backend/BackendInterface.vala"
		_iface_->save_tasks (self, tasks, tasks_length1);
#line 115 "BackendInterface.c"
	}
}

void
agenda_backend_save_history (AgendaBackend* self,
                             gchar** history,
                             gint history_length1)
{
	AgendaBackendIface* _iface_;
#line 27 "../src/Backend/BackendInterface.vala"
	g_return_if_fail (self != NULL);
#line 27 "../src/Backend/BackendInterface.vala"
	_iface_ = AGENDA_BACKEND_GET_INTERFACE (self);
#line 27 "../src/Backend/BackendInterface.vala"
	if (_iface_->save_history) {
#line 27 "../src/Backend/BackendInterface.vala"
		_iface_->save_history (self, history, history_length1);
#line 133 "BackendInterface.c"
	}
}

static void
agenda_backend_default_init (AgendaBackendIface * iface,
                             gpointer iface_data)
{
}

static GType
agenda_backend_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaBackendIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_backend_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType agenda_backend_type_id;
	agenda_backend_type_id = g_type_register_static (G_TYPE_INTERFACE, "AgendaBackend", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (agenda_backend_type_id, G_TYPE_OBJECT);
	return agenda_backend_type_id;
}

GType
agenda_backend_get_type (void)
{
	static volatile gsize agenda_backend_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_backend_type_id__volatile)) {
		GType agenda_backend_type_id;
		agenda_backend_type_id = agenda_backend_get_type_once ();
		g_once_init_leave (&agenda_backend_type_id__volatile, agenda_backend_type_id);
	}
	return agenda_backend_type_id__volatile;
}

