/* FileBackend.c generated by valac 0.54.3, the Vala compiler
 * generated from FileBackend.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define AGENDA_TYPE_BACKEND (agenda_backend_get_type ())
#define AGENDA_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_BACKEND, AgendaBackend))
#define AGENDA_IS_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_BACKEND))
#define AGENDA_BACKEND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), AGENDA_TYPE_BACKEND, AgendaBackendIface))

typedef struct _AgendaBackend AgendaBackend;
typedef struct _AgendaBackendIface AgendaBackendIface;

#define AGENDA_TYPE_TASK (agenda_task_get_type ())
#define AGENDA_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_TASK, AgendaTask))
#define AGENDA_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_TASK, AgendaTaskClass))
#define AGENDA_IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_TASK))
#define AGENDA_IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_TASK))
#define AGENDA_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_TASK, AgendaTaskClass))

typedef struct _AgendaTask AgendaTask;
typedef struct _AgendaTaskClass AgendaTaskClass;

#define AGENDA_TYPE_FILE_BACKEND (agenda_file_backend_get_type ())
#define AGENDA_FILE_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AGENDA_TYPE_FILE_BACKEND, AgendaFileBackend))
#define AGENDA_FILE_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AGENDA_TYPE_FILE_BACKEND, AgendaFileBackendClass))
#define AGENDA_IS_FILE_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AGENDA_TYPE_FILE_BACKEND))
#define AGENDA_IS_FILE_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AGENDA_TYPE_FILE_BACKEND))
#define AGENDA_FILE_BACKEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AGENDA_TYPE_FILE_BACKEND, AgendaFileBackendClass))

typedef struct _AgendaFileBackend AgendaFileBackend;
typedef struct _AgendaFileBackendClass AgendaFileBackendClass;
typedef struct _AgendaFileBackendPrivate AgendaFileBackendPrivate;
enum  {
	AGENDA_FILE_BACKEND_0_PROPERTY,
	AGENDA_FILE_BACKEND_NUM_PROPERTIES
};
static GParamSpec* agenda_file_backend_properties[AGENDA_FILE_BACKEND_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _AgendaBackendIface {
	GTypeInterface parent_iface;
	AgendaTask** (*load_tasks) (AgendaBackend* self, gint* result_length1);
	gchar** (*load_history) (AgendaBackend* self, gint* result_length1);
	void (*save_tasks) (AgendaBackend* self, AgendaTask** tasks, gint tasks_length1);
	void (*save_history) (AgendaBackend* self, gchar** history, gint history_length1);
};

struct _AgendaFileBackend {
	GObject parent_instance;
	AgendaFileBackendPrivate * priv;
};

struct _AgendaFileBackendClass {
	GObjectClass parent_class;
};

struct _AgendaFileBackendPrivate {
	GFile* task_file;
	GFile* history_file;
};

static gint AgendaFileBackend_private_offset;
static gpointer agenda_file_backend_parent_class = NULL;
static AgendaBackendIface * agenda_file_backend_agenda_backend_parent_iface = NULL;

VALA_EXTERN GType agenda_task_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaTask, g_object_unref)
VALA_EXTERN GType agenda_backend_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType agenda_file_backend_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AgendaFileBackend, g_object_unref)
VALA_EXTERN AgendaFileBackend* agenda_file_backend_new (void);
VALA_EXTERN AgendaFileBackend* agenda_file_backend_construct (GType object_type);
static gchar** agenda_file_backend_real_load_history (AgendaBackend* base,
                                               gint* result_length1);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static AgendaTask** agenda_file_backend_real_load_tasks (AgendaBackend* base,
                                                  gint* result_length1);
VALA_EXTERN AgendaTask* agenda_task_new (void);
VALA_EXTERN AgendaTask* agenda_task_construct (GType object_type);
VALA_EXTERN void agenda_task_set_text (AgendaTask* self,
                           const gchar* value);
VALA_EXTERN void agenda_task_set_complete (AgendaTask* self,
                               gboolean value);
static void _vala_array_add2 (AgendaTask** * array,
                       gint* length,
                       gint* size,
                       AgendaTask* value);
static void agenda_file_backend_real_save_history (AgendaBackend* base,
                                            gchar** history,
                                            gint history_length1);
static void agenda_file_backend_save_to_file (AgendaFileBackend* self,
                                       gchar** lines,
                                       gint lines_length1,
                                       GFile* file);
static void agenda_file_backend_real_save_tasks (AgendaBackend* base,
                                          AgendaTask** tasks,
                                          gint tasks_length1);
VALA_EXTERN gchar* agenda_task_to_string (AgendaTask* self);
static void _vala_array_add3 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
VALA_EXTERN gchar** agenda_backend_load_history (AgendaBackend* self,
                                     gint* result_length1);
VALA_EXTERN AgendaTask** agenda_backend_load_tasks (AgendaBackend* self,
                                        gint* result_length1);
VALA_EXTERN void agenda_backend_save_history (AgendaBackend* self,
                                  gchar** history,
                                  gint history_length1);
VALA_EXTERN void agenda_backend_save_tasks (AgendaBackend* self,
                                AgendaTask** tasks,
                                gint tasks_length1);
static void agenda_file_backend_finalize (GObject * obj);
static GType agenda_file_backend_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static inline gpointer
agenda_file_backend_get_instance_private (AgendaFileBackend* self)
{
	return G_STRUCT_MEMBER_P (self, AgendaFileBackend_private_offset);
}

AgendaFileBackend*
agenda_file_backend_construct (GType object_type)
{
	AgendaFileBackend * self = NULL;
	gchar* user_data = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	GFile* dir = NULL;
	GFile* _tmp2_;
	GFile* _tmp3_;
	GFile* _tmp4_;
	GFile* _tmp5_;
	GFile* _tmp11_;
	GFile* _tmp12_;
	GError* _inner_error0_ = NULL;
#line 28 "../src/Backend/FileBackend.vala"
	self = (AgendaFileBackend*) g_object_new (object_type, NULL);
#line 29 "../src/Backend/FileBackend.vala"
	_tmp0_ = g_get_user_data_dir ();
#line 29 "../src/Backend/FileBackend.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 29 "../src/Backend/FileBackend.vala"
	user_data = _tmp1_;
#line 31 "../src/Backend/FileBackend.vala"
	_tmp2_ = g_file_new_for_path (user_data);
#line 31 "../src/Backend/FileBackend.vala"
	_tmp3_ = _tmp2_;
#line 31 "../src/Backend/FileBackend.vala"
	_tmp4_ = g_file_get_child (_tmp3_, "agenda");
#line 31 "../src/Backend/FileBackend.vala"
	_tmp5_ = _tmp4_;
#line 31 "../src/Backend/FileBackend.vala"
	_g_object_unref0 (_tmp3_);
#line 31 "../src/Backend/FileBackend.vala"
	dir = _tmp5_;
#line 185 "FileBackend.c"
	{
#line 34 "../src/Backend/FileBackend.vala"
		g_file_make_directory_with_parents (dir, NULL, &_inner_error0_);
#line 34 "../src/Backend/FileBackend.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 191 "FileBackend.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp6_;
#line 33 "../src/Backend/FileBackend.vala"
		e = _inner_error0_;
#line 33 "../src/Backend/FileBackend.vala"
		_inner_error0_ = NULL;
#line 36 "../src/Backend/FileBackend.vala"
		_tmp6_ = e;
#line 36 "../src/Backend/FileBackend.vala"
		if (g_error_matches (_tmp6_, G_IO_ERROR, G_IO_ERROR_EXISTS)) {
#line 208 "FileBackend.c"
			GError* _tmp7_;
			const gchar* _tmp8_;
#line 37 "../src/Backend/FileBackend.vala"
			_tmp7_ = e;
#line 37 "../src/Backend/FileBackend.vala"
			_tmp8_ = _tmp7_->message;
#line 37 "../src/Backend/FileBackend.vala"
			g_info ("FileBackend.vala:37: %s", _tmp8_);
#line 217 "FileBackend.c"
		} else {
			gchar* _tmp9_;
			gchar* _tmp10_;
#line 39 "../src/Backend/FileBackend.vala"
			_tmp9_ = g_file_get_path (dir);
#line 39 "../src/Backend/FileBackend.vala"
			_tmp10_ = _tmp9_;
#line 39 "../src/Backend/FileBackend.vala"
			g_error ("FileBackend.vala:39: Could not access or create directory '%s'.", _tmp10_);
#line 39 "../src/Backend/FileBackend.vala"
			_g_free0 (_tmp10_);
#line 229 "FileBackend.c"
		}
#line 33 "../src/Backend/FileBackend.vala"
		_g_error_free0 (e);
#line 233 "FileBackend.c"
	}
	__finally0:
#line 33 "../src/Backend/FileBackend.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 33 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (dir);
#line 33 "../src/Backend/FileBackend.vala"
		_g_free0 (user_data);
#line 33 "../src/Backend/FileBackend.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 33 "../src/Backend/FileBackend.vala"
		g_clear_error (&_inner_error0_);
#line 33 "../src/Backend/FileBackend.vala"
		return NULL;
#line 248 "FileBackend.c"
	}
#line 44 "../src/Backend/FileBackend.vala"
	_tmp11_ = g_file_get_child (dir, "tasks");
#line 44 "../src/Backend/FileBackend.vala"
	_g_object_unref0 (self->priv->task_file);
#line 44 "../src/Backend/FileBackend.vala"
	self->priv->task_file = _tmp11_;
#line 45 "../src/Backend/FileBackend.vala"
	_tmp12_ = g_file_get_child (dir, "history");
#line 45 "../src/Backend/FileBackend.vala"
	_g_object_unref0 (self->priv->history_file);
#line 45 "../src/Backend/FileBackend.vala"
	self->priv->history_file = _tmp12_;
#line 28 "../src/Backend/FileBackend.vala"
	_g_object_unref0 (dir);
#line 28 "../src/Backend/FileBackend.vala"
	_g_free0 (user_data);
#line 28 "../src/Backend/FileBackend.vala"
	return self;
#line 268 "FileBackend.c"
}

AgendaFileBackend*
agenda_file_backend_new (void)
{
#line 28 "../src/Backend/FileBackend.vala"
	return agenda_file_backend_construct (AGENDA_TYPE_FILE_BACKEND);
#line 276 "FileBackend.c"
}

static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
#line 57 "../src/Backend/FileBackend.vala"
	if ((*length) == (*size)) {
#line 57 "../src/Backend/FileBackend.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 57 "../src/Backend/FileBackend.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 291 "FileBackend.c"
	}
#line 57 "../src/Backend/FileBackend.vala"
	(*array)[(*length)++] = value;
#line 57 "../src/Backend/FileBackend.vala"
	(*array)[*length] = NULL;
#line 297 "FileBackend.c"
}

static gchar**
agenda_file_backend_real_load_history (AgendaBackend* base,
                                       gint* result_length1)
{
	AgendaFileBackend * self;
	gchar** history = NULL;
	gchar** _tmp0_;
	gint history_length1;
	gint _history_size_;
	gchar** _tmp17_;
	gint _tmp17__length1;
	GError* _inner_error0_ = NULL;
	gchar** result = NULL;
#line 48 "../src/Backend/FileBackend.vala"
	self = (AgendaFileBackend*) base;
#line 49 "../src/Backend/FileBackend.vala"
	_tmp0_ = g_new0 (gchar*, 0 + 1);
#line 49 "../src/Backend/FileBackend.vala"
	history = _tmp0_;
#line 49 "../src/Backend/FileBackend.vala"
	history_length1 = 0;
#line 49 "../src/Backend/FileBackend.vala"
	_history_size_ = history_length1;
#line 323 "FileBackend.c"
	{
		gchar* line = NULL;
		GFileInputStream* file_input_stream = NULL;
		GFile* _tmp1_;
		GFileInputStream* _tmp2_;
		GDataInputStream* f_dis = NULL;
		GFileInputStream* _tmp3_;
		GDataInputStream* _tmp4_;
#line 53 "../src/Backend/FileBackend.vala"
		_tmp1_ = self->priv->history_file;
#line 53 "../src/Backend/FileBackend.vala"
		_tmp2_ = g_file_read (_tmp1_, NULL, &_inner_error0_);
#line 53 "../src/Backend/FileBackend.vala"
		file_input_stream = _tmp2_;
#line 53 "../src/Backend/FileBackend.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 53 "../src/Backend/FileBackend.vala"
			_g_free0 (line);
#line 342 "FileBackend.c"
			goto __catch0_g_error;
		}
#line 54 "../src/Backend/FileBackend.vala"
		_tmp3_ = file_input_stream;
#line 54 "../src/Backend/FileBackend.vala"
		_tmp4_ = g_data_input_stream_new ((GInputStream*) _tmp3_);
#line 54 "../src/Backend/FileBackend.vala"
		f_dis = _tmp4_;
#line 56 "../src/Backend/FileBackend.vala"
		while (TRUE) {
#line 353 "FileBackend.c"
			gchar* _tmp5_ = NULL;
			GDataInputStream* _tmp6_;
			gchar* _tmp7_;
			gchar* _tmp8_;
			const gchar* _tmp9_;
			const gchar* _tmp10_;
			gchar* _tmp11_;
#line 56 "../src/Backend/FileBackend.vala"
			_tmp6_ = f_dis;
#line 56 "../src/Backend/FileBackend.vala"
			_tmp7_ = g_data_input_stream_read_line (_tmp6_, NULL, NULL, &_inner_error0_);
#line 56 "../src/Backend/FileBackend.vala"
			_tmp5_ = _tmp7_;
#line 56 "../src/Backend/FileBackend.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 56 "../src/Backend/FileBackend.vala"
				_g_object_unref0 (f_dis);
#line 56 "../src/Backend/FileBackend.vala"
				_g_object_unref0 (file_input_stream);
#line 56 "../src/Backend/FileBackend.vala"
				_g_free0 (line);
#line 375 "FileBackend.c"
				goto __catch0_g_error;
			}
#line 56 "../src/Backend/FileBackend.vala"
			_tmp8_ = _tmp5_;
#line 56 "../src/Backend/FileBackend.vala"
			_tmp5_ = NULL;
#line 56 "../src/Backend/FileBackend.vala"
			_g_free0 (line);
#line 56 "../src/Backend/FileBackend.vala"
			line = _tmp8_;
#line 56 "../src/Backend/FileBackend.vala"
			_tmp9_ = line;
#line 56 "../src/Backend/FileBackend.vala"
			if (!(_tmp9_ != NULL)) {
#line 56 "../src/Backend/FileBackend.vala"
				_g_free0 (_tmp5_);
#line 56 "../src/Backend/FileBackend.vala"
				break;
#line 394 "FileBackend.c"
			}
#line 57 "../src/Backend/FileBackend.vala"
			_tmp10_ = line;
#line 57 "../src/Backend/FileBackend.vala"
			_tmp11_ = g_strdup (_tmp10_);
#line 57 "../src/Backend/FileBackend.vala"
			_vala_array_add1 (&history, &history_length1, &_history_size_, _tmp11_);
#line 56 "../src/Backend/FileBackend.vala"
			_g_free0 (_tmp5_);
#line 404 "FileBackend.c"
		}
#line 51 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (f_dis);
#line 51 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (file_input_stream);
#line 51 "../src/Backend/FileBackend.vala"
		_g_free0 (line);
#line 412 "FileBackend.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp12_;
#line 51 "../src/Backend/FileBackend.vala"
		e = _inner_error0_;
#line 51 "../src/Backend/FileBackend.vala"
		_inner_error0_ = NULL;
#line 60 "../src/Backend/FileBackend.vala"
		_tmp12_ = e;
#line 60 "../src/Backend/FileBackend.vala"
		if (g_error_matches (_tmp12_, G_IO_ERROR, G_IO_ERROR_NOT_FOUND)) {
#line 427 "FileBackend.c"
			GError* _tmp13_;
			const gchar* _tmp14_;
#line 61 "../src/Backend/FileBackend.vala"
			_tmp13_ = e;
#line 61 "../src/Backend/FileBackend.vala"
			_tmp14_ = _tmp13_->message;
#line 61 "../src/Backend/FileBackend.vala"
			g_info ("FileBackend.vala:61: %s", _tmp14_);
#line 436 "FileBackend.c"
		} else {
			GError* _tmp15_;
			const gchar* _tmp16_;
#line 63 "../src/Backend/FileBackend.vala"
			_tmp15_ = e;
#line 63 "../src/Backend/FileBackend.vala"
			_tmp16_ = _tmp15_->message;
#line 63 "../src/Backend/FileBackend.vala"
			g_error ("FileBackend.vala:63: %s", _tmp16_);
#line 446 "FileBackend.c"
		}
#line 51 "../src/Backend/FileBackend.vala"
		_g_error_free0 (e);
#line 450 "FileBackend.c"
	}
	__finally0:
#line 51 "../src/Backend/FileBackend.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 51 "../src/Backend/FileBackend.vala"
		history = (_vala_array_free (history, history_length1, (GDestroyNotify) g_free), NULL);
#line 51 "../src/Backend/FileBackend.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 51 "../src/Backend/FileBackend.vala"
		g_clear_error (&_inner_error0_);
#line 51 "../src/Backend/FileBackend.vala"
		return NULL;
#line 463 "FileBackend.c"
	}
#line 67 "../src/Backend/FileBackend.vala"
	_tmp17_ = history;
#line 67 "../src/Backend/FileBackend.vala"
	_tmp17__length1 = history_length1;
#line 67 "../src/Backend/FileBackend.vala"
	if (result_length1) {
#line 67 "../src/Backend/FileBackend.vala"
		*result_length1 = _tmp17__length1;
#line 473 "FileBackend.c"
	}
#line 67 "../src/Backend/FileBackend.vala"
	result = _tmp17_;
#line 67 "../src/Backend/FileBackend.vala"
	return result;
#line 479 "FileBackend.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 88 "../src/Backend/FileBackend.vala"
	return self ? g_object_ref (self) : NULL;
#line 487 "FileBackend.c"
}

static void
_vala_array_add2 (AgendaTask** * array,
                  gint* length,
                  gint* size,
                  AgendaTask* value)
{
#line 88 "../src/Backend/FileBackend.vala"
	if ((*length) == (*size)) {
#line 88 "../src/Backend/FileBackend.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 88 "../src/Backend/FileBackend.vala"
		*array = g_renew (AgendaTask*, *array, (*size) + 1);
#line 502 "FileBackend.c"
	}
#line 88 "../src/Backend/FileBackend.vala"
	(*array)[(*length)++] = value;
#line 88 "../src/Backend/FileBackend.vala"
	(*array)[*length] = NULL;
#line 508 "FileBackend.c"
}

static AgendaTask**
agenda_file_backend_real_load_tasks (AgendaBackend* base,
                                     gint* result_length1)
{
	AgendaFileBackend * self;
	AgendaTask** tasks = NULL;
	AgendaTask** _tmp0_;
	gint tasks_length1;
	gint _tasks_size_;
	AgendaTask** _tmp28_;
	gint _tmp28__length1;
	GError* _inner_error0_ = NULL;
	AgendaTask** result = NULL;
#line 70 "../src/Backend/FileBackend.vala"
	self = (AgendaFileBackend*) base;
#line 71 "../src/Backend/FileBackend.vala"
	_tmp0_ = g_new0 (AgendaTask*, 0 + 1);
#line 71 "../src/Backend/FileBackend.vala"
	tasks = _tmp0_;
#line 71 "../src/Backend/FileBackend.vala"
	tasks_length1 = 0;
#line 71 "../src/Backend/FileBackend.vala"
	_tasks_size_ = tasks_length1;
#line 534 "FileBackend.c"
	{
		gchar* line = NULL;
		GFileInputStream* file_input_stream = NULL;
		GFile* _tmp1_;
		GFileInputStream* _tmp2_;
		GDataInputStream* f_dis = NULL;
		GFileInputStream* _tmp3_;
		GDataInputStream* _tmp4_;
#line 75 "../src/Backend/FileBackend.vala"
		_tmp1_ = self->priv->task_file;
#line 75 "../src/Backend/FileBackend.vala"
		_tmp2_ = g_file_read (_tmp1_, NULL, &_inner_error0_);
#line 75 "../src/Backend/FileBackend.vala"
		file_input_stream = _tmp2_;
#line 75 "../src/Backend/FileBackend.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 75 "../src/Backend/FileBackend.vala"
			_g_free0 (line);
#line 553 "FileBackend.c"
			goto __catch0_g_error;
		}
#line 76 "../src/Backend/FileBackend.vala"
		_tmp3_ = file_input_stream;
#line 76 "../src/Backend/FileBackend.vala"
		_tmp4_ = g_data_input_stream_new ((GInputStream*) _tmp3_);
#line 76 "../src/Backend/FileBackend.vala"
		f_dis = _tmp4_;
#line 78 "../src/Backend/FileBackend.vala"
		while (TRUE) {
#line 564 "FileBackend.c"
			gchar* _tmp5_ = NULL;
			GDataInputStream* _tmp6_;
			gchar* _tmp7_;
			gchar* _tmp8_;
			const gchar* _tmp9_;
			gchar** task_line = NULL;
			const gchar* _tmp10_;
			gchar** _tmp11_;
			gchar** _tmp12_;
			gint task_line_length1;
			gint _task_line_size_;
			AgendaTask* task = NULL;
			AgendaTask* _tmp13_;
			AgendaTask* _tmp14_;
			gchar** _tmp15_;
			gint _tmp15__length1;
			const gchar* _tmp16_;
			gchar** _tmp17_;
			gint _tmp17__length1;
			const gchar* _tmp18_;
			AgendaTask* _tmp21_;
			AgendaTask* _tmp22_;
#line 78 "../src/Backend/FileBackend.vala"
			_tmp6_ = f_dis;
#line 78 "../src/Backend/FileBackend.vala"
			_tmp7_ = g_data_input_stream_read_line (_tmp6_, NULL, NULL, &_inner_error0_);
#line 78 "../src/Backend/FileBackend.vala"
			_tmp5_ = _tmp7_;
#line 78 "../src/Backend/FileBackend.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 78 "../src/Backend/FileBackend.vala"
				_g_object_unref0 (f_dis);
#line 78 "../src/Backend/FileBackend.vala"
				_g_object_unref0 (file_input_stream);
#line 78 "../src/Backend/FileBackend.vala"
				_g_free0 (line);
#line 601 "FileBackend.c"
				goto __catch0_g_error;
			}
#line 78 "../src/Backend/FileBackend.vala"
			_tmp8_ = _tmp5_;
#line 78 "../src/Backend/FileBackend.vala"
			_tmp5_ = NULL;
#line 78 "../src/Backend/FileBackend.vala"
			_g_free0 (line);
#line 78 "../src/Backend/FileBackend.vala"
			line = _tmp8_;
#line 78 "../src/Backend/FileBackend.vala"
			_tmp9_ = line;
#line 78 "../src/Backend/FileBackend.vala"
			if (!(_tmp9_ != NULL)) {
#line 78 "../src/Backend/FileBackend.vala"
				_g_free0 (_tmp5_);
#line 78 "../src/Backend/FileBackend.vala"
				break;
#line 620 "FileBackend.c"
			}
#line 79 "../src/Backend/FileBackend.vala"
			_tmp10_ = line;
#line 79 "../src/Backend/FileBackend.vala"
			_tmp12_ = _tmp11_ = g_strsplit (_tmp10_, ",", 2);
#line 79 "../src/Backend/FileBackend.vala"
			task_line = _tmp12_;
#line 79 "../src/Backend/FileBackend.vala"
			task_line_length1 = _vala_array_length (_tmp11_);
#line 79 "../src/Backend/FileBackend.vala"
			_task_line_size_ = task_line_length1;
#line 80 "../src/Backend/FileBackend.vala"
			_tmp13_ = agenda_task_new ();
#line 80 "../src/Backend/FileBackend.vala"
			task = _tmp13_;
#line 81 "../src/Backend/FileBackend.vala"
			_tmp14_ = task;
#line 81 "../src/Backend/FileBackend.vala"
			_tmp15_ = task_line;
#line 81 "../src/Backend/FileBackend.vala"
			_tmp15__length1 = task_line_length1;
#line 81 "../src/Backend/FileBackend.vala"
			_tmp16_ = _tmp15_[1];
#line 81 "../src/Backend/FileBackend.vala"
			agenda_task_set_text (_tmp14_, _tmp16_);
#line 83 "../src/Backend/FileBackend.vala"
			_tmp17_ = task_line;
#line 83 "../src/Backend/FileBackend.vala"
			_tmp17__length1 = task_line_length1;
#line 83 "../src/Backend/FileBackend.vala"
			_tmp18_ = _tmp17_[0];
#line 83 "../src/Backend/FileBackend.vala"
			if (g_strcmp0 (_tmp18_, "t") == 0) {
#line 654 "FileBackend.c"
				AgendaTask* _tmp19_;
#line 84 "../src/Backend/FileBackend.vala"
				_tmp19_ = task;
#line 84 "../src/Backend/FileBackend.vala"
				agenda_task_set_complete (_tmp19_, TRUE);
#line 660 "FileBackend.c"
			} else {
				AgendaTask* _tmp20_;
#line 86 "../src/Backend/FileBackend.vala"
				_tmp20_ = task;
#line 86 "../src/Backend/FileBackend.vala"
				agenda_task_set_complete (_tmp20_, FALSE);
#line 667 "FileBackend.c"
			}
#line 88 "../src/Backend/FileBackend.vala"
			_tmp21_ = task;
#line 88 "../src/Backend/FileBackend.vala"
			_tmp22_ = _g_object_ref0 (_tmp21_);
#line 88 "../src/Backend/FileBackend.vala"
			_vala_array_add2 (&tasks, &tasks_length1, &_tasks_size_, _tmp22_);
#line 78 "../src/Backend/FileBackend.vala"
			_g_object_unref0 (task);
#line 78 "../src/Backend/FileBackend.vala"
			task_line = (_vala_array_free (task_line, task_line_length1, (GDestroyNotify) g_free), NULL);
#line 78 "../src/Backend/FileBackend.vala"
			_g_free0 (_tmp5_);
#line 681 "FileBackend.c"
		}
#line 73 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (f_dis);
#line 73 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (file_input_stream);
#line 73 "../src/Backend/FileBackend.vala"
		_g_free0 (line);
#line 689 "FileBackend.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp23_;
#line 73 "../src/Backend/FileBackend.vala"
		e = _inner_error0_;
#line 73 "../src/Backend/FileBackend.vala"
		_inner_error0_ = NULL;
#line 91 "../src/Backend/FileBackend.vala"
		_tmp23_ = e;
#line 91 "../src/Backend/FileBackend.vala"
		if (g_error_matches (_tmp23_, G_IO_ERROR, G_IO_ERROR_NOT_FOUND)) {
#line 704 "FileBackend.c"
			GError* _tmp24_;
			const gchar* _tmp25_;
#line 92 "../src/Backend/FileBackend.vala"
			_tmp24_ = e;
#line 92 "../src/Backend/FileBackend.vala"
			_tmp25_ = _tmp24_->message;
#line 92 "../src/Backend/FileBackend.vala"
			g_info ("FileBackend.vala:92: %s", _tmp25_);
#line 713 "FileBackend.c"
		} else {
			GError* _tmp26_;
			const gchar* _tmp27_;
#line 94 "../src/Backend/FileBackend.vala"
			_tmp26_ = e;
#line 94 "../src/Backend/FileBackend.vala"
			_tmp27_ = _tmp26_->message;
#line 94 "../src/Backend/FileBackend.vala"
			g_error ("FileBackend.vala:94: %s", _tmp27_);
#line 723 "FileBackend.c"
		}
#line 73 "../src/Backend/FileBackend.vala"
		_g_error_free0 (e);
#line 727 "FileBackend.c"
	}
	__finally0:
#line 73 "../src/Backend/FileBackend.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 73 "../src/Backend/FileBackend.vala"
		tasks = (_vala_array_free (tasks, tasks_length1, (GDestroyNotify) g_object_unref), NULL);
#line 73 "../src/Backend/FileBackend.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 73 "../src/Backend/FileBackend.vala"
		g_clear_error (&_inner_error0_);
#line 73 "../src/Backend/FileBackend.vala"
		return NULL;
#line 740 "FileBackend.c"
	}
#line 98 "../src/Backend/FileBackend.vala"
	_tmp28_ = tasks;
#line 98 "../src/Backend/FileBackend.vala"
	_tmp28__length1 = tasks_length1;
#line 98 "../src/Backend/FileBackend.vala"
	if (result_length1) {
#line 98 "../src/Backend/FileBackend.vala"
		*result_length1 = _tmp28__length1;
#line 750 "FileBackend.c"
	}
#line 98 "../src/Backend/FileBackend.vala"
	result = _tmp28_;
#line 98 "../src/Backend/FileBackend.vala"
	return result;
#line 756 "FileBackend.c"
}

static void
agenda_file_backend_real_save_history (AgendaBackend* base,
                                       gchar** history,
                                       gint history_length1)
{
	AgendaFileBackend * self;
	GFile* _tmp0_;
#line 101 "../src/Backend/FileBackend.vala"
	self = (AgendaFileBackend*) base;
#line 102 "../src/Backend/FileBackend.vala"
	_tmp0_ = self->priv->history_file;
#line 102 "../src/Backend/FileBackend.vala"
	agenda_file_backend_save_to_file (self, history, (gint) history_length1, _tmp0_);
#line 772 "FileBackend.c"
}

static void
_vala_array_add3 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
#line 109 "../src/Backend/FileBackend.vala"
	if ((*length) == (*size)) {
#line 109 "../src/Backend/FileBackend.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 109 "../src/Backend/FileBackend.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 787 "FileBackend.c"
	}
#line 109 "../src/Backend/FileBackend.vala"
	(*array)[(*length)++] = value;
#line 109 "../src/Backend/FileBackend.vala"
	(*array)[*length] = NULL;
#line 793 "FileBackend.c"
}

static void
agenda_file_backend_real_save_tasks (AgendaBackend* base,
                                     AgendaTask** tasks,
                                     gint tasks_length1)
{
	AgendaFileBackend * self;
	gchar** lines = NULL;
	gchar** _tmp0_;
	gint lines_length1;
	gint _lines_size_;
	gchar** _tmp4_;
	gint _tmp4__length1;
	GFile* _tmp5_;
#line 105 "../src/Backend/FileBackend.vala"
	self = (AgendaFileBackend*) base;
#line 106 "../src/Backend/FileBackend.vala"
	_tmp0_ = g_new0 (gchar*, 0 + 1);
#line 106 "../src/Backend/FileBackend.vala"
	lines = _tmp0_;
#line 106 "../src/Backend/FileBackend.vala"
	lines_length1 = 0;
#line 106 "../src/Backend/FileBackend.vala"
	_lines_size_ = lines_length1;
#line 819 "FileBackend.c"
	{
		AgendaTask** task_collection = NULL;
		gint task_collection_length1 = 0;
		gint _task_collection_size_ = 0;
		gint task_it = 0;
#line 108 "../src/Backend/FileBackend.vala"
		task_collection = tasks;
#line 108 "../src/Backend/FileBackend.vala"
		task_collection_length1 = tasks_length1;
#line 108 "../src/Backend/FileBackend.vala"
		for (task_it = 0; task_it < task_collection_length1; task_it = task_it + 1) {
#line 831 "FileBackend.c"
			AgendaTask* _tmp1_;
			AgendaTask* task = NULL;
#line 108 "../src/Backend/FileBackend.vala"
			_tmp1_ = _g_object_ref0 (task_collection[task_it]);
#line 108 "../src/Backend/FileBackend.vala"
			task = _tmp1_;
#line 838 "FileBackend.c"
			{
				AgendaTask* _tmp2_;
				gchar* _tmp3_;
#line 109 "../src/Backend/FileBackend.vala"
				_tmp2_ = task;
#line 109 "../src/Backend/FileBackend.vala"
				_tmp3_ = agenda_task_to_string (_tmp2_);
#line 109 "../src/Backend/FileBackend.vala"
				_vala_array_add3 (&lines, &lines_length1, &_lines_size_, _tmp3_);
#line 108 "../src/Backend/FileBackend.vala"
				_g_object_unref0 (task);
#line 850 "FileBackend.c"
			}
		}
	}
#line 112 "../src/Backend/FileBackend.vala"
	_tmp4_ = lines;
#line 112 "../src/Backend/FileBackend.vala"
	_tmp4__length1 = lines_length1;
#line 112 "../src/Backend/FileBackend.vala"
	_tmp5_ = self->priv->task_file;
#line 112 "../src/Backend/FileBackend.vala"
	agenda_file_backend_save_to_file (self, _tmp4_, (gint) _tmp4__length1, _tmp5_);
#line 105 "../src/Backend/FileBackend.vala"
	lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
#line 864 "FileBackend.c"
}

static void
agenda_file_backend_save_to_file (AgendaFileBackend* self,
                                  gchar** lines,
                                  gint lines_length1,
                                  GFile* file)
{
	GError* _inner_error0_ = NULL;
#line 115 "../src/Backend/FileBackend.vala"
	g_return_if_fail (self != NULL);
#line 115 "../src/Backend/FileBackend.vala"
	g_return_if_fail (file != NULL);
#line 878 "FileBackend.c"
	{
		GFileOutputStream* file_fos = NULL;
		GFileOutputStream* _tmp0_;
		GDataOutputStream* file_dos = NULL;
		GFileOutputStream* _tmp1_;
		GDataOutputStream* _tmp2_;
#line 117 "../src/Backend/FileBackend.vala"
		_tmp0_ = g_file_replace (file, NULL, FALSE, G_FILE_CREATE_NONE, NULL, &_inner_error0_);
#line 117 "../src/Backend/FileBackend.vala"
		file_fos = _tmp0_;
#line 117 "../src/Backend/FileBackend.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 891 "FileBackend.c"
			goto __catch0_g_error;
		}
#line 118 "../src/Backend/FileBackend.vala"
		_tmp1_ = file_fos;
#line 118 "../src/Backend/FileBackend.vala"
		_tmp2_ = g_data_output_stream_new ((GOutputStream*) _tmp1_);
#line 118 "../src/Backend/FileBackend.vala"
		file_dos = _tmp2_;
#line 900 "FileBackend.c"
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
#line 119 "../src/Backend/FileBackend.vala"
			line_collection = lines;
#line 119 "../src/Backend/FileBackend.vala"
			line_collection_length1 = lines_length1;
#line 119 "../src/Backend/FileBackend.vala"
			for (line_it = 0; line_it < line_collection_length1; line_it = line_it + 1) {
#line 912 "FileBackend.c"
				gchar* _tmp3_;
				gchar* line = NULL;
#line 119 "../src/Backend/FileBackend.vala"
				_tmp3_ = g_strdup (line_collection[line_it]);
#line 119 "../src/Backend/FileBackend.vala"
				line = _tmp3_;
#line 919 "FileBackend.c"
				{
					GDataOutputStream* _tmp4_;
					const gchar* _tmp5_;
					gchar* _tmp6_;
					gchar* _tmp7_;
#line 120 "../src/Backend/FileBackend.vala"
					_tmp4_ = file_dos;
#line 120 "../src/Backend/FileBackend.vala"
					_tmp5_ = line;
#line 120 "../src/Backend/FileBackend.vala"
					_tmp6_ = g_strconcat (_tmp5_, "\n", NULL);
#line 120 "../src/Backend/FileBackend.vala"
					_tmp7_ = _tmp6_;
#line 120 "../src/Backend/FileBackend.vala"
					g_data_output_stream_put_string (_tmp4_, _tmp7_, NULL, &_inner_error0_);
#line 120 "../src/Backend/FileBackend.vala"
					_g_free0 (_tmp7_);
#line 120 "../src/Backend/FileBackend.vala"
					if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 120 "../src/Backend/FileBackend.vala"
						_g_free0 (line);
#line 120 "../src/Backend/FileBackend.vala"
						_g_object_unref0 (file_dos);
#line 120 "../src/Backend/FileBackend.vala"
						_g_object_unref0 (file_fos);
#line 945 "FileBackend.c"
						goto __catch0_g_error;
					}
#line 119 "../src/Backend/FileBackend.vala"
					_g_free0 (line);
#line 950 "FileBackend.c"
				}
			}
		}
#line 116 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (file_dos);
#line 116 "../src/Backend/FileBackend.vala"
		_g_object_unref0 (file_fos);
#line 958 "FileBackend.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp8_;
#line 116 "../src/Backend/FileBackend.vala"
		e = _inner_error0_;
#line 116 "../src/Backend/FileBackend.vala"
		_inner_error0_ = NULL;
#line 123 "../src/Backend/FileBackend.vala"
		_tmp8_ = e->message;
#line 123 "../src/Backend/FileBackend.vala"
		g_error ("FileBackend.vala:123: Error: %s\n", _tmp8_);
#line 116 "../src/Backend/FileBackend.vala"
		_g_error_free0 (e);
#line 975 "FileBackend.c"
	}
	__finally0:
#line 116 "../src/Backend/FileBackend.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 116 "../src/Backend/FileBackend.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 116 "../src/Backend/FileBackend.vala"
		g_clear_error (&_inner_error0_);
#line 116 "../src/Backend/FileBackend.vala"
		return;
#line 986 "FileBackend.c"
	}
}

static void
agenda_file_backend_class_init (AgendaFileBackendClass * klass,
                                gpointer klass_data)
{
#line 23 "../src/Backend/FileBackend.vala"
	agenda_file_backend_parent_class = g_type_class_peek_parent (klass);
#line 23 "../src/Backend/FileBackend.vala"
	g_type_class_adjust_private_offset (klass, &AgendaFileBackend_private_offset);
#line 23 "../src/Backend/FileBackend.vala"
	G_OBJECT_CLASS (klass)->finalize = agenda_file_backend_finalize;
#line 1000 "FileBackend.c"
}

static void
agenda_file_backend_agenda_backend_interface_init (AgendaBackendIface * iface,
                                                   gpointer iface_data)
{
#line 23 "../src/Backend/FileBackend.vala"
	agenda_file_backend_agenda_backend_parent_iface = g_type_interface_peek_parent (iface);
#line 23 "../src/Backend/FileBackend.vala"
	iface->load_history = (gchar** (*) (AgendaBackend*, gint*)) agenda_file_backend_real_load_history;
#line 23 "../src/Backend/FileBackend.vala"
	iface->load_tasks = (AgendaTask** (*) (AgendaBackend*, gint*)) agenda_file_backend_real_load_tasks;
#line 23 "../src/Backend/FileBackend.vala"
	iface->save_history = (void (*) (AgendaBackend*, gchar**, gint)) agenda_file_backend_real_save_history;
#line 23 "../src/Backend/FileBackend.vala"
	iface->save_tasks = (void (*) (AgendaBackend*, AgendaTask**, gint)) agenda_file_backend_real_save_tasks;
#line 1017 "FileBackend.c"
}

static void
agenda_file_backend_instance_init (AgendaFileBackend * self,
                                   gpointer klass)
{
#line 23 "../src/Backend/FileBackend.vala"
	self->priv = agenda_file_backend_get_instance_private (self);
#line 1026 "FileBackend.c"
}

static void
agenda_file_backend_finalize (GObject * obj)
{
	AgendaFileBackend * self;
#line 23 "../src/Backend/FileBackend.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, AGENDA_TYPE_FILE_BACKEND, AgendaFileBackend);
#line 25 "../src/Backend/FileBackend.vala"
	_g_object_unref0 (self->priv->task_file);
#line 26 "../src/Backend/FileBackend.vala"
	_g_object_unref0 (self->priv->history_file);
#line 23 "../src/Backend/FileBackend.vala"
	G_OBJECT_CLASS (agenda_file_backend_parent_class)->finalize (obj);
#line 1041 "FileBackend.c"
}

static GType
agenda_file_backend_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AgendaFileBackendClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) agenda_file_backend_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AgendaFileBackend), 0, (GInstanceInitFunc) agenda_file_backend_instance_init, NULL };
	static const GInterfaceInfo agenda_backend_info = { (GInterfaceInitFunc) agenda_file_backend_agenda_backend_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType agenda_file_backend_type_id;
	agenda_file_backend_type_id = g_type_register_static (G_TYPE_OBJECT, "AgendaFileBackend", &g_define_type_info, 0);
	g_type_add_interface_static (agenda_file_backend_type_id, AGENDA_TYPE_BACKEND, &agenda_backend_info);
	AgendaFileBackend_private_offset = g_type_add_instance_private (agenda_file_backend_type_id, sizeof (AgendaFileBackendPrivate));
	return agenda_file_backend_type_id;
}

GType
agenda_file_backend_get_type (void)
{
	static volatile gsize agenda_file_backend_type_id__volatile = 0;
	if (g_once_init_enter (&agenda_file_backend_type_id__volatile)) {
		GType agenda_file_backend_type_id;
		agenda_file_backend_type_id = agenda_file_backend_get_type_once ();
		g_once_init_leave (&agenda_file_backend_type_id__volatile, agenda_file_backend_type_id);
	}
	return agenda_file_backend_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

